import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Sparkles } from 'lucide-react'
import { ExampleContent } from '@/components/ExampleContent'

export const metadata: Metadata = {
  title: 'See a Sample Result — FairFare',
  description:
    'See exactly what you get with FairFare — a real sample taxi fare result and tipping guide before you pay.',
  alternates: { canonical: 'https://fairfare.app/example' },
  openGraph: {
    title: 'Sample Result — FairFare',
    description: 'See a real taxi fare result and tipping guide before you pay.',
    url: 'https://fairfare.app/example',
  },
}

export default function ExamplePage() {
  return (
    <div className="space-y-5 pb-8">
      {/* Header */}
      <div className="space-y-1">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-7 h-7 rounded-lg bg-purple-900/40 flex items-center justify-center">
            <Sparkles size={14} className="text-purple-400" />
          </div>
          <span className="text-xs font-semibold text-purple-400 uppercase tracking-wider">Sample Result</span>
        </div>
        <h1 className="text-xl font-bold text-white">See what you get</h1>
        <p className="text-zinc-500 text-sm leading-relaxed">
          This is a real result for Bangkok. Your result will look identical — but for your actual route and country.
        </p>
      </div>

      {/* AI disclosure */}
      <div className="flex items-start gap-2.5 bg-zinc-900 border border-zinc-800 rounded-xl px-3.5 py-3">
        <span className="text-lg shrink-0">🤖</span>
        <p className="text-xs text-zinc-400 leading-relaxed">
          Scam warnings and tipping notes are AI-generated by Claude, personalised to your city and route.
          Fare ranges are calculated from official meter rates.
        </p>
      </div>

      {/* Interactive sample result */}
      <ExampleContent />

      {/* CTAs */}
      <div className="space-y-3 pt-2">
        <Link
          href="/taxi"
          className="flex items-center justify-center gap-2 w-full bg-purple-600 hover:bg-purple-700 text-white font-semibold py-3.5 rounded-xl transition-colors text-sm"
        >
          Check My Taxi Route <ArrowRight size={16} />
        </Link>
        <Link
          href="/tipping"
          className="flex items-center justify-center gap-2 w-full bg-teal-700 hover:bg-teal-800 text-white font-semibold py-3.5 rounded-xl transition-colors text-sm"
        >
          Get a Tipping Guide <ArrowRight size={16} />
        </Link>
        <p className="text-center text-xs text-zinc-600">From $0.99 · No account required · Instant result</p>
      </div>
    </div>
  )
}
