import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Sparkles } from 'lucide-react'
import { ExampleContent } from '@/components/ExampleContent'

export const metadata: Metadata = {
  title: 'See a Sample Result — FairFare',
  description:
    'See exactly what you get with FairFare — a real sample taxi fare result and tipping guide before you pay.',
  alternates: { canonical: 'https://fairfare.app/example' },
  openGraph: {
    title: 'Sample Result — FairFare',
    description: 'See a real taxi fare result and tipping guide before you pay.',
    url: 'https://fairfare.app/example',
  },
}

/**
 * Build a dark-styled Static Maps URL for the BKK Airport → Sukhumvit sample.
 * Uses a straight two-point path (no polyline encoding required for the sample).
 * Returns undefined when GOOGLE_MAPS_API_KEY is not set, or when the Maps
 * Static API is not enabled — TaxiResult silently hides the map section.
 */
function buildSampleMapUrl(): string | undefined {
  const key = process.env.GOOGLE_MAPS_API_KEY ?? process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
  if (!key) return undefined

  // Dark styles matching FairFare's zinc palette (same as buildRouteMapUrl)
  const styles = [
    'element:geometry|color:0x1c1c27',
    'element:geometry.stroke|color:0x2e2e3e',
    'element:labels.text.fill|color:0x686878',
    'element:labels.text.stroke|color:0x1c1c27',
    'feature:road|element:geometry|color:0x2d2d40',
    'feature:road.highway|element:geometry|color:0x3d3d5a',
    'feature:road.highway|element:geometry.stroke|color:0x242432',
    'feature:water|element:geometry|color:0x0d1117',
    'feature:landscape|element:geometry|color:0x1a1a28',
    'feature:poi|visibility:off',
    'feature:transit|visibility:off',
    'feature:administrative.land_parcel|visibility:off',
  ]

  const params = [
    'size=640x320',
    'scale=2',
    'maptype=roadmap',
    ...styles.map(s => `style=${s}`),
    // Two-point path: Suvarnabhumi Airport → Sukhumvit Soi 11
    'path=color:0xa855f7ff|weight:4|13.6900,100.7501|13.7452,100.5547',
    'markers=color:0x9333ea|size:small|13.6900,100.7501',
    'markers=color:0x6b21a8|size:small|13.7452,100.5547',
    `key=${encodeURIComponent(key)}`,
  ]

  return `https://maps.googleapis.com/maps/api/staticmap?${params.join('&')}`
}

export default function ExamplePage() {
  const sampleMapUrl = buildSampleMapUrl()

  return (
    <div className="space-y-5 pb-8">
      {/* Header */}
      <div className="space-y-1">
        <div className="flex items-center gap-2 mb-2">
          <Link href="/" className="w-7 h-7 rounded-lg bg-purple-900/40 flex items-center justify-center hover:bg-purple-900/60 transition-colors shrink-0">
            <Sparkles size={14} className="text-purple-400" />
          </Link>
          <span className="text-xs font-semibold text-purple-400 uppercase tracking-wider">Sample Result</span>
        </div>
        <h1 className="text-xl font-bold text-white">See what you get</h1>
        <p className="text-zinc-500 text-sm leading-relaxed">
          This is a real result for Bangkok. Your result will look identical — but for your actual route and country.
        </p>
      </div>

      {/* Interactive sample result */}
      <ExampleContent sampleMapUrl={sampleMapUrl} />

      {/* CTAs */}
      <div className="space-y-3 pt-2">
        <Link
          href="/taxi"
          className="flex items-center justify-center gap-2 w-full bg-purple-600 hover:bg-purple-700 text-white font-semibold py-3.5 rounded-xl transition-colors text-sm"
        >
          Check My Taxi Route <ArrowRight size={16} />
        </Link>
        <Link
          href="/tipping"
          className="flex items-center justify-center gap-2 w-full bg-teal-700 hover:bg-teal-800 text-white font-semibold py-3.5 rounded-xl transition-colors text-sm"
        >
          Get a Tipping Guide <ArrowRight size={16} />
        </Link>
        <p className="text-center text-xs text-zinc-600">From $0.99 · No account required · Instant result</p>
      </div>

      {/* AI disclosure — fine print */}
      <p className="text-center text-xs text-zinc-700 leading-relaxed px-2">
        🤖 Scam warnings and tipping notes are AI-generated by Claude, personalised to your city and route.
        Fare ranges are calculated from official meter rates.
      </p>
    </div>
  )
}
