import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Hootling Terms of Service — the rules for using our taxi fare check and tipping guide service.',
}

const EFFECTIVE = '7 March 2026'
const CONTACT = 'legal@hootling.com'

export default function TermsPage() {
  return (
    <div className="space-y-6 pb-4">
      <div className="flex items-center gap-3">
        <Link href="/" className="w-10 h-10 rounded-xl bg-purple-600 flex items-center justify-center text-lg font-bold text-white hover:bg-purple-700 transition-colors shrink-0">
          H
        </Link>
        <div>
          <h1 className="text-xl font-bold text-white">Terms of Service</h1>
          <p className="text-xs text-zinc-500 mt-1">Effective {EFFECTIVE}</p>
        </div>
      </div>

      <p className="text-sm text-zinc-400 leading-relaxed">
        Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully before using Hootling
        (&ldquo;Service&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). By accessing or using
        the Service, you agree to be bound by these Terms.
      </p>

      <Section title="1. Description of Service">
        <p>
          Hootling provides on-demand information about taxi fare estimates and tipping customs
          for international destinations. Fare estimates are calculated using publicly available
          rate data combined with routing information from Google Maps. Tipping guidance and
          scam awareness content is generated by an AI assistant.
        </p>
        <p className="mt-2">
          The Service is a travel reference tool only. It is not a taxi dispatch, booking,
          or metering service, and has no affiliation with any taxi company, driver, or
          transportation authority.
        </p>
      </Section>

      <Section title="2. Payments and Refunds">
        <p>
          Access to full query results costs <strong className="text-white">$0.99 USD</strong> per
          query. Payment is processed securely by Stripe. We do not store your payment card
          details — all payment handling is performed by Stripe, Inc.
        </p>
        <p className="mt-2">
          Each payment grants you a single-use access token valid for 30 minutes. Tokens are
          non-transferable and cannot be shared between sessions or devices.
        </p>
        <p className="mt-2">
          Due to the instant digital nature of the Service, <strong className="text-white">all
          sales are final</strong>. Refunds are not provided once a query result has been
          delivered. If you experience a technical failure that prevents result delivery,
          contact us at <a href={`mailto:${CONTACT}`} className="text-purple-400 underline">{CONTACT}</a> and
          we will review your case within 5 business days.
        </p>
      </Section>

      <Section title="3. Accuracy Disclaimer">
        <p>
          Taxi fares, tipping norms, and travel safety conditions change frequently. While we
          strive to keep our data current, <strong className="text-white">we make no warranty
          that any information provided is accurate, complete, or current</strong> at the time
          of your query.
        </p>
        <p className="mt-2">
          Fare estimates are a reference range only. Actual fares may differ due to traffic,
          route changes, surcharges, local regulation changes, currency fluctuations, or driver
          discretion. Always confirm the fare directly with your driver before beginning a journey.
        </p>
        <p className="mt-2">
          AI-generated content (scam warnings, tipping advice, driver phrases) is produced by a
          third-party artificial intelligence model and reflects general training data. It may
          contain errors, hallucinations, or outdated information.{' '}
          <strong className="text-white">This content is not a substitute for local knowledge or
          professional travel advice.</strong> Exercise your own judgment when travelling.
        </p>
      </Section>

      <Section title="4. Acceptable Use">
        <p>You agree not to:</p>
        <ul className="mt-2 space-y-1.5 list-disc list-inside text-zinc-400">
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to reverse engineer, scrape, or systematically extract data from the Service</li>
          <li>Resell or redistribute query results without written permission</li>
          <li>Circumvent payment controls or exploit access tokens beyond their intended use</li>
          <li>Submit false or misleading information to influence query results</li>
        </ul>
      </Section>

      <Section title="5. Intellectual Property">
        <p>
          All content, design, and software comprising the Service is owned by or licensed to
          Hootling. You may not reproduce, distribute, or create derivative works from any part
          of the Service without our express written permission.
        </p>
        <p className="mt-2">
          Query results delivered to you are for your personal, non-commercial travel use only.
        </p>
      </Section>

      <Section title="6. Third-Party Services">
        <p>The Service relies on the following third-party providers, each with their own terms:</p>
        <ul className="mt-2 space-y-1.5 list-disc list-inside text-zinc-400">
          <li>
            <strong className="text-zinc-300">Google Maps Platform</strong> — routing, distance
            calculation, and location autocomplete. Mapping results are provided by Google Maps.
            Use of Google Maps features is subject to the{' '}
            <a href="https://maps.google.com/help/terms_maps/" target="_blank" rel="noopener noreferrer"
              className="text-purple-400 underline">Google Maps Terms of Service</a>.
          </li>
          <li>
            <strong className="text-zinc-300">Anthropic Claude</strong> — AI-generated travel
            safety and etiquette content
          </li>
          <li>
            <strong className="text-zinc-300">Stripe</strong> — payment processing
          </li>
          <li>
            <strong className="text-zinc-300">Vercel</strong> — hosting and privacy-first analytics
          </li>
        </ul>
        <p className="mt-2">
          We are not responsible for the availability, accuracy, or conduct of these third-party
          services.
        </p>
      </Section>

      <Section title="7. Limitation of Liability">
        <p>
          To the fullest extent permitted by applicable law, Hootling and its operators shall
          not be liable for any indirect, incidental, special, consequential, or punitive damages
          arising from your use of, or inability to use, the Service.
        </p>
        <p className="mt-2">
          Our total liability for any claim arising from these Terms or your use of the Service
          shall not exceed the amount you paid for the specific query giving rise to the claim.
        </p>
        <p className="mt-2">
          Nothing in these Terms excludes, restricts, or modifies any right, remedy, guarantee,
          warranty, or other term implied or imposed by legislation that cannot lawfully be
          excluded, including under the{' '}
          <strong className="text-white">Australian Consumer Law</strong> (Schedule 2 of the
          Competition and Consumer Act 2010 (Cth)).
        </p>
      </Section>

      <Section title="8. Indemnification">
        <p>
          You agree to indemnify and hold harmless Hootling and its operators from any claims,
          losses, or damages (including reasonable legal fees) arising out of your use of the
          Service or violation of these Terms.
        </p>
      </Section>

      <Section title="9. Changes to Terms">
        <p>
          We may update these Terms from time to time. The &ldquo;Effective&rdquo; date at the
          top of this page will reflect the most recent revision. Continued use of the Service
          after changes constitutes acceptance of the revised Terms.
        </p>
      </Section>

      <Section title="10. Governing Law">
        <p>
          These Terms shall be governed by and construed in accordance with the laws of{' '}
          <strong className="text-white">Victoria, Australia</strong>, without regard to conflict
          of law principles. Any disputes shall be subject to the exclusive jurisdiction of the
          courts of Victoria, Australia.
        </p>
        <p className="mt-2">
          If you are an Australian consumer, you may also have rights and remedies under the
          Australian Consumer Law (Schedule 2 of the Competition and Consumer Act 2010 (Cth))
          that cannot be excluded by these Terms.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these Terms? Contact us at{' '}
          <a href={`mailto:${CONTACT}`} className="text-purple-400 underline">{CONTACT}</a>.
        </p>
      </Section>

      <div className="pt-2 border-t border-zinc-800">
        <Link href="/" className="text-sm text-zinc-600 hover:text-zinc-400 transition-colors">
          ← Back to Hootling
        </Link>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-2">
      <h2 className="text-sm font-semibold text-white">{title}</h2>
      <div className="text-sm text-zinc-400 leading-relaxed">{children}</div>
    </div>
  )
}
