export interface BlogPost {
  slug: string
  title: string
  description: string
  publishedAt: string   // ISO date
  updatedAt?: string
  readingMinutes: number
  category: 'taxi' | 'tipping' | 'travel'
  city?: string
  country?: string
  citySlug?: string     // link to /taxi/[city] if it exists
  countrySlug?: string  // link to /tipping/[country] if it exists
  content: BlogSection[]
}

export interface BlogSection {
  type: 'intro' | 'h2' | 'h3' | 'p' | 'ul' | 'table' | 'tip' | 'warning' | 'faq'
  heading?: string
  body?: string
  items?: string[]
  rows?: { label: string; value: string }[]
  faqs?: { q: string; a: string }[]
}

export const BLOG_POSTS: BlogPost[] = [
  // ── Hootling Origin Story ──────────────────────────────────────────────────
  {
    slug: 'meet-hootling-the-travel-app-that-keeps-you-from-getting-ripped-off',
    title: 'Meet Hootling: The Travel App That Keeps You from Getting Ripped Off',
    description:
      'Introducing Hootling — the travel utility that checks taxi fares and tipping customs in 120+ cities worldwide. Know before you go. Pay right every time.',
    publishedAt: '2026-03-15',
    updatedAt: '2026-03-15',
    readingMinutes: 5,
    category: 'travel',
    content: [
      {
        type: 'intro',
        body: 'Every traveller has a story. A too-expensive taxi from the airport. An awkward moment at a restaurant table, wallet out, wondering if the locals tip here. We built Hootling to fix that.',
      },
      {
        type: 'h2',
        heading: 'The Problem Every Traveller Knows',
      },
      {
        type: 'p',
        body: 'You land in Bangkok after a long-haul flight. You\'re tired, you have luggage, and a driver is waiting with a hand-written sign. He quotes you 800 baht. Is that right? Is that a rip-off? You have no idea. You accept it because you don\'t know any better. Later, you find out the metered fare should have been 280 baht.\n\nThat moment — the uncertainty, the powerlessness — happens to millions of travellers every year. Not because they\'re careless. Because they simply didn\'t have the right information at the right time.',
      },
      {
        type: 'h2',
        heading: 'Why We Built Hootling',
      },
      {
        type: 'p',
        body: 'Hootling was built on one belief: travel should feel empowering, not anxious. When you know the fair price of a taxi before you get in, you negotiate from confidence, not desperation. When you know that tipping is offensive in Japan but expected in New York, you don\'t make cultural missteps that can sour an interaction.\n\nThe name \'Hootling\' comes from the English diminutive \'-ling\' — meaning a baby or young owl. Owls are symbols of wisdom, local knowledge, and the ability to navigate the dark. A Hootling is a wise little companion for your travels — always there when you need to know something fast.',
      },
      {
        type: 'h2',
        heading: 'What Hootling Does',
      },
      {
        type: 'p',
        body: 'Hootling has two core features:',
      },
      {
        type: 'ul',
        items: [
          '**Taxi Fare Check** — Enter your pickup and destination. Get a fair fare range in local currency, city-specific scam warnings, and a phrase to confirm the fare with your driver in their language. Powered by real local meter rate data from 120+ cities.',
          '**Tipping Guide** — Select a country. Get tipping etiquette for restaurants, taxis, hotel porters, bars, tour guides, and delivery. Know exactly how much to tip (or whether to tip at all) before you reach for your wallet.',
        ],
      },
      {
        type: 'h2',
        heading: 'How It Works',
      },
      {
        type: 'p',
        body: 'Fare estimates are calculated from a curated dataset of official local taxi meter rates, combined with real-time route distances from Google Maps. AI-powered scam warnings are generated by Anthropic Claude and tailored to your specific city and route. Results unlock for a small one-time fee — no subscription, no account, no tracking.',
      },
      {
        type: 'tip',
        body: 'Hootling costs less than the difference between a fair fare and a tourist trap fare. One Bangkok taxi check pays for itself in the first ride.',
      },
      {
        type: 'h2',
        heading: 'Travel Wise. Pay Right.',
      },
      {
        type: 'p',
        body: 'Hootling is built for the modern traveller — someone who moves fast, travels smart, and values their money without sacrificing experiences. Whether you\'re navigating the streets of Tokyo, tipping at a restaurant in Rome, or hailing a cab outside Dubai Airport, Hootling has the answer in seconds.\n\nTry it at hootling.com.',
      },
    ],
  },

  // ── Why Tipping Is So Confusing ────────────────────────────────────────────
  {
    slug: 'why-tipping-is-so-confusing-and-how-to-get-it-right',
    title: 'Why Tipping Is So Confusing (And How to Get It Right Every Time)',
    description:
      'Tipping customs vary wildly by country. In Japan it can be offensive. In the US it\'s almost mandatory. Here\'s how to tip correctly wherever you are in the world.',
    publishedAt: '2026-03-14',
    updatedAt: '2026-03-15',
    readingMinutes: 6,
    category: 'tipping',
    content: [
      {
        type: 'intro',
        body: 'Tipping is one of the most anxiety-inducing moments in international travel. Get it wrong and you might offend your host, embarrass yourself, or overpay significantly. Here\'s everything you need to know.',
      },
      {
        type: 'h2',
        heading: 'The Three Types of Tipping Cultures',
      },
      {
        type: 'p',
        body: 'Countries broadly fall into three tipping categories:',
      },
      {
        type: 'ul',
        items: [
          '**Expected (USA, Canada, some Middle East)** — Not tipping is considered rude. 15–20% at restaurants is standard in the US. Taxi drivers, hotel porters, and bar staff all expect something.',
          '**Optional (UK, Australia, most of Europe)** — Tipping is appreciated but not required. Rounding up the bill or leaving small change is common and well-received.',
          '**Offensive or Unnecessary (Japan, South Korea, China)** — Tipping can imply the worker isn\'t paid fairly, which can cause embarrassment. In Japan, it\'s best not to tip at all in most situations.',
        ],
      },
      {
        type: 'h2',
        heading: 'The 6 Scenarios Where Tipping Matters',
      },
      {
        type: 'p',
        body: 'Hootling\'s tipping guides cover six key scenarios where you\'re most likely to face a tipping decision:',
      },
      {
        type: 'ul',
        items: [
          'Restaurants & cafés',
          'Taxis & rideshare drivers',
          'Hotel porters & housekeeping',
          'Bars & nightlife',
          'Tour guides & day trips',
          'Spa, massage & wellness',
        ],
      },
      {
        type: 'h2',
        heading: 'A Country-by-Country Cheat Sheet',
      },
      {
        type: 'table',
        rows: [
          { label: 'USA', value: 'Restaurants: 15–20% · Taxis: 15–20% · Hotels: $2–5/bag' },
          { label: 'UK', value: 'Restaurants: 10–15% optional · Taxis: Round up · Hotels: £1–2/bag' },
          { label: 'Japan', value: 'Restaurants: Not expected · Taxis: Not expected · Hotels: Not expected' },
          { label: 'Australia', value: 'Restaurants: 5–10% optional · Taxis: Round up · Hotels: Optional' },
          { label: 'France', value: 'Restaurants: 5–10% optional · Taxis: Round up · Hotels: €1–2/bag' },
          { label: 'Thailand', value: 'Restaurants: 10–15% appreciated · Taxis: Round up · Hotels: Optional' },
        ],
      },
      {
        type: 'h2',
        heading: 'How Hootling Makes Tipping Simple',
      },
      {
        type: 'p',
        body: 'Rather than memorising every country\'s customs, Hootling looks it up for you. Select your destination country and get instant, AI-verified tipping guidance for all six scenarios — with cultural context, exact amounts in local currency, and a phrase to use in the local language.',
      },
      {
        type: 'tip',
        body: 'Always check tipping customs before you travel, not after the bill arrives. Hootling\'s tipping guides are available for 50+ countries.',
      },
    ],
  },

  // ── 5 Most Common Taxi Scams ───────────────────────────────────────────────
  {
    slug: '5-most-common-taxi-scams-and-how-to-avoid-them',
    title: 'The 5 Most Common Taxi Scams (And How to Avoid Every One)',
    description:
      'Taxi scams cost travellers millions every year. Here are the 5 most common tricks drivers use worldwide, and exactly how to protect yourself in every city.',
    publishedAt: '2026-03-13',
    updatedAt: '2026-03-15',
    readingMinutes: 7,
    category: 'taxi',
    content: [
      {
        type: 'intro',
        body: 'Taxi scams are the most common way travellers lose money abroad. They happen in every country, at every income level, to experienced travellers and first-timers alike. Knowing the playbook is the best defence.',
      },
      {
        type: 'h2',
        heading: 'Scam #1: The Broken Meter',
      },
      {
        type: 'p',
        body: 'The driver claims the meter isn\'t working and offers a \'special\' flat rate. That flat rate is almost always 2–5x the metered fare.',
      },
      {
        type: 'warning',
        body: 'Never accept a flat rate before asking what the metered fare would be. If the meter is genuinely broken, find another taxi or use a ride-hailing app.',
      },
      {
        type: 'h2',
        heading: 'Scam #2: The Long Route',
      },
      {
        type: 'p',
        body: 'The driver takes an unnecessarily long or circuitous route, running the meter up without you realising. This is particularly common from airports where you don\'t know the city layout.',
      },
      {
        type: 'tip',
        body: 'Before getting in, open Google Maps and note the approximate route. If the driver deviates significantly, politely ask them to follow the GPS route.',
      },
      {
        type: 'h2',
        heading: 'Scam #3: Price Change on Arrival',
      },
      {
        type: 'p',
        body: 'You agree on a price before departure, but when you arrive, the driver claims the price was per person, or that traffic/luggage makes it more expensive. Suddenly the agreed 200 baht becomes 600.',
      },
      {
        type: 'tip',
        body: 'Always confirm: \'This is the total price, for this journey, for [number] people, including luggage?\' before you leave.',
      },
      {
        type: 'h2',
        heading: 'Scam #4: The Hotel Switch',
      },
      {
        type: 'p',
        body: 'The driver insists your hotel is closed, full, or \'not safe\' and takes you to a different hotel where he gets a commission. This is extremely common in parts of Southeast Asia and India.',
      },
      {
        type: 'warning',
        body: 'If a driver says your hotel is closed, don\'t believe them without checking yourself. Call the hotel directly or show the driver a booking confirmation.',
      },
      {
        type: 'h2',
        heading: 'Scam #5: Airport Unofficial Taxis',
      },
      {
        type: 'p',
        body: 'Touts approach you in the arrivals hall offering \'official\' taxi services. They have lanyards, uniforms, and clipboards. They are not official. Airport taxi ranks are always outside the terminal, not inside arrivals.',
      },
      {
        type: 'tip',
        body: 'Always use the official taxi rank (signposted by the airport), a pre-booked transfer, or a verified ride-hailing app. Never follow someone who approaches you inside the terminal.',
      },
      {
        type: 'h2',
        heading: 'How to Protect Yourself in Any City',
      },
      {
        type: 'ul',
        items: [
          '**Know the fair price before you get in** — Use Hootling to check the fare range for your route before departure.',
          '**Screenshot the route** — Open Google Maps, enter your destination, take a screenshot of the recommended route.',
          '**Use metered taxis or ride-hailing apps** — Uber, Grab, Bolt, and local equivalents make price scams nearly impossible.',
          '**Pay with exact change when possible** — Overpaying \'because the driver has no change\' is a common minor scam.',
          '**Know the phrase** — Hootling provides a phrase in the local language to say: \'Please use the meter\' or \'I know the fair price.\'',
        ],
      },
      {
        type: 'tip',
        body: 'Hootling\'s taxi fare check gives you a city-specific scam warning list tailored to your exact route, plus the local phrase to use with your driver. Available for 120+ cities.',
      },
    ],
  },

  // ── 1. Bangkok ─────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-bangkok',
    title: 'How Much Does a Taxi Cost in Bangkok? (2026 Fare Guide)',
    description:
      'Real Bangkok taxi meter rates, sample fares from Suvarnabhumi Airport, scam warnings, and Grab vs taxi comparison for 2026.',
    publishedAt: '2026-03-01',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Bangkok',
    country: 'Thailand',
    citySlug: 'bangkok',
    countrySlug: 'thailand',
    content: [
      {
        type: 'intro',
        body: 'Bangkok taxis are some of the cheapest in Southeast Asia — but only if the meter is running. Here is exactly what you should pay in 2026, how to avoid the most common scams, and when Grab is a better choice.',
      },
      {
        type: 'h2',
        heading: 'Bangkok Taxi Meter Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall (first 2 km)', value: '฿35' },
          { label: 'Per km (2–10 km)', value: '฿6.50' },
          { label: 'Per km (over 10 km)', value: '฿5.50' },
          { label: 'Waiting time', value: '฿3 per minute' },
          { label: 'Minimum fare', value: '฿35' },
          { label: 'Airport surcharge (from BKK/DMK)', value: '฿50' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Fares: Airport to City',
      },
      {
        type: 'table',
        rows: [
          { label: 'BKK Airport → Sukhumvit', value: '฿280–400 + ฿50–75 expressway toll' },
          { label: 'BKK Airport → Silom', value: '฿300–430 + ฿75 expressway toll' },
          { label: 'BKK Airport → Khao San Road', value: '฿350–500 + ฿75 expressway toll' },
          { label: 'City centre → Grand Palace', value: '฿60–100' },
          { label: 'City centre → Chatuchak Market', value: '฿80–130' },
        ],
      },
      {
        type: 'h2',
        heading: 'Common Bangkok Taxi Scams',
      },
      {
        type: 'ul',
        items: [
          '"Meter broken" — driver offers a flat rate of ฿300–500. Decline and take the next taxi.',
          'Taxi rank touts inside Suvarnabhumi arrivals hall. Always use Level 1 official queue.',
          '"Hotel closed today" — driver claims your hotel is shut and diverts to a partner hotel paying commission.',
          'Long route without taking expressways, then charging for tolls that were never paid.',
        ],
      },
      {
        type: 'h2',
        heading: 'Grab vs Taxi in Bangkok',
      },
      {
        type: 'p',
        body: 'Grab is reliable, price-fixed, and cashless — ideal if you want certainty. However, surge pricing applies during peak hours and rain. A metered taxi is often 10–30% cheaper than Grab\'s standard price during off-peak hours, but adds uncertainty if the driver refuses the meter.',
      },
      {
        type: 'tip',
        body: 'Grab tip: Enable the "GrabTaxi" option inside the app to hail metered taxis via Grab — you get the meter rate with Grab\'s accountability.',
      },
      {
        type: 'h2',
        heading: 'Frequently Asked Questions',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Bangkok airport to the city?', a: 'Expect ฿280–450 on the meter plus a ฿50 airport surcharge and ฿50–75 in expressway tolls. Total: approximately ฿380–575 (about $10–16 USD).' },
          { q: 'Can I pay by card in Bangkok taxis?', a: 'Almost all Bangkok taxis are cash only. Bring Thai Baht. ATMs are available at the airport.' },
          { q: 'Is tipping expected in Bangkok taxis?', a: 'Tipping is not expected. Rounding up to the nearest ฿10 is a common courtesy.' },
          { q: 'What is the fastest way from BKK airport to Bangkok?', a: 'The Airport Rail Link express train (฿150) takes 15 minutes to Phaya Thai. Taxis take 35–90 minutes depending on traffic.' },
        ],
      },
    ],
  },

  // ── 2. Dubai ───────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-dubai',
    title: 'How Much Does a Taxi Cost in Dubai? (2026 Rates)',
    description:
      'Dubai taxi meter rates, airport fares, tipping customs, and Uber vs Careem comparison for 2026.',
    publishedAt: '2026-03-02',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Dubai',
    country: 'UAE',
    citySlug: 'dubai',
    countrySlug: 'uae',
    content: [
      {
        type: 'intro',
        body: 'Dubai\'s official taxis are metered, well-regulated, and air-conditioned. Fares are slightly higher than Southeast Asia but reasonable for a global hub. Here\'s what to expect in 2026.',
      },
      {
        type: 'h2',
        heading: 'Dubai Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall (day)', value: 'AED 12' },
          { label: 'Flag fall (night 10 pm–6 am)', value: 'AED 12' },
          { label: 'Per km', value: 'AED 1.97' },
          { label: 'Minimum fare', value: 'AED 12' },
          { label: 'Airport surcharge (from DXB)', value: 'AED 3' },
          { label: 'Night surcharge (midnight–6 am)', value: '25% of meter' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Fares from Dubai Airport',
      },
      {
        type: 'table',
        rows: [
          { label: 'DXB → Downtown Dubai / Burj Khalifa', value: 'AED 50–75' },
          { label: 'DXB → Dubai Marina', value: 'AED 80–120' },
          { label: 'DXB → Palm Jumeirah', value: 'AED 85–130' },
          { label: 'DXB → Deira (city centre)', value: 'AED 25–40' },
          { label: 'DXB → Sharjah', value: 'AED 60–80 + AED 20 surcharge' },
        ],
      },
      {
        type: 'h2',
        heading: 'Uber vs Careem vs Dubai Taxi',
      },
      {
        type: 'p',
        body: 'Careem (owned by Uber) and Uber both operate in Dubai with fixed upfront prices. Both are typically AED 5–15 cheaper than a metered taxi for long routes to Marina and JBR. However, during peak times the apps surge while taxis remain metered.',
      },
      {
        type: 'warning',
        body: 'Beware unofficial drivers in the arrivals hall at DXB. Only use Dubai Taxi Corporation (cream/beige cabs) or rideshare apps.',
      },
      {
        type: 'h2',
        heading: 'Is Tipping Expected in Dubai Taxis?',
      },
      {
        type: 'p',
        body: 'Tipping is not mandatory in Dubai taxis. Rounding up to the nearest AED 5 or 10 is a common courtesy and appreciated. For a AED 67 fare, giving AED 70 is perfectly normal.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Dubai airport to Downtown?', a: 'Approximately AED 50–75 including the AED 3 airport surcharge. The trip takes 15–25 minutes.' },
          { q: 'Are taxis metered in Dubai?', a: 'Yes — all official Dubai Taxi Corporation cabs use digital meters. Insist on the meter if it\'s not running.' },
          { q: 'Can I book a taxi from Dubai airport in advance?', a: 'Yes — use the Dubai Taxi app (by RTA) to pre-book with a fixed fare shown upfront.' },
        ],
      },
    ],
  },

  // ── 3. Singapore ───────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-singapore',
    title: 'How Much Does a Taxi Cost in Singapore? (2026 Guide)',
    description:
      'Singapore taxi fare structure, airport surcharges, ERP tolls explained, and when to use Grab instead for 2026.',
    publishedAt: '2026-03-03',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Singapore',
    country: 'Singapore',
    citySlug: 'singapore',
    countrySlug: 'singapore',
    content: [
      {
        type: 'intro',
        body: 'Singapore taxis are efficient and well-regulated, but the fare structure is complex: airport surcharges, ERP road tolls, peak-hour surcharges, and midnight fees all stack up. Here\'s what you\'ll actually pay in 2026.',
      },
      {
        type: 'h2',
        heading: 'Singapore Taxi Base Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall (first 1 km)', value: 'S$3.90' },
          { label: 'Per 400 m (up to 10 km)', value: 'S$0.25' },
          { label: 'Per 350 m (over 10 km)', value: 'S$0.25' },
          { label: 'Waiting time', value: 'S$0.25 per 45 seconds' },
          { label: 'Airport surcharge (peak)', value: 'S$8' },
          { label: 'Airport surcharge (other hours)', value: 'S$5' },
          { label: 'Midnight surcharge (12 am–5:59 am)', value: '50% of meter' },
          { label: 'Peak-hour surcharge (Mon–Fri 6–9:30 am, 6–11 pm)', value: '25% of meter' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Fares from Changi Airport',
      },
      {
        type: 'table',
        rows: [
          { label: 'SIN → Orchard Road', value: 'S$28–42 (incl. surcharges)' },
          { label: 'SIN → Marina Bay Sands', value: 'S$26–38 (incl. surcharges)' },
          { label: 'SIN → Sentosa', value: 'S$32–48 (incl. S$3 Sentosa surcharge)' },
          { label: 'SIN → Jurong East', value: 'S$30–45' },
        ],
      },
      {
        type: 'tip',
        body: 'The MRT (Changi Airport → City) costs just S$2.30 and takes 30 minutes. Unless you have heavy luggage, it\'s the best option for solo travellers.',
      },
      {
        type: 'h2',
        heading: 'Grab vs Taxi in Singapore',
      },
      {
        type: 'p',
        body: 'Grab is the dominant rideshare in Singapore. It offers a fixed upfront price that avoids surprises from surcharges and tolls. For airport trips, Grab is usually S$2–5 cheaper than metered taxis with surge, and you can compare both options in the app.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'Why is my Singapore taxi bill higher than expected?', a: 'Singapore taxis have multiple surcharges that stack: airport fee, peak hour fee, ERP tolls (road pricing), and late-night fees. Always confirm total at destination.' },
          { q: 'Is tipping expected in Singapore taxis?', a: 'Tipping is not expected or common in Singapore. Most Singaporeans do not tip taxi drivers.' },
          { q: 'Can I pay by card in Singapore taxis?', a: 'Most Singapore taxis accept NETS, Visa, and Mastercard. Contactless payment is widely available.' },
        ],
      },
    ],
  },

  // ── 4. London ──────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-london',
    title: 'How Much Does a Taxi Cost in London? (2026 Black Cab Fares)',
    description:
      'London black cab meter rates, Heathrow taxi fares, Uber vs black cab comparison, and how to avoid unlicensed minicabs in 2026.',
    publishedAt: '2026-03-04',
    readingMinutes: 7,
    category: 'taxi',
    city: 'London',
    country: 'United Kingdom',
    citySlug: 'london',
    countrySlug: 'united-kingdom',
    content: [
      {
        type: 'intro',
        body: 'London\'s black cabs are iconic but expensive. Uber and Bolt are often 40–60% cheaper. Here\'s exactly what you\'ll pay for both in 2026, and how to stay safe.',
      },
      {
        type: 'h2',
        heading: 'London Black Cab Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall', value: '£3.80' },
          { label: 'Per km (Tariff 1: Mon–Fri 6 am–10 pm)', value: '£2.10' },
          { label: 'Per km (Tariff 2: evenings, weekends)', value: '£2.50' },
          { label: 'Per km (Tariff 3: Christmas, New Year)', value: '£2.80' },
          { label: 'Extras (each additional passenger)', value: '£0.20' },
          { label: 'Extras (large luggage)', value: '£0.40' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Black Cab Fares',
      },
      {
        type: 'table',
        rows: [
          { label: 'Heathrow → Central London', value: '£55–85 (depends on traffic)' },
          { label: 'King\'s Cross → Shoreditch', value: '£12–18' },
          { label: 'Paddington → Canary Wharf', value: '£28–40' },
          { label: 'Victoria → Brixton', value: '£15–22' },
          { label: 'Gatwick → Central London', value: '£90–120 (negotiate fixed fare)' },
        ],
      },
      {
        type: 'h2',
        heading: 'Uber vs Black Cab in London',
      },
      {
        type: 'p',
        body: 'For a typical £18 black cab fare, Uber uberX will show roughly £9–12. The trade-off: black cabs can be hailed on the street and have more stringent driver checks. Uber requires booking via app but is generally safe and licensed by TfL.',
      },
      {
        type: 'warning',
        body: 'Unlicensed minicabs ("touts") in central London are illegal and unsafe. Never get into a car that was not pre-booked via a licensed app or dispatched firm.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much should I tip a London black cab driver?', a: 'Rounding up to the nearest pound is common. A 10% tip is generous. There is no obligation to tip.' },
          { q: 'Is it safe to take Uber in London?', a: 'Yes — Uber is licensed by Transport for London (TfL) and undergoes regular compliance checks. It is a safe alternative to black cabs.' },
          { q: 'Can I hail an Uber on the street in London?', a: 'No — Ubers must be booked via the app. Black cabs (hackney carriages) can be hailed on the street with an illuminated yellow TAXI sign.' },
        ],
      },
    ],
  },

  // ── 5. New York ────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-new-york',
    title: 'How Much Does a Taxi Cost in New York? (2026 Yellow Cab Guide)',
    description:
      'New York yellow cab rates, JFK flat rate explained, tips and surcharges breakdown, and when Uber is cheaper in 2026.',
    publishedAt: '2026-03-05',
    readingMinutes: 7,
    category: 'taxi',
    city: 'New York',
    country: 'United States',
    citySlug: 'new-york',
    countrySlug: 'united-states',
    content: [
      {
        type: 'intro',
        body: 'New York yellow cabs operate on a metered system with multiple surcharges that can add 40–50% to the base meter. For JFK airport trips, there\'s a flat $70 rate to Manhattan. Here\'s the full breakdown for 2026.',
      },
      {
        type: 'h2',
        heading: 'NYC Yellow Cab Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Initial charge', value: '$3.00' },
          { label: 'Per mile', value: '$2.50' },
          { label: 'Per minute (slow traffic)', value: '$0.50' },
          { label: 'Night surcharge (8 pm–6 am)', value: '+$0.50' },
          { label: 'Congestion Surcharge (below 96th St, Manhattan)', value: '+$2.50' },
          { label: 'New York State surcharge', value: '+$0.30' },
          { label: 'JFK Airport flat rate to Manhattan', value: '$70.00 (excl. tolls)' },
        ],
      },
      {
        type: 'h2',
        heading: 'Understanding the JFK Flat Rate',
      },
      {
        type: 'p',
        body: 'The $70 flat rate applies to any destination in Manhattan from JFK. This does NOT include bridge/tunnel tolls ($8.50–19), congestion pricing, and tip. A JFK → Midtown taxi trip typically costs $85–105 all-in at a 20% tip.',
      },
      {
        type: 'h2',
        heading: 'Sample NYC Taxi Fares',
      },
      {
        type: 'table',
        rows: [
          { label: 'JFK → Manhattan (all neighbourhoods)', value: '$85–105 all-in (flat $70 + tolls + tip)' },
          { label: 'LaGuardia → Midtown Manhattan', value: '$35–55 + tolls + tip' },
          { label: 'Times Square → Brooklyn (metered)', value: '$25–45 + tolls + tip' },
          { label: 'Grand Central → JFK', value: '$70 + tolls + tip' },
          { label: 'Within Midtown Manhattan (short)', value: '$10–18 + tip' },
        ],
      },
      {
        type: 'tip',
        body: 'Always tip 20% in NYC. Cab drivers rely on tips as part of their income, and 20% is the local norm. 15% is acceptable for a basic ride.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How do I pay in a New York yellow cab?', a: 'All NYC yellow cabs accept credit/debit cards at the in-car terminal. Tap-to-pay (contactless) works too. Cash is also accepted.' },
          { q: 'Is Uber cheaper than a yellow cab in NYC?', a: 'For most short to medium rides, Uber uberX is comparable to yellow cabs. For JFK, Uber\'s fixed price ($60–75) is often slightly cheaper than the $70 flat rate plus tolls.' },
          { q: 'What is congestion pricing in NYC?', a: 'Since 2025, most vehicles entering Manhattan below 60th Street pay a congestion surcharge. Taxis pass this fee to passengers via the $2.50 taxi surcharge.' },
        ],
      },
    ],
  },

  // ── 6. Tokyo ───────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-tokyo',
    title: 'How Much Does a Taxi Cost in Tokyo? (2026 Fare Guide)',
    description:
      'Tokyo taxi prices, Narita and Haneda airport fares, why taxis are expensive at night, and cheaper alternatives for 2026.',
    publishedAt: '2026-03-06',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Tokyo',
    country: 'Japan',
    citySlug: 'tokyo',
    countrySlug: 'japan',
    content: [
      {
        type: 'intro',
        body: 'Tokyo taxis are clean, reliable, and scam-free — but expensive by Asian standards. The train system is almost always the better option. Here\'s when it makes sense to take a taxi and what you\'ll pay.',
      },
      {
        type: 'h2',
        heading: 'Tokyo Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall (first 1.052 km)', value: '¥500' },
          { label: 'Per 237 m after', value: '¥100' },
          { label: 'Waiting (per 1 min 30 sec)', value: '¥100' },
          { label: 'Late-night surcharge (10 pm–5 am)', value: '20% extra' },
          { label: 'Highway tolls', value: 'Added to fare' },
        ],
      },
      {
        type: 'h2',
        heading: 'Airport Transfer Costs',
      },
      {
        type: 'table',
        rows: [
          { label: 'Narita Airport → Tokyo city centre', value: '¥20,000–30,000 (90 min)' },
          { label: 'Haneda Airport → Tokyo city centre', value: '¥6,000–12,000 (40 min)' },
          { label: 'Shinjuku → Shibuya', value: '¥1,200–1,800' },
          { label: 'Shinjuku → Tokyo Station', value: '¥2,000–3,000' },
        ],
      },
      {
        type: 'warning',
        body: 'A taxi from Narita Airport costs ¥20,000–30,000 ($130–200 USD). The Narita Express train is ¥3,070 and takes 50 minutes. Always take the train from Narita.',
      },
      {
        type: 'h2',
        heading: 'Tipping in Japanese Taxis',
      },
      {
        type: 'p',
        body: 'Never tip in Japan. Tipping is considered rude or confusing. Pay the exact meter amount. Drivers will often chase you to return any extra money if you overpay.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'Can I hail a taxi on the street in Tokyo?', a: 'Yes — Tokyo taxis can be hailed anywhere. A red light on the dashboard means the taxi is available. JapanTaxi app also works for pre-booking.' },
          { q: 'Do Tokyo taxis accept credit cards?', a: 'Most Tokyo taxis now accept credit cards and IC cards (Suica, Pasmo). Cash is still the most reliable.' },
          { q: 'Is Uber available in Tokyo?', a: 'Yes, but Uber in Japan uses licensed taxi companies (not private drivers) so prices are similar to metered taxis. Uber Taxi gives you a fixed quote.' },
        ],
      },
    ],
  },

  // ── 7. Paris ───────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-paris',
    title: 'How Much Does a Taxi Cost in Paris? (2026 Rates)',
    description:
      'Paris taxi tariffs A, B, and C explained, CDG and Orly airport fixed fares, and Bolt vs G7 vs Uber comparison for 2026.',
    publishedAt: '2026-03-07',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Paris',
    country: 'France',
    citySlug: 'paris',
    countrySlug: 'france',
    content: [
      {
        type: 'intro',
        body: 'Paris taxis use a three-tariff system (A, B, C) that changes by time and destination zone. Airport trips now have regulated fixed fares. Here\'s what you need to know in 2026.',
      },
      {
        type: 'h2',
        heading: 'Paris Taxi Tariffs (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall', value: '€4.00' },
          { label: 'Tariff A (Mon–Sat 10 am–5 pm, within Paris)', value: '€1.14/km' },
          { label: 'Tariff B (Mon–Sat 5 pm–10 am, Sundays, airports)', value: '€1.57/km' },
          { label: 'Tariff C (nights, suburbs, long distances)', value: '€2.00/km' },
          { label: 'Minimum fare', value: '€8.00' },
          { label: 'Extra per item of large luggage', value: '€1.00' },
        ],
      },
      {
        type: 'h2',
        heading: 'Fixed Fares from Paris Airports',
      },
      {
        type: 'table',
        rows: [
          { label: 'CDG Airport → Right Bank (1st–8th, 10th, etc.)', value: '€56 fixed' },
          { label: 'CDG Airport → Left Bank (5th, 6th, 13th, etc.)', value: '€65 fixed' },
          { label: 'Orly Airport → Left Bank', value: '€35 fixed' },
          { label: 'Orly Airport → Right Bank', value: '€41 fixed' },
          { label: 'Beauvais Airport → Paris city', value: 'No fixed rate — negotiate' },
        ],
      },
      {
        type: 'tip',
        body: 'The CDG/Orly fixed fares are mandatory for licensed Paris taxis from the airport. If a driver quotes more, show them the regulated tariff (available on the Paris Police Prefecture website).',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from CDG to Paris city centre?', a: 'The fixed regulated fare is €56 to the Right Bank and €65 to the Left Bank. No meter — it\'s a flat rate.' },
          { q: 'Is Uber legal in Paris?', a: 'Yes — Uber VTC (private hire vehicles) are legal in Paris. Bolt is also available. Both are typically €10–20 cheaper than taxis for longer trips.' },
          { q: 'Should I tip Paris taxi drivers?', a: 'Tipping is not obligatory in France. Rounding up to the next euro or adding €1–2 for good service is customary.' },
        ],
      },
    ],
  },

  // ── 8. Bali ────────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-bali',
    title: 'How Much Does a Taxi Cost in Bali? (2026 Guide)',
    description:
      'Bali taxi prices, Ngurah Rai airport fares, Blue Bird vs Gojek vs Grab comparison, and the biggest taxi scams tourists face.',
    publishedAt: '2026-03-08',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Bali',
    country: 'Indonesia',
    citySlug: 'denpasar',
    countrySlug: 'indonesia',
    content: [
      {
        type: 'intro',
        body: 'Bali taxis range from cheap metered Blue Bird cabs to wildly overpriced tourist taxis charging 10× the fair rate. Know before you go.',
      },
      {
        type: 'h2',
        heading: 'Bali Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Blue Bird flag fall', value: 'IDR 7,500' },
          { label: 'Blue Bird per km', value: 'IDR 5,000' },
          { label: 'Minimum fare', value: 'IDR 35,000' },
          { label: 'Gojek / Grab (motorbike)', value: 'IDR 15,000–30,000 for 5 km' },
          { label: 'Gojek / Grab (car)', value: 'IDR 30,000–60,000 for 5 km' },
          { label: 'Tourist taxi (Kuta–Seminyak)', value: 'IDR 150,000–300,000 (overpriced)' },
        ],
      },
      {
        type: 'h2',
        heading: 'Airport Transfer Costs',
      },
      {
        type: 'table',
        rows: [
          { label: 'Ngurah Rai Airport → Kuta', value: 'IDR 80,000–120,000 (official prepaid)' },
          { label: 'Ngurah Rai Airport → Seminyak', value: 'IDR 130,000–180,000' },
          { label: 'Ngurah Rai Airport → Ubud', value: 'IDR 300,000–400,000' },
          { label: 'Ngurah Rai Airport → Nusa Dua', value: 'IDR 150,000–200,000' },
        ],
      },
      {
        type: 'warning',
        body: 'Gojek and Grab are banned from picking up at Ngurah Rai Airport. Use the official prepaid taxi counter inside the terminal — do not negotiate with drivers outside.',
      },
      {
        type: 'h2',
        heading: 'Biggest Bali Taxi Scams',
      },
      {
        type: 'ul',
        items: [
          'Unmetered tourist taxis charging 5–10× Blue Bird meter rates. Always ask for Blue Bird or Grab.',
          'Airport touts quoting IDR 500,000–700,000 for trips to Kuta (official price is IDR 80,000–120,000).',
          '"Meter broken" claims — Blue Bird meters always work. Take a different taxi.',
          'Pre-agreed price that changes at the destination after adding "toll fees" that don\'t exist.',
        ],
      },
      {
        type: 'faq',
        faqs: [
          { q: 'Is Grab or Gojek available in Bali?', a: 'Yes, both are widely available in Kuta, Seminyak, Canggu, and Ubud. They cannot pick up at the airport, but you can use them everywhere else.' },
          { q: 'How do I identify a Blue Bird taxi in Bali?', a: 'Blue Bird taxis are light blue, clean, and always metered. The driver wears a uniform. Avoid look-alike blue taxis from other companies.' },
          { q: 'Should I tip taxi drivers in Bali?', a: 'Rounding up is appreciated but not expected. For a Blue Bird meter fare of IDR 47,000, IDR 50,000 is fine.' },
        ],
      },
    ],
  },

  // ── 9. Rome ────────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-rome',
    title: 'How Much Does a Taxi Cost in Rome? (2026 Fixed & Metered Fares)',
    description:
      'Rome taxi rates, Fiumicino airport fixed fare, the classic tourist overcharge scams, and how to book a legal taxi in 2026.',
    publishedAt: '2026-03-09',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Rome',
    country: 'Italy',
    citySlug: 'rome',
    countrySlug: 'italy',
    content: [
      {
        type: 'intro',
        body: 'Rome taxis are metered and regulated, but tourist overcharging is common. Fixed rates from airports and train stations protect you — know them before you travel.',
      },
      {
        type: 'h2',
        heading: 'Rome Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall (daytime)', value: '€3.00' },
          { label: 'Flag fall (night 10 pm–7 am)', value: '€6.50' },
          { label: 'Flag fall (Sundays & holidays)', value: '€4.50' },
          { label: 'Per km (daytime)', value: '€1.10' },
          { label: 'Per km (night)', value: '€1.30' },
          { label: 'Extra per suitcase', value: '€1.00' },
          { label: 'Extra per passenger (over 4)', value: '€1.00' },
        ],
      },
      {
        type: 'h2',
        heading: 'Fixed Fares from Rome Airports',
      },
      {
        type: 'table',
        rows: [
          { label: 'Fiumicino (FCO) → centre of Rome (within Aurelian Walls)', value: '€50 fixed' },
          { label: 'Ciampino (CIA) → centre of Rome (within Aurelian Walls)', value: '€30 fixed' },
          { label: 'Roma Termini → Colosseum', value: '€10–15 metered' },
          { label: 'Roma Termini → Vatican', value: '€15–22 metered' },
        ],
      },
      {
        type: 'warning',
        body: 'Only licensed Rome taxis are white. Any other colour taxi is unlicensed. At Fiumicino, take the taxi queue outside arrivals — ignore anyone who approaches you inside the terminal.',
      },
      {
        type: 'h2',
        heading: 'Common Rome Taxi Scams',
      },
      {
        type: 'ul',
        items: [
          'Unlicensed "taxi" driver quotes €80–100 for a Fiumicino trip that should cost €50.',
          'Driver charges multiple "extras" (airport supplement, luggage, night rate) on top of the flat rate.',
          'Driver starts meter during the flat-rate airport trip, hoping passengers don\'t know about the fixed fare.',
          '"Credit card machine broken" then adding an unofficial cash surcharge.',
        ],
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Rome airport to city centre?', a: 'The regulated fixed fare from Fiumicino (FCO) to within the Aurelian Walls is €50. From Ciampino, it\'s €30. These are all-inclusive — no extras.' },
          { q: 'How do I book a taxi in Rome?', a: 'Call 06-0609 (city taxi booking), or use the itTaxi or FREE NOW apps. Street hailing is also common at taxi ranks (bianchi = white cars only).' },
          { q: 'Should I tip taxis in Rome?', a: 'Tipping is not expected. Rounding up to the nearest euro is considered polite.' },
        ],
      },
    ],
  },

  // ── 10. Istanbul ───────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-istanbul',
    title: 'How Much Does a Taxi Cost in Istanbul? (2026 Guide)',
    description:
      'Istanbul taxi meter rates, airport fares, the change-scam to know about, and BiTaksi vs Uber alternatives for 2026.',
    publishedAt: '2026-03-10',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Istanbul',
    country: 'Turkey',
    citySlug: 'istanbul',
    countrySlug: 'turkey',
    content: [
      {
        type: 'intro',
        body: 'Istanbul taxis are cheap by European standards but are notorious for a specific scam involving currency. Here\'s how to pay correctly and what you\'ll actually pay in 2026.',
      },
      {
        type: 'h2',
        heading: 'Istanbul Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall', value: '₺49' },
          { label: 'Per km', value: '₺32' },
          { label: 'Minimum fare', value: '₺49' },
          { label: 'Night surcharge (midnight–6 am)', value: '50% extra' },
          { label: 'Airport to city (IST)', value: '₺500–800 depending on destination' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Fares',
      },
      {
        type: 'table',
        rows: [
          { label: 'Istanbul Airport (IST) → Taksim Square', value: '₺550–750' },
          { label: 'Istanbul Airport (IST) → Sultanahmet', value: '₺600–800' },
          { label: 'Sabiha Gökçen (SAW) → Taksim', value: '₺400–600' },
          { label: 'Taksim → Sultanahmet', value: '₺80–130' },
          { label: 'Taksim → Kadıköy (via bridge)', value: '₺150–220 + bridge toll' },
        ],
      },
      {
        type: 'warning',
        body: 'The "banknote switch" scam: you hand over a ₺200 note; the driver palms it and shows you a ₺20, claiming you gave the wrong note. Always hand over one note at a time and watch your change. BiTaksi app eliminates this risk.',
      },
      {
        type: 'h2',
        heading: 'BiTaksi vs Uber in Istanbul',
      },
      {
        type: 'p',
        body: 'BiTaksi is the dominant taxi app in Istanbul — it hails official yellow taxis with a fixed upfront price and in-app payment. Uber also operates in Istanbul. Both prevent the cash scam and provide driver accountability.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Istanbul airport to the city?', a: 'From Istanbul Airport (IST), expect ₺550–800 to Taksim or Sultanahmet. From Sabiha Gökçen (SAW), ₺400–600. Metro and bus options are significantly cheaper.' },
          { q: 'Is tipping expected in Istanbul taxis?', a: 'Rounding up to the nearest ₺10 or ₺20 is common courtesy. Tipping 10% is generous but not expected.' },
          { q: 'Are Istanbul taxis metered?', a: 'All licensed yellow taxis are metered. Insist the driver starts the meter immediately. If they refuse, use BiTaksi.' },
        ],
      },
    ],
  },
  // ── 10. Phuket ─────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-phuket',
    title: 'How Much Does a Taxi Cost in Phuket? (2026 Fare Guide)',
    description:
      'Phuket taxi fares, fixed-rate zones, airport scams, and when to use Grab instead — everything you need to know before hailing a cab in 2026.',
    publishedAt: '2026-03-08',
    readingMinutes: 6,
    category: 'taxi',
    city: 'Phuket',
    country: 'Thailand',
    citySlug: 'phuket',
    countrySlug: 'thailand',
    content: [
      {
        type: 'intro',
        body: 'Phuket taxis are infamous for refusing meters and quoting inflated flat rates to tourists. Unlike Bangkok, there is no obligation for drivers to use a meter — knowing the fixed zones before you travel is your best protection.',
      },
      {
        type: 'h2',
        heading: 'How Phuket Taxi Pricing Works',
      },
      {
        type: 'p',
        body: 'Phuket operates on a fixed-zone system rather than a running meter. Prices are set per route. Drivers will quote a flat rate — knowing the typical ranges below lets you negotiate from a position of knowledge.',
      },
      {
        type: 'h2',
        heading: 'Sample Fares from Phuket Airport (HKT)',
      },
      {
        type: 'table',
        rows: [
          { label: 'HKT → Patong Beach', value: '฿600–700' },
          { label: 'HKT → Kata / Karon Beach', value: '฿700–800' },
          { label: 'HKT → Phuket Town', value: '฿400–500' },
          { label: 'HKT → Rawai / Nai Harn', value: '฿800–900' },
          { label: 'HKT → Kamala Beach', value: '฿500–600' },
          { label: 'Patong → Phuket Town', value: '฿300–400' },
        ],
      },
      {
        type: 'warning',
        body: 'Airport "limousine" services in the arrivals hall charge 30–50% more than official airport taxis. Exit the terminal and use the airport taxi desk on the ground floor.',
      },
      {
        type: 'h2',
        heading: 'Common Phuket Taxi Scams',
      },
      {
        type: 'ul',
        items: [
          'Quoting ฿1,200–1,500 for airport routes where ฿600–700 is standard.',
          'Tuk-tuk drivers offering "free rides" to a shopping area — you pay with your time and pressure to buy.',
          'Songthaew (shared truck taxi) overcharging tourists who don\'t know the local fares.',
          'Late-night price doubling — always agree the fare before getting in, especially after midnight.',
        ],
      },
      {
        type: 'h2',
        heading: 'Grab vs Taxi in Phuket',
      },
      {
        type: 'p',
        body: 'Grab operates in Phuket and is the most reliable option for transparent pricing. However, Grab availability is lower than Bangkok — during peak season, wait times can exceed 15–20 minutes. Always have the flat-rate zones in mind as a fallback.',
      },
      {
        type: 'tip',
        body: 'For beach-to-beach travel, songthaew (shared pickups) run fixed routes for ฿30–50 per person — 10x cheaper than a private taxi for the same distance.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Phuket airport to Patong?', a: 'The official fixed rate is ฿600–700. If quoted more than ฿800, negotiate or use the Grab app.' },
          { q: 'Do Phuket taxis use meters?', a: 'Most do not — Phuket largely operates on fixed-zone pricing. Always agree the fare before getting in.' },
          { q: 'What is the cheapest way to get around Phuket?', a: 'Songthaew (shared trucks) for ฿30–50 per person between beaches. Scooter rental for ฿200–300/day is cheapest for flexible travel.' },
        ],
      },
    ],
  },

  // ── 11. Barcelona ──────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-barcelona',
    title: 'How Much Does a Taxi Cost in Barcelona? (2026 Guide)',
    description:
      'Barcelona taxi meter rates, airport fares from El Prat, zone tariffs, and when Uber is cheaper — updated for 2026.',
    publishedAt: '2026-03-09',
    readingMinutes: 5,
    category: 'taxi',
    city: 'Barcelona',
    country: 'Spain',
    citySlug: 'barcelona',
    countrySlug: 'spain',
    content: [
      {
        type: 'intro',
        body: 'Barcelona\'s black-and-yellow taxis (Taxi Barcelonaand) are well-regulated and metered. Fares are set by AMB (Àrea Metropolitana de Barcelona) and posted inside every taxi. Overcharging is uncommon but knowing the rates eliminates any doubt.',
      },
      {
        type: 'h2',
        heading: 'Barcelona Taxi Meter Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall (Tariff T-1, day)', value: '€2.35' },
          { label: 'Flag fall (Tariff T-2, night/weekend)', value: '€2.95' },
          { label: 'Per km (T-1)', value: '€1.30' },
          { label: 'Per km (T-2 — night/weekend)', value: '€1.47' },
          { label: 'Airport supplement (BCN El Prat)', value: '€4.30' },
          { label: 'Large luggage supplement', value: '€1.10/bag' },
          { label: 'Night rate (21:00–08:00)', value: 'T-2 applies' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Fares from Barcelona Airport (BCN)',
      },
      {
        type: 'table',
        rows: [
          { label: 'BCN Airport → Las Ramblas / Gothic Quarter', value: '€25–35' },
          { label: 'BCN Airport → Eixample', value: '€30–40' },
          { label: 'BCN Airport → Gràcia / Sagrada Família', value: '€32–42' },
          { label: 'BCN Airport → Barceloneta Beach', value: '€25–35' },
          { label: 'City centre → Sagrada Família', value: '€8–14' },
        ],
      },
      {
        type: 'h2',
        heading: 'Uber vs Official Taxi in Barcelona',
      },
      {
        type: 'p',
        body: 'Uber operates in Barcelona (legally, as a licensed VTC service). Uber is often comparable in price to metered taxis and offers upfront pricing — useful if you prefer certainty. During surge hours, metered taxis are cheaper. For airport runs, the fixed official taxi rate is competitive.',
      },
      {
        type: 'tip',
        body: 'The AEROBUS express coach connects both airport terminals to Plaça Catalunya in 35 minutes for €6.75 — far cheaper than a taxi for solo travellers heading to central Barcelona.',
      },
      {
        type: 'h2',
        heading: 'Is Tipping Expected in Barcelona Taxis?',
      },
      {
        type: 'p',
        body: 'Tipping is not mandatory in Spain. Rounding up to the nearest euro or leaving €1–2 on longer trips is common and appreciated. For a €28 airport fare, rounding to €30 is perfectly normal.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Barcelona airport to the city?', a: 'Expect €25–42 depending on traffic and destination, plus a €4.30 airport supplement. Night and weekend rates (T-2) apply after 21:00.' },
          { q: 'Are Barcelona taxis metered?', a: 'Yes — all official taxis use AMB-regulated meters. If the meter is not running, ask the driver to start it.' },
          { q: 'Is Uber available in Barcelona?', a: 'Yes, Uber operates legally in Barcelona as a licensed VTC service. Bolt is also available and often slightly cheaper.' },
        ],
      },
    ],
  },

  // ── 12. Sydney ─────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-sydney',
    title: 'How Much Does a Taxi Cost in Sydney? (2026 Fare Guide)',
    description:
      'Sydney taxi rates, airport fares from Kingsford Smith, booking fees, and Uber vs taxi comparison for 2026.',
    publishedAt: '2026-03-10',
    readingMinutes: 5,
    category: 'taxi',
    city: 'Sydney',
    country: 'Australia',
    citySlug: 'sydney',
    countrySlug: 'australia',
    content: [
      {
        type: 'intro',
        body: 'Sydney taxis are metered and regulated by Transport for NSW. They\'re reliable but significantly more expensive than Southeast Asia — knowing the rates helps you decide when Uber is genuinely cheaper.',
      },
      {
        type: 'h2',
        heading: 'Sydney Taxi Meter Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall', value: 'A$3.60' },
          { label: 'Per km (under 10 km/h or waiting)', value: 'A$0.99/min' },
          { label: 'Per km (over 10 km/h)', value: 'A$2.19/km' },
          { label: 'Airport booking fee (from SYD)', value: 'A$4.40' },
          { label: 'Night rate (10 pm–6 am)', value: '20% surcharge' },
          { label: 'Public holiday surcharge', value: 'A$2.50' },
        ],
      },
      {
        type: 'h2',
        heading: 'Sample Fares from Sydney Airport (SYD)',
      },
      {
        type: 'table',
        rows: [
          { label: 'SYD → CBD / Circular Quay', value: 'A$45–60' },
          { label: 'SYD → Surry Hills / Darlinghurst', value: 'A$35–50' },
          { label: 'SYD → Bondi Beach', value: 'A$40–55' },
          { label: 'SYD → Manly (to ferry terminal)', value: 'A$55–75' },
          { label: 'CBD → Bondi Beach', value: 'A$25–35' },
        ],
      },
      {
        type: 'h2',
        heading: 'Uber vs Taxi in Sydney',
      },
      {
        type: 'p',
        body: 'Uber is widely available in Sydney and is often 10–20% cheaper than a metered taxi for standard routes. However, Uber surge pricing during events (New Year\'s Eve, Sydney FC matches, Vivid festival) can make taxis the better value. The Airport Link train (A$21.60 from the airport to the CBD) is the cheapest option for solo travellers.',
      },
      {
        type: 'tip',
        body: 'The Airport Link train takes 13 minutes to Central Station for A$21.60 — about a third the price of a taxi. Combine with an Opal card for free transfer to buses and ferries.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Sydney airport to the CBD?', a: 'Expect A$45–65 including the A$4.40 airport booking fee. The journey takes 20–45 minutes depending on traffic.' },
          { q: 'Are there toll roads from Sydney airport?', a: 'Yes — the Eastern Distributor tunnel adds A$8.65 (inbound) to most city routes. This is paid by the passenger on top of the meter.' },
          { q: 'Is tipping expected in Sydney taxis?', a: 'Tipping is not expected in Australia. Rounding up to the nearest dollar is common but entirely optional.' },
        ],
      },
    ],
  },

  // ── 13. Amsterdam ──────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-amsterdam',
    title: 'How Much Does a Taxi Cost in Amsterdam? (2026 Guide)',
    description:
      'Amsterdam taxi meter rates, Schiphol airport fares, and why booking a pre-agreed taxi saves money — updated for 2026.',
    publishedAt: '2026-03-11',
    readingMinutes: 5,
    category: 'taxi',
    city: 'Amsterdam',
    country: 'Netherlands',
    citySlug: 'amsterdam',
    countrySlug: 'netherlands',
    content: [
      {
        type: 'intro',
        body: 'Amsterdam taxis have a reputation for overcharging tourists — but the city has a capped tariff system to protect passengers. Knowing the maximum allowable fare from Schiphol is your first line of defence.',
      },
      {
        type: 'h2',
        heading: 'Amsterdam Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Flag fall', value: '€3.19' },
          { label: 'Per km', value: '€2.35' },
          { label: 'Per minute (waiting/slow traffic)', value: '€0.38' },
          { label: 'Fixed Schiphol → Amsterdam city', value: 'Capped at €47' },
          { label: 'Night rate (22:00–07:00)', value: 'No separate night tariff — meter applies' },
        ],
      },
      {
        type: 'h2',
        heading: 'Schiphol Airport to Amsterdam — What to Pay',
      },
      {
        type: 'p',
        body: 'The municipality caps the Schiphol to Amsterdam city centre fare at approximately €47. If a driver quotes significantly more, you can legally dispute the charge. The train (Intercity Direct, €5.50, 17 minutes to Centraal Station) is by far the cheapest option.',
      },
      {
        type: 'warning',
        body: 'Unofficial taxi touts operate aggressively outside Schiphol arrivals. Only use TCA-licenced taxis (look for the blue "Taxi" oval sign) from the official taxi rank at exit 4 of the arrivals hall.',
      },
      {
        type: 'h2',
        heading: 'Sample City Fares',
      },
      {
        type: 'table',
        rows: [
          { label: 'Centraal Station → Rijksmuseum', value: '€12–18' },
          { label: 'Centraal Station → Vondelpark', value: '€14–20' },
          { label: 'Centraal Station → De Pijp', value: '€10–16' },
          { label: 'Centraal Station → Jordaan', value: '€8–14' },
        ],
      },
      {
        type: 'tip',
        body: 'Amsterdam\'s canal ring is compact — most city-centre attractions are walkable or a short tram ride apart. A GVB day pass (€9.50) covers all trams, buses and metro and is almost always better value than a taxi for daytime sightseeing.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Schiphol to Amsterdam centre?', a: 'The capped rate is approximately €47. Expect €40–50 in practice. The Intercity train takes 17 minutes for €5.50.' },
          { q: 'Are Amsterdam taxis metered?', a: 'Yes — all licensed TCA taxis use regulated meters. If the meter is not running, ask the driver to start it or leave the vehicle.' },
          { q: 'Is tipping expected in Amsterdam taxis?', a: 'Rounding up to the nearest euro or adding 5–10% is common courtesy. It is not mandatory.' },
        ],
      },
    ],
  },

  // ── 14. Mumbai ─────────────────────────────────────────────────────────────
  {
    slug: 'how-much-does-a-taxi-cost-in-mumbai',
    title: 'How Much Does a Taxi Cost in Mumbai? (2026 Guide)',
    description:
      'Mumbai taxi and auto-rickshaw rates, airport fares, meter conversion charts, and Ola vs Uber comparison for 2026.',
    publishedAt: '2026-03-12',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Mumbai',
    country: 'India',
    citySlug: 'mumbai',
    countrySlug: 'india',
    content: [
      {
        type: 'intro',
        body: 'Mumbai has two types of metered cabs: the iconic black-and-yellow taxis (Kaali-Peeli) and air-conditioned app cabs. Both use meters — but the Kaali-Peeli meter reading must be multiplied by a tariff card rate, which confuses many visitors.',
      },
      {
        type: 'h2',
        heading: 'Mumbai Taxi Rates (2026)',
      },
      {
        type: 'table',
        rows: [
          { label: 'Kaali-Peeli flag fall (first 1.5 km)', value: '₹28' },
          { label: 'Kaali-Peeli per km after 1.5 km', value: '₹14.43' },
          { label: 'Night surcharge (midnight–5 am)', value: '25% on meter' },
          { label: 'AC Cool Cab / Meru (app cabs) flag fall', value: '₹25' },
          { label: 'AC app cabs per km', value: '₹16–18' },
          { label: 'Auto-rickshaw flag fall (suburbs only)', value: '₹21' },
          { label: 'Auto-rickshaw per km', value: '₹13.48' },
        ],
      },
      {
        type: 'warning',
        body: 'Kaali-Peeli taxi meters show an old tariff. The driver will produce a printed "tariff card" and multiply the meter reading to get the real fare. This is legal — ask to see the card before paying.',
      },
      {
        type: 'h2',
        heading: 'Sample Fares from Mumbai Airports',
      },
      {
        type: 'table',
        rows: [
          { label: 'BOM (T2) → Bandra', value: '₹400–600' },
          { label: 'BOM (T2) → Colaba / South Mumbai', value: '₹700–1,000' },
          { label: 'BOM (T2) → Juhu Beach', value: '₹200–350' },
          { label: 'BOM (T2) → Andheri', value: '₹150–250' },
          { label: 'BOM (T1 domestic) → Andheri', value: '₹100–180' },
        ],
      },
      {
        type: 'h2',
        heading: 'Ola and Uber in Mumbai',
      },
      {
        type: 'p',
        body: 'Ola and Uber are the most reliable options in Mumbai — fixed upfront pricing, no meter card confusion, and payment via app. Both are typically 10–20% more expensive than a Kaali-Peeli taxi but far more convenient. During peak hours (8–10 am, 6–9 pm), surge pricing can double the fare — switch to a metered Kaali-Peeli as a backup.',
      },
      {
        type: 'tip',
        body: 'Auto-rickshaws are not allowed in South Mumbai (below Mahim/Sion causeway) — only taxis operate there. In the suburbs, rickshaws are usually cheaper and faster for short trips.',
      },
      {
        type: 'faq',
        faqs: [
          { q: 'How much is a taxi from Mumbai airport to South Mumbai?', a: 'Approximately ₹700–1,000 by metered Kaali-Peeli or app cab. The journey takes 45–90 minutes depending on traffic.' },
          { q: 'Why does the Mumbai taxi meter show a different amount to what I pay?', a: 'Black-and-yellow Kaali-Peeli meters use a legacy tariff. The driver multiplies the meter reading by the printed tariff card. This is the legal fare — ask to see the tariff card before paying.' },
          { q: 'Is tipping expected in Mumbai taxis?', a: 'Rounding up the fare or leaving ₹10–20 extra is appreciated but not mandatory. For Ola/Uber, tips can be added in-app after the ride.' },
        ],
      },
    ],
  },
]

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug)
}

export function getAllBlogSlugs(): string[] {
  return BLOG_POSTS.map((p) => p.slug)
}
