import type { BlogPost } from './blog-posts'

export const BATCH5_BLOG_POSTS: BlogPost[] = [

  // ── Uber vs Taxi ──────────────────────────────────────────────────────────

  {
    slug: 'uber-vs-taxi-paris',
    title: 'Uber vs Taxi in Paris: VTC, G7 & Which to Choose (2026)',
    description: "A 5km Paris taxi costs €14–18 by metered cab — Uber typically runs €10–14 for the same trip. But airport fixed fares flip the equation: CDG→Right Bank is €55 by taxi or €50–80 by Uber depending on surge. Here's the full 2026 guide.",
    publishedAt: '2026-07-15',
    readingMinutes: 8,
    category: 'taxi',
    city: 'Paris',
    citySlug: 'paris',
    country: 'France',
    countrySlug: 'france',
    content: [
      { type: 'intro', body: 'Paris has two distinct categories of paid transport: traditional metered taxis (taxi conventionné) and VTC — Voitures de Transport avec Chauffeur, the French term for app-based private hire vehicles including Uber, Bolt, Marcel, and Heetch. Both are heavily regulated; neither can legally operate outside their licensing class. For tourists, the practical choice comes down to price, availability, and whether you are heading to or from the airport — where fixed rates completely change the calculation.' },
      { type: 'h2', heading: 'At a Glance: Paris Uber vs Taxi' },
      { type: 'table', rows: [
        { label: 'Metered taxi flag-fall (zones A/B)', value: '€4.00 — then €1.12/km (day) or €1.57/km (night, 19:00–07:00)' },
        { label: 'Typical 5km city trip (daytime)', value: '€14–18 by metered taxi' },
        { label: 'Typical 5km city trip (daytime)', value: '€10–14 by UberX' },
        { label: 'CDG → Right Bank Paris (fixed taxi rate)', value: '€55 flat — no negotiation, no meter' },
        { label: 'CDG → Left Bank Paris (fixed taxi rate)', value: '€62 flat' },
        { label: 'Orly → Right Bank Paris (fixed taxi rate)', value: '€35 flat' },
        { label: 'Orly → Left Bank Paris (fixed taxi rate)', value: '€41 flat' },
        { label: 'CDG → Paris by Uber (variable)', value: '€50–80+ depending on surge and vehicle class' },
        { label: 'Night surcharge window', value: '19:00–07:00, Monday–Saturday; all day Sunday and public holidays' },
      ]},
      { type: 'h2', heading: 'How Parisian Taxis Work' },
      { type: 'p', body: 'Traditional Paris taxis display a rooftop light — white when available, orange when occupied. You can hail them on the street (anywhere that is not a bus lane or no-stopping zone), pick them up at a rank, or book via the G7 or Taxis Bleus apps. The meter is mandatory for all in-city journeys. Two important things tourists misunderstand: first, taxis charge by the hour when stuck in traffic, not by distance — Paris gridlock can significantly inflate a fare. Second, luggage fees (€1 per large bag) and fourth-passenger supplements apply and are legal.' },
      { type: 'h2', heading: 'How Uber Works in Paris' },
      { type: 'p', body: 'Uber operates legally in France under the VTC licensing framework. All Uber drivers must hold a VTC licence — a professional qualification distinct from a taxi licence. UberX is the standard option; Uber Green, Uber Comfort, and Uber Black are also available. Unlike London or New York, Uber in Paris is typically cheaper than a metered taxi for city trips under 10km. The app shows upfront pricing before you confirm, which removes the meter anxiety common with traditional cabs. Surge pricing applies during high-demand periods: New Year\'s Eve, major events at Stade de France, and Friday–Saturday nights in tourist areas.' },
      { type: 'h2', heading: 'Airport Journeys: When Taxis Win' },
      { type: 'p', body: 'Paris introduced mandatory fixed-rate fares between Charles de Gaulle (CDG), Orly (ORY), and the central zones of Paris in January 2016. Every licensed taxi charges the same flat rate regardless of route taken or time of day: CDG to the Right Bank (Rive Droite: 1st–9th, 10th–12th, 18th–20th arrondissements) costs exactly €55. CDG to the Left Bank (Rive Gauche: 5th–7th, 13th–15th arrondissements) costs €62. Orly to the Right Bank is €35; to the Left Bank, €41. These rates are non-negotiable and cannot legally be increased. Uber does not have a fixed airport rate — during surges, Uber can easily exceed the taxi flat rate and is not capped.' },
      { type: 'tip', body: 'At CDG and Orly, look for the official taxi rank (queue de taxis) outside arrivals. Licensed taxis are always metered (for city destinations) or fixed-rate (for in-city Paris). Any driver approaching you inside the terminal who offers a flat rate is almost certainly an unlicensed tout — decline and walk to the official rank.' },
      { type: 'h2', heading: 'When to Choose Each' },
      { type: 'ul', items: [
        'Choose taxi for airport journeys (CDG/Orly): the fixed rate beats Uber on most days, especially with surge pricing',
        'Choose Uber for city trips under 10km where upfront pricing removes uncertainty',
        'Choose Uber or Bolt late-night when taxi availability drops but app supply stays strong',
        'Choose taxi if you prefer paying cash — many VTC drivers only accept card',
        'Use the G7 app to pre-book a taxi when you need a specific pickup time',
        'Check both the Uber app and the G7 app at the airport — whichever is cheaper wins',
      ]},
      { type: 'h2', heading: 'Tipping in Paris Taxis' },
      { type: 'p', body: 'Tipping is not expected in Paris taxis. The fare shown on the meter (or the fixed airport rate) is complete. If you wish to show appreciation, rounding up to the nearest euro or leaving €1–2 for exceptional service is sufficient and will be received warmly. Do not feel guilty for paying the exact fare shown.' },
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'How much does a taxi from CDG to Paris city centre cost?', a: 'A fixed rate applies: €55 to the Right Bank (1st–12th, 18th–20th arrondissements) and €62 to the Left Bank (5th–7th, 13th–15th arrondissements). These rates are mandatory for all licensed taxis and apply 24 hours a day.' },
        { q: 'Is Uber cheaper than a taxi in Paris?', a: 'For city trips under 10km, yes — UberX is typically €3–5 cheaper than a metered taxi. For airport journeys, taxis have fixed regulated rates that often beat Uber, especially when Uber is surging. Always compare both apps for airport runs.' },
        { q: 'Are Paris taxis safe and honest?', a: 'Licensed Paris taxis are regulated and honest. The only risk is taking an unlicensed vehicle — never accept offers from drivers inside terminal buildings. Always use the official taxi rank or book via the G7 app.' },
        { q: 'Does Uber surge in Paris?', a: 'Yes — Uber applies dynamic pricing during high demand. Major events, public holidays (especially New Year\'s Eve and Bastille Day), Friday–Saturday nights, and airport peak arrival times all trigger surge pricing. There is no legal cap on surge for VTCs in France.' },
        { q: 'What is the night rate for Paris taxis?', a: 'The night tariff (Tarif B) applies from 19:00 to 07:00 on weekdays, all day on Sundays and public holidays. The per-km rate rises from €1.12 to approximately €1.57. The fixed airport rates do not change at night.' },
        { q: 'Can I take Uber from Orly Airport?', a: 'Yes — Uber has a designated pick-up area at Orly (follow signs for VTC/ride-hail). The licensed taxi fixed rate from Orly is €35 (Right Bank) or €41 (Left Bank) — compare with the Uber price before you commit.' },
      ]},
    ],
  },

  {
    slug: 'uber-vs-taxi-berlin',
    title: 'Uber vs Taxi in Berlin: FREENOW, Bolt & Which to Choose (2026)',
    description: "A Berlin taxi costs €3.90 to start then €2.00/km — a 5km city ride runs about €14. Uber dispatches licensed taxi drivers in Germany at similar prices. Here's when the S-Bahn at €3.50 beats both.",
    publishedAt: '2026-07-15',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Berlin',
    citySlug: 'berlin',
    country: 'Germany',
    countrySlug: 'germany',
    content: [
      { type: 'intro', body: 'Berlin has one of Europe\'s more interesting ride-hailing markets. Uber operates legally but under a significant constraint: German law requires that all for-hire vehicle drivers hold a P-Schein (professional passenger transport licence), which is the same licence required for traditional taxi drivers. As a result, Uber in Berlin dispatches licensed taxi drivers rather than private drivers — making Uber and taxis essentially the same product, dispatched differently. Bolt also operates and competes on price. FREENOW (formerly MyTaxi) is the dominant app for booking traditional taxis. And the S-Bahn and U-Bahn, at €3.50 per single journey, frequently beat both.' },
      { type: 'h2', heading: 'At a Glance: Berlin Uber vs Taxi' },
      { type: 'table', rows: [
        { label: 'Taxi flag-fall (day and night)', value: '€3.90' },
        { label: 'Taxi rate per km', value: '€2.00 (day) — night surcharge applies 22:00–06:00' },
        { label: 'Typical 5km city ride (taxi)', value: '€13.90–€16' },
        { label: 'Uber / Bolt typical city ride (5km)', value: '€11–€15' },
        { label: 'BER airport to Berlin Mitte (taxi)', value: '€55–€70' },
        { label: 'BER airport to Berlin Mitte (Uber)', value: '€50–€65' },
        { label: 'S45 S-Bahn to BER (single ticket)', value: '€4.40 (zone ABC) — 45 min to Ostbahnhof' },
        { label: 'FEX Airport Express to Berlin Hbf', value: '€4.40 (zone ABC) — ~30 min' },
        { label: 'U-Bahn / S-Bahn single ticket (zones AB)', value: '€3.50' },
      ]},
      { type: 'h2', heading: 'How Berlin Taxis Work' },
      { type: 'p', body: 'Berlin taxis are cream/beige coloured and operate on a strict metered fare. The meter starts at €3.90 and runs at €2.00/km. There is a night surcharge applied between 22:00 and 06:00, and a short-distance rate (Kurzstreckentarif) of €6.00 for journeys under 2km — useful for very short trips. You can hail Berlin taxis on the street, find them at ranks (Taxistand) outside major stations, hotels, and attractions, or book via the FREENOW app. All licensed Berlin taxis accept card payment.' },
      { type: 'h2', heading: 'How Uber and Bolt Work in Berlin' },
      { type: 'p', body: 'Uber relaunched in Germany in 2021 after restructuring to comply with the P-Schein requirement. UberX in Berlin dispatches licensed drivers, often in the same type of vehicles as traditional taxis. Bolt operates similarly. The key difference from taxis: upfront pricing (you see the fare before confirming), no night surcharge in the base fare display, and slightly lower prices on average due to fleet partnerships with licensed taxi companies. However, both Uber and Bolt can apply surge pricing during high-demand periods — New Year\'s Eve, major concerts at Mercedes-Benz Arena or Waldbühne, and peak Friday–Saturday evenings.' },
      { type: 'h2', heading: 'BER Airport: The Transit-First Case' },
      { type: 'p', body: 'Berlin Brandenburg Airport (BER) is 18km south of Berlin city centre. A taxi to Berlin Mitte typically costs €55–€70. Uber runs €50–€65. Both options work, but the public transport alternative is compelling: the Airport Express (FEX) runs directly to Berlin Hauptbahnhof and Ostbahnhof in approximately 30 minutes with a standard zone ABC ticket (€4.40). For solo travellers or pairs without excessive luggage, the train is almost always the right call.' },
      { type: 'tip', body: "At BER, both the S45 (slower, stops at Schönefeld and intermediate stations) and the FEX (faster, fewer stops) use the same zone ABC ticket. If you have a Deutschlandticket (€58/month national flat-rate transit pass), both trains are included at no additional cost — making a taxi genuinely hard to justify for solo or couple travel." },
      { type: 'h2', heading: 'When to Choose Each' },
      { type: 'ul', items: [
        'Choose S-Bahn/U-Bahn for almost all city centre journeys — fast, cheap, reliable',
        'Choose taxi (via FREENOW) for late-night returns when trains run less frequently (after 24:00)',
        'Choose Bolt for upfront pricing and slight discount vs metered taxi',
        'Choose taxi over Uber when you want cash payment option',
        'Use the FEX train for BER airport unless travelling with large groups or heavy luggage',
        'Neither Uber nor taxi is necessary for most tourist destinations in central Berlin — foot or transit covers it',
      ]},
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'Is Uber available in Berlin?', a: 'Yes — Uber operates legally in Berlin and dispatches licensed P-Schein drivers. UberX is the standard option. Bolt is also available and often competitive on price.' },
        { q: 'How much is a taxi from BER airport to central Berlin?', a: 'Approximately €55–€70 depending on exact destination. The train (FEX or S45) costs €4.40 with a zone ABC ticket and takes 30–45 minutes — strongly recommended for solo travellers.' },
        { q: 'What is the Kurzstreckentarif in Berlin?', a: 'The "short distance rate" — if you hail a taxi on the street (not pre-booked) and ask for a Kurzstrecke, you pay a flat €6.00 for journeys under 2km. It is not available for pre-booked rides or rides from taxi ranks — only street hails.' },
        { q: 'Is FREENOW the same as MyTaxi?', a: 'Yes — FREENOW was rebranded from MyTaxi in 2019. It is the dominant taxi booking app in Germany and dispatches licensed Berlin taxis with upfront pricing. Many drivers prefer FREENOW bookings over street hails.' },
        { q: 'Are Berlin taxis expensive?', a: 'By European capital standards, Berlin taxis are mid-range — cheaper than Zurich or London, more expensive than Prague or Warsaw. At €2.00/km, a 10km trip costs approximately €23.90. The S-Bahn at €3.50/trip makes taxi costs stand out by comparison.' },
        { q: 'Do Berlin taxis have a night surcharge?', a: 'Yes — a surcharge applies between 22:00 and 06:00. The exact rate varies but adds approximately 15–20% to the metered fare. Plan for this when estimating late-night costs.' },
      ]},
    ],
  },

  {
    slug: 'uber-vs-taxi-tokyo',
    title: 'Uber vs Taxi in Tokyo: GO App, DiDi & Which to Choose (2026)',
    description: "Tokyo taxis are the most reliable in the world — and Uber in Japan literally dispatches the same licensed taxis. The GO app beats Uber for local coverage. Here's when ¥730 flag-fall makes sense vs the ¥170 Suica tap.",
    publishedAt: '2026-07-15',
    readingMinutes: 8,
    category: 'taxi',
    city: 'Tokyo',
    citySlug: 'tokyo',
    country: 'Japan',
    countrySlug: 'japan',
    content: [
      { type: 'intro', body: 'Tokyo taxis are among the world\'s most honest and reliable — but also among its most expensive. Drivers wear white gloves, vehicles are immaculate, and the meter runs with the precision of a Swiss watch. What surprises most visitors is that Uber in Japan does not operate as it does in most countries: Japanese law requires that all for-hire drivers hold a Type 2 (第二種免許) professional licence, which means Uber dispatches licensed taxi drivers — not independent contractors. The GO app, Japan\'s largest taxi-hailing platform, offers the same taxis with broader coverage and better integration with local payment systems. For most city routes, the train wins comprehensively on price.' },
      { type: 'h2', heading: 'At a Glance: Tokyo Uber vs Taxi' },
      { type: 'table', rows: [
        { label: 'Taxi flag-fall (standard)', value: '¥730 for first ~1km' },
        { label: 'Rate per km after flag-fall', value: '¥100 per 265m (~¥377/km)' },
        { label: 'Night surcharge (22:00–05:00)', value: '+20% on metered fare' },
        { label: 'Typical 5km city ride (daytime)', value: '¥2,000–¥2,500' },
        { label: 'Typical 5km city ride (night)', value: '¥2,400–¥3,000' },
        { label: 'Uber (dispatches licensed taxis)', value: 'Same vehicles, similar pricing, variable upfront price' },
        { label: 'GO app (Japan\'s main taxi app)', value: 'Dispatches same taxis — often more drivers available than Uber' },
        { label: 'Tokyo Metro / JR single', value: '¥170–¥320 depending on distance — 95% of journeys covered' },
        { label: 'Haneda (HND) to Shibuya by taxi', value: '¥5,000–¥7,500 (30–50 min)' },
        { label: 'Narita (NRT) to Tokyo Station by taxi', value: '¥20,000–¥30,000 — use Narita Express (¥3,070) instead' },
      ]},
      { type: 'h2', heading: 'How Uber Works in Tokyo' },
      { type: 'p', body: 'Uber launched in Japan in 2013 but quickly ran into legal barriers — Japan strictly prohibits unlicensed private hire transport (白タク行為, "shiro-taxi" operations). Uber now operates exclusively by partnering with licensed taxi companies. When you request an UberX in Tokyo, a licensed taxi driver from a partner company arrives — the same driver who might appear if you hailed from the street or used the GO app. Prices are displayed upfront in the app but may differ from the final metered fare; the app reconciles this at the end. Uber is convenient for English-speaking tourists because the app handles communication, but Japanese taxi drivers are experienced with foreign passengers and often carry translation aids.' },
      { type: 'h2', heading: 'GO App: The Better Choice for Tokyo' },
      { type: 'p', body: 'GO (formerly MOV and JapanTaxi) is the dominant taxi-hailing app in Japan, operated by GO Inc. It dispatches from a wider network of taxi companies than Uber, meaning shorter wait times in most areas — including outer Tokyo wards where Uber coverage is thin. GO supports IC card payment (Suica/Pasmo), credit cards, and PayPay. The app is available in English. DiDi (via SoftBank partnership) also operates in Tokyo and offers coupons for first-time users. For the best coverage and local driver pool, GO is the recommended app over Uber for Tokyo travel.' },
      { type: 'h2', heading: 'Airport: When NOT to Take a Taxi' },
      { type: 'p', body: 'Narita Airport (NRT) is 66km from central Tokyo — a taxi costs ¥20,000–¥30,000 and takes 60–90 minutes. This is one of the most economically poor taxi decisions a traveller can make. The Narita Express (N\'EX) costs ¥3,070 to Tokyo Station and takes 55 minutes; the Keisei Skyliner runs ¥2,570 to Ueno in 41 minutes. Both are dramatically better. Haneda (HND), being much closer at 15–25km depending on terminal, is the exception: taxis to central Tokyo run ¥5,000–¥8,500 and are a reasonable choice for groups or late arrivals when train options are limited.' },
      { type: 'tip', body: 'Japanese taxi doors open and close automatically — do not touch the passenger door handles. The driver operates the door remotely. Standing next to the rear left door is the signal that you wish to board. This is a common source of confusion for first-time visitors.' },
      { type: 'h2', heading: 'When to Choose Each' },
      { type: 'ul', items: [
        'Choose train (Metro or JR) for virtually all city centre journeys — fastest and cheapest',
        'Choose taxi late night after trains stop (~24:00–05:00) — taxis are the only option',
        'Use GO app instead of Uber — broader driver pool, better app integration with Japanese payment',
        'Choose taxi for Haneda airport arrivals (groups of 3+, heavy luggage, or night travel)',
        'Never take a taxi from Narita — the cost is prohibitive for most travellers',
        'Taxi makes sense when rain disrupts pedestrian connections and trains are overcrowded',
      ]},
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'Does Uber work in Tokyo?', a: 'Yes, but not as in most countries — Uber dispatches licensed taxi drivers from partner companies. You will be picked up by a professional taxi driver in a licensed taxi. Prices are similar to street taxis. The GO app has broader coverage and is generally preferred by locals.' },
        { q: 'Are Tokyo taxis safe?', a: 'Extremely safe. Tokyo taxis are among the world\'s most regulated and honest. Drivers hold professional licences, vehicles are inspected, and the meter is tamper-proof. There is essentially no risk of overcharging or detour scams.' },
        { q: 'How much is a Tokyo taxi from the airport?', a: 'From Narita (NRT): ¥20,000–¥30,000 — do not take a taxi, use N\'EX or Skyliner. From Haneda (HND): ¥5,000–¥8,500 to central Tokyo — reasonable for groups or late arrivals.' },
        { q: 'What is the night surcharge for Tokyo taxis?', a: 'A 20% surcharge applies between 22:00 and 05:00. A ¥2,000 daytime ride becomes ¥2,400 at night. Plan for this when estimating late-night costs.' },
        { q: 'Can I pay by IC card (Suica/Pasmo) in Tokyo taxis?', a: 'Many taxis accept IC cards — look for the sticker on the door. The GO app also supports Suica payment via the app. Credit cards are widely accepted too. Cash is always accepted.' },
        { q: 'What does it cost to get around Tokyo by train?', a: 'Most journeys within the Yamanote Line are ¥170–¥210. Cross-city journeys up to 15km run ¥200–¥320. A 24-hour Metro pass is ¥600 and covers all 9 Tokyo Metro lines — excellent value for tourist-day use.' },
      ]},
    ],
  },

  {
    slug: 'uber-vs-taxi-sydney',
    title: 'Uber vs Taxi in Sydney: 13CABS, Ola & Which to Choose (2026)',
    description: "Sydney taxis cost A$3.60 flag-fall then A$1.87/km — Uber typically runs 20–30% cheaper for the same trip. But both add a A$3.87 airport pickup fee. Here's when each makes sense in 2026.",
    publishedAt: '2026-07-15',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Sydney',
    citySlug: 'sydney',
    country: 'Australia',
    countrySlug: 'australia',
    content: [
      { type: 'intro', body: 'Sydney was one of the first Australian cities where Uber launched — illegally in 2012, and then legally following the NSW Government\'s legalisation of ride-sharing in 2016. Today the market is mature: Uber dominates ride-hailing, 13CABS and Yellow Cabs anchor the traditional taxi market, and Ola (the Indian competitor) offers frequent first-ride discounts that make it worth keeping installed. For most city routes, Uber is cheaper than a metered taxi by 20–30%. At the airport, a NSW government pickup levy applies to both — so the price gap narrows at Sydney Airport specifically.' },
      { type: 'h2', heading: 'At a Glance: Sydney Uber vs Taxi' },
      { type: 'table', rows: [
        { label: 'Taxi flag-fall', value: 'A$3.60' },
        { label: 'Rate per km', value: 'A$1.87/km' },
        { label: 'Booking fee (phone/app)', value: 'A$2.00' },
        { label: 'Typical 5km city ride (taxi)', value: 'A$13–A$18' },
        { label: 'Typical 5km city ride (Uber)', value: 'A$10–A$14' },
        { label: 'Sydney Airport pickup surcharge (taxi)', value: 'A$3.87 (airport network fee) + A$4.11 (NSW levy) = A$7.98 total' },
        { label: 'Sydney Airport pickup surcharge (Uber)', value: 'A$4.11 (NSW levy) — applied to all rideshare pickups at SYD' },
        { label: 'Sydney Airport (SYD) to CBD by taxi', value: 'A$45–A$65' },
        { label: 'Sydney Airport (SYD) to CBD by Uber', value: 'A$35–A$55' },
        { label: 'Airport Link train (SYD to Central)', value: 'A$20.50 off-peak — 13 minutes' },
      ]},
      { type: 'h2', heading: 'How Sydney Taxis Work' },
      { type: 'p', body: '13CABS (the largest network), Yellow Cabs, and Premier Cabs are Sydney\'s main taxi operators. All use metered fares with the NSW Government-set rate structure. You can hail on the street, find taxis at ranks outside major hotels, Circular Quay, Central Station, and the airport, or book via the 13CABS or Cabcharge apps. Most Sydney taxis accept card payment via Cabcharge or Eftpos. A small credit card surcharge may apply. Tipping is not expected or common in Australia — pay the metered amount.' },
      { type: 'h2', heading: 'Uber and Ola in Sydney' },
      { type: 'p', body: 'UberX is the standard option and is almost always available within 3–5 minutes in inner Sydney, the Eastern Suburbs, North Shore, and Parramatta. Uber Pool is not available in Sydney. Ola launched in Australia in 2018 and competes primarily on price — it regularly offers 20–30% discounts for new users and promotional fare cuts. If you have Ola installed alongside Uber, checking both takes 10 seconds and can save A$5–15 on longer rides. Didi also launched in Sydney but has smaller driver supply than Uber or Ola.' },
      { type: 'h2', heading: 'Sydney Airport: The Levy and the Train' },
      { type: 'p', body: 'Sydney Airport applies a NSW Government levy to all private hire vehicles and taxis departing the terminal precinct. For taxis, this is A$7.98 total (A$3.87 network fee + A$4.11 NSW levy). For Uber and rideshare, it is A$4.11. This narrows the gap between taxi and Uber at the airport specifically. The Airport Link train from the domestic or international terminal to Central Station takes 13 minutes and costs A$20.50 (off-peak) — significantly cheaper than either taxi or Uber for solo or pair travel, but less practical for large groups or heavy luggage.' },
      { type: 'tip', body: 'Sydney Airport has a dedicated rideshare pickup zone in the T1 International car park (Level 0, P3). Follow signs for "Rideshare" once you clear customs. Taxis use the designated rank outside each terminal. Both operate 24 hours.' },
      { type: 'h2', heading: 'When to Choose Each' },
      { type: 'ul', items: [
        'Choose Uber or Ola for most city trips — typically 20–30% cheaper than metered taxi',
        'Check Ola first if you\'re price-sensitive — discount codes and lower base rates are common',
        'Choose taxi if you prefer cash payment or are in an area with poor app coverage',
        'Use the Airport Link train from SYD for solo/pair travel — much cheaper than any road option',
        'Choose taxi at the airport if you have 3+ passengers and heavy luggage (train becomes less practical)',
        'Expect surge pricing on Uber during Sydney events (NYE fireworks, New Year\'s Day, major concerts at Accor Stadium)',
      ]},
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'Is Uber cheaper than a taxi in Sydney?', a: 'Yes, typically 20–30% cheaper for equivalent city trips. At the airport, the gap narrows because a NSW Government levy applies to rideshare too (A$4.11). Over a 15km journey, Uber saves roughly A$10–15 compared to a metered taxi.' },
        { q: 'How much is a taxi from Sydney Airport to the CBD?', a: 'Approximately A$45–A$65 for the 10–15km journey, including the airport surcharges. By Uber the same trip costs A$35–A$55. The Airport Link train is A$20.50 and takes 13 minutes — the best value for solo travellers.' },
        { q: 'Should I tip taxi drivers in Sydney?', a: 'No — tipping is not customary in Australia. Taxi drivers and Uber drivers are paid living wages under Australian award rates. Rounding up a dollar or two is a pleasant gesture but is not expected and should not be felt as an obligation.' },
        { q: 'What is Ola and is it available in Sydney?', a: 'Ola is an Indian ride-hailing company that operates in Sydney, Melbourne, Perth, and other Australian cities. It typically offers lower base fares and frequent promotional discounts. Download it alongside Uber and compare — you may find significantly cheaper rides.' },
        { q: 'Do Sydney taxis accept credit cards?', a: 'Yes — all Sydney taxis accept credit and debit cards via Cabcharge terminals. A surcharge of approximately 5–10% applies for card payments in some taxis. Uber and Ola charge your saved card automatically with no surcharge.' },
        { q: 'Can I hail a taxi in Sydney on the street?', a: 'Yes — taxi-hailing on the street is legal in Sydney anywhere taxis are permitted to stop. A free cab shows a lit "TAXI" sign on the roof. For late-night availability, 13CABS has a reliable dispatch service. Uber is usually faster to arrive during off-peak hours.' },
      ]},
    ],
  },

  // ── Airport Routes ─────────────────────────────────────────────────────────

  {
    slug: 'taxi-ber-to-berlin',
    title: 'Taxi from Berlin Airport (BER) to Berlin City: Cost & Guide (2026)',
    description: 'A taxi from Berlin Brandenburg Airport to Berlin Mitte costs €55–€70 — but the FEX Airport Express costs €4.40 and takes 30 minutes. Here\'s when the taxi is worth it and when the train wins.',
    publishedAt: '2026-07-15',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Berlin',
    citySlug: 'berlin',
    country: 'Germany',
    countrySlug: 'germany',
    content: [
      { type: 'intro', body: 'Berlin Brandenburg Airport (Flughafen Berlin Brandenburg, BER) opened in October 2020 after a notorious nine-year delay that became a global symbol of infrastructure failure. Located 18km south of Berlin city centre in Schönefeld, Brandenburg, BER now handles all of Berlin\'s commercial flights after the closure of Tegel (TXL). Taxis from BER to central Berlin are metered, reliable, and straightforward — but at €55–€70 for a solo traveller, they are a difficult choice to justify against the FEX Airport Express, which runs every 30 minutes for €4.40.' },
      { type: 'h2', heading: 'BER to Berlin: Key Numbers' },
      { type: 'table', rows: [
        { label: 'Taxi flag-fall (all hours)', value: '€3.90' },
        { label: 'Rate per km (day)', value: '€2.00' },
        { label: 'Night surcharge (22:00–06:00)', value: 'Applies — adds ~15–20% to the metered fare' },
        { label: 'BER to Berlin Mitte (taxi, ~20km)', value: '€55–€70 (daytime)' },
        { label: 'BER to Berlin Mitte (Uber/Bolt)', value: '€50–€65 (variable, check app)' },
        { label: 'FEX Airport Express (to Berlin Hbf)', value: '€4.40 (zone ABC ticket) — ~30 minutes, every 30 min' },
        { label: 'S45 S-Bahn (to Berlin Ringbahn)', value: '€4.40 (zone ABC ticket) — ~45 min, slower route' },
        { label: 'Deutschlandticket holders', value: 'Both trains free — most cost-effective option' },
      ]},
      { type: 'h2', heading: 'Taxi Fares to Berlin Districts' },
      { type: 'table', rows: [
        { label: 'BER → Berlin Mitte (city centre)', value: '€55–€70 (~20km)' },
        { label: 'BER → Friedrichshain / Kreuzberg', value: '€50–€65 (~18km)' },
        { label: 'BER → Prenzlauer Berg', value: '€60–€75 (~24km)' },
        { label: 'BER → Charlottenburg (western Berlin)', value: '€70–€90 (~30km)' },
        { label: 'BER → Schönefeld area (close to airport)', value: '€15–€25 — short trip, taxi reasonable' },
        { label: 'BER → Potsdam', value: '€40–€55 (~25km)' },
      ]},
      { type: 'h2', heading: 'How to Get a Taxi at BER' },
      { type: 'p', body: 'Taxis at BER queue at the designated taxi rank on the ground floor of Terminal 1, directly outside the arrivals hall. Follow "Taxi" signs from the baggage reclaim area. The rank is staffed 24 hours and operates as a queue — no need to negotiate or pre-book for immediate travel. All licensed Berlin taxis are metered and cream/beige coloured. The meter starts the moment you depart — there is no airport surcharge added separately, and the fare displayed is the fare you pay.' },
      { type: 'h2', heading: 'The FEX Airport Express — Almost Always the Right Call' },
      { type: 'p', body: 'The Airport Express (FEX) is a regional train (RE7) that runs from BER Terminal 1 to Berlin Hauptbahnhof (central station) in approximately 30 minutes, continuing to Berlin Ostbahnhof. Trains depart every 30 minutes, from approximately 04:40 until after midnight. A zone ABC single ticket costs €4.40 — for holders of the Deutschlandticket (€58/month for unlimited German public transport), the train is free. The S45 S-Bahn is a slower alternative (~45 minutes) but uses the same ticket.' },
      { type: 'tip', body: 'BER terminals also served by the city S-Bahn (Flughafen BER Terminal 1-2 station and Flughafen BER Terminal 5 station — the latter for the old Schönefeld Terminal). The zone ABC ticket covers both. Buy at the BVG ticket machines on the platform level — contactless card payment accepted.' },
      { type: 'h2', heading: 'When the Taxi is Worth It from BER' },
      { type: 'ul', items: [
        'Three or more passengers splitting the fare — at €65/3 = ~€22 each vs €4.40 each by train, the taxi becomes competitive for groups',
        'Heavy luggage or oversized bags that make train travel impractical',
        'Arrivals after midnight when train frequency drops significantly',
        'Destinations in Schönefeld / Köpenick that are on the wrong side for trains',
        'Business travel where time and convenience outweigh cost',
      ]},
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'How much does a taxi from Berlin Airport (BER) to the city centre cost?', a: 'Approximately €55–€70 to Berlin Mitte for the ~20km journey. Fares vary with exact destination — western districts like Charlottenburg cost more at €70–€90. Night fares (22:00–06:00) are slightly higher.' },
        { q: 'How long does the taxi from BER take?', a: 'Approximately 30–50 minutes depending on traffic and destination. The A113 motorway connects BER directly to the city ring road. Traffic can extend this during peak hours (7–9am, 5–7pm weekdays).' },
        { q: 'Is Uber available at Berlin Airport?', a: 'Yes — Uber and Bolt both operate from BER. Use the designated app pickup zones signposted at the terminal. Uber dispatches licensed P-Schein drivers in Germany, so prices are similar to metered taxis but displayed upfront.' },
        { q: 'Does the FEX train go to Berlin Hauptbahnhof?', a: 'Yes — the FEX (Airport Express, RE7) runs from BER Terminal 1 to Berlin Hauptbahnhof in ~30 minutes. It also stops at Südkreuz and continues to Ostbahnhof. A zone ABC ticket (€4.40) covers the full journey.' },
        { q: 'What happened to Tegel Airport?', a: 'Tegel Airport (TXL) closed permanently on 8 November 2020, following the opening of BER. All Berlin flights now use BER. The former Tegel site is being redeveloped as an innovation campus.' },
        { q: 'Can I pre-book a taxi from BER?', a: 'Yes — FREENOW (the main German taxi booking app) allows advance booking from BER. You can schedule for a specific arrival time. Pre-booked taxis meet you at the arrivals hall.' },
      ]},
    ],
  },

  {
    slug: 'taxi-muc-to-munich',
    title: 'Taxi from Munich Airport (MUC) to Munich City: Cost & Guide (2026)',
    description: 'A taxi from Munich Airport to the city centre costs €65–€85 for a 40km journey. The S-Bahn S1/S8 costs €13.60 and takes 40 minutes. Here\'s when each makes sense.',
    publishedAt: '2026-07-15',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Munich',
    citySlug: 'munich',
    country: 'Germany',
    countrySlug: 'germany',
    content: [
      { type: 'intro', body: 'Munich Airport Franz Josef Strauss (MUC) is Germany\'s second-busiest airport and one of Europe\'s most efficient. Located 40km northeast of Munich city centre in the municipality of Hallbergmoos/Freising, MUC is significantly farther from the city than most European capital airports. A metered taxi to central Munich costs €65–€85, making the S-Bahn — at €13.60 — the default choice for most individual travellers. For groups of three or more, or for destinations off the S-Bahn route, the taxi proposition improves significantly.' },
      { type: 'h2', heading: 'MUC to Munich: Key Numbers' },
      { type: 'table', rows: [
        { label: 'Taxi flag-fall', value: '€4.50' },
        { label: 'Rate per km', value: '€2.00 (day), with night surcharge 21:00–06:00' },
        { label: 'MUC to Munich Hauptbahnhof (taxi)', value: '€65–€80 (~40km, daytime)' },
        { label: 'MUC to Munich Marienplatz area', value: '€70–€85' },
        { label: 'MUC to Schwabing / Maxvorstadt', value: '€65–€80' },
        { label: 'MUC → city (Uber / Bolt)', value: '€60–€75 (variable)' },
        { label: 'S1/S8 S-Bahn to Munich Hbf', value: '€13.60 (zone XXL ticket) — 40 minutes' },
        { label: 'S-Bahn with Bayern-Ticket', value: 'Free (Bayern-Ticket covers airport zone)' },
        { label: 'Lufthansa Express Bus to Munich Hbf', value: '€10.80 — 40 min, departs every 20 min' },
      ]},
      { type: 'h2', heading: 'Getting a Taxi at MUC' },
      { type: 'p', body: 'Taxis at MUC are available 24 hours from the ground transportation level below both Terminal 1 and Terminal 2. Follow "Taxi" signs from baggage reclaim. The taxi rank operates on a queue system — no pre-booking required for immediate travel. All Munich taxis are metered cream/beige vehicles. For pre-booked taxis, the Taxi München app (isarfunk) allows advance reservations with a specific vehicle meeting you at arrivals. Uber and Bolt also serve MUC from designated rideshare pickup zones.' },
      { type: 'h2', heading: 'S-Bahn: The Economical Choice' },
      { type: 'p', body: 'Two S-Bahn lines serve Munich Airport: S1 (via the north route through Freising) and S8 (via the south route through Daglfing). Both terminate at Munich Hauptbahnhof and take approximately 40 minutes. The fare is €13.60 (a zone XXL single ticket covers the airport zone). Trains run every 20 minutes during the day, every 40 minutes at night. If you hold a Bayern-Ticket (€29 for the first person, €8 each additional, valid all day on all Bavarian regional trains and S-Bahn), the airport journey is included at no extra cost.' },
      { type: 'h2', heading: 'Lufthansa Express Bus: A Mid-Way Option' },
      { type: 'p', body: 'The Lufthansa Express Bus (previously marketed as the Lufthansa Airport Bus) runs between MUC and Munich Hauptbahnhof for €10.80 one-way, departing every 20 minutes. Despite the name, it accepts all passengers — not just Lufthansa travellers. The journey takes approximately 40–45 minutes. This is a comfortable, reliable alternative for those with larger luggage who find the S-Bahn less convenient. Tickets are available at the bus stop or via the Flixbus app.' },
      { type: 'tip', body: 'The Munich Airport S-Bahn runs 24 hours a day (though with reduced frequency between midnight and 04:00). Night travellers should check the MVV timetable for the S1/S8 schedule. Night taxis are subject to the 21:00–06:00 surcharge.' },
      { type: 'h2', heading: 'When the Taxi Makes Sense from MUC' },
      { type: 'ul', items: [
        'Three or more passengers: at €75/3 = €25 each vs €13.60 by S-Bahn — taxi becomes competitive',
        'Destinations in northern Munich or the Freising area that are close to the airport',
        'Oversized or heavy luggage that makes train travel difficult',
        'Night arrivals between 00:00 and 04:00 when S-Bahn runs less frequently',
        'Business travel where client pickup requires a specific terminal meeting point',
        'Trade fair periods (Oktoberfest, IAA, bauma) when S-Bahn is extremely crowded',
      ]},
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'How much is a taxi from Munich Airport to the city centre?', a: 'Approximately €65–€80 for the ~40km journey to Munich Hauptbahnhof, €70–€85 to Marienplatz and the old town. Night fares (21:00–06:00) add a surcharge of approximately 15–20%.' },
        { q: 'How long does the taxi from MUC take?', a: 'Approximately 40–60 minutes under normal traffic. The A9 motorway connects MUC to central Munich, but congestion during peak hours (7–9am and 5–8pm weekdays) can extend this to 75–90 minutes. The S-Bahn is unaffected by road traffic.' },
        { q: 'Which S-Bahn goes to Munich Airport?', a: 'Both S1 and S8 serve Munich Airport (S-Bahn Flughafen München). S8 is generally faster (via Ostbahnhof and Hbf). The €13.60 zone XXL ticket covers the entire journey from airport to city.' },
        { q: 'Is Uber available at Munich Airport?', a: 'Yes — Uber and Bolt operate from MUC. Follow signs for the rideshare pickup area. Prices are typically €60–€75 to the city centre, marginally cheaper than a metered taxi but still significantly more than the S-Bahn.' },
        { q: 'Does the Bayern-Ticket cover the airport S-Bahn?', a: 'Yes — the Bayern-Ticket covers all MVV zones including the airport zone (zone XXL). At €29 for one person (valid all day from 09:00 on weekdays, from midnight on weekends), it makes sense if you plan to use S-Bahn elsewhere during the day.' },
        { q: 'Are there fixed-price taxis from Munich Airport?', a: 'Munich taxis are metered — there are no legally mandated fixed rates for the airport route (unlike Paris). Some taxi companies offer pre-agreed flat rates via advance booking apps, but these are not regulated. Expect approximately €65–€80 metered.' },
      ]},
    ],
  },

  {
    slug: 'taxi-mad-to-madrid',
    title: 'Taxi from Madrid Airport (MAD) to Madrid City: Cost & Guide (2026)',
    description: "A taxi from Madrid Barajas to the city centre costs a flat €30 — regulated by Madrid City Council since 2012. Metro Line 8 costs €4.50. Here's when the taxi at €30 is genuinely the right call.",
    publishedAt: '2026-07-15',
    readingMinutes: 7,
    category: 'taxi',
    city: 'Madrid',
    citySlug: 'madrid',
    country: 'Spain',
    countrySlug: 'spain',
    content: [
      { type: 'intro', body: 'Madrid Barajas airport (Adolfo Suárez Madrid–Barajas, MAD) has an unusually traveller-friendly taxi situation: since 2012, Madrid City Council has mandated a flat rate of €30 for all taxi journeys between any point in the Madrid Municipal Area (within the M-30 ring road) and the airport. This rate applies in both directions, at any hour of the day or night, and cannot be increased by the driver. The flat rate makes Madrid one of the fairest airport taxi cities in Europe — and at €30, taxis are genuinely competitive with the Metro for groups of two or more.' },
      { type: 'h2', heading: 'MAD to Madrid: Key Numbers' },
      { type: 'table', rows: [
        { label: 'Taxi (flat rate, any terminal → M-30 zone)', value: '€30 — fixed by law, no meter for this route' },
        { label: 'Taxi (destinations outside M-30)', value: 'Metered — flag-fall €2.40 + €1.17/km (day) or €1.40/km (night)' },
        { label: 'Uber / Cabify to city centre', value: '€20–€35 (variable — can beat taxi or surge above it)' },
        { label: 'Metro Line 8 (T1/T2/T3 to Nuevos Ministerios)', value: '~€4.50 — regular fare + €3 airport supplement, 25 minutes' },
        { label: 'Metro T4 (Barajas station to city)', value: 'Regular Metro fare + airport supplement ~€4.50 — 40 min with change' },
        { label: 'RENFE Cercanías C1 (T4 to Sol)', value: 'Under €4 — slowest option (~45 min), no airport supplement' },
        { label: 'Express bus 203 (airport to Avenida América)', value: '€5 — 24 hours, runs every 15–35 minutes' },
      ]},
      { type: 'h2', heading: 'The €30 Flat Rate — What You Need to Know' },
      { type: 'p', body: 'The €30 flat rate applies specifically to journeys between Madrid Airport (all terminals) and any address within the Madrid Municipal Zone (essentially within or near the M-30 orbital motorway — this covers the entire tourist and business core of the city: Gran Vía, Sol, Retiro, Malasaña, Lavapiés, Chueca, Salamanca district, and most hotels). The driver is legally required to use the flat rate for this journey. If the driver proposes a metered fare or a different amount for an in-zone destination, you are entitled to insist on the €30 rate. The rate applies in both directions: airport to city AND city to airport.' },
      { type: 'h2', heading: 'Which Terminal Are You Arriving At?' },
      { type: 'p', body: 'MAD has four terminals. T1, T2, and T3 are clustered together and share a Metro station (Aeropuerto T1-T2-T3, Line 8). T4 is a separate terminal approximately 5km east, served by its own Metro station (Aeropuerto T4, also Line 8) and Cercanías C1 train. Most intercontinental and Iberia mainline flights use T4; most European and low-cost carriers use T1–T3. Check your terminal before planning transport — both are on Metro Line 8 and served by the flat-rate taxis.' },
      { type: 'h2', heading: 'Uber and Cabify from Madrid Airport' },
      { type: 'p', body: 'Cabify is the dominant app-based private hire service in Spain (Spain\'s local equivalent of Uber). Uber also operates in Madrid. Both are VTC (Vehículo de Transporte con Conductor) services. For the airport route, check the quoted price before confirming: during off-peak hours, Cabify or Uber can come in at €20–€25, beating the €30 taxi flat rate. During peak demand or airport surge, prices can reach €35–€50. The €30 taxi rate is fixed and surge-proof — on busy travel days, the taxi may genuinely be the smarter financial choice.' },
      { type: 'tip', body: "Madrid's Metro Line 8 (the pink line) connects all airport terminals to Nuevos Ministerios in central Madrid. From there, you can connect to Lines 6, 10, and others for most tourist destinations. The airport supplement (€3) is added to the regular zone fare — bringing the total to approximately €4.50. The Metro runs from approximately 06:00 to 01:30 daily." },
      { type: 'h2', heading: 'When to Choose the €30 Taxi' },
      { type: 'ul', items: [
        'Two or more people travelling together — split cost of €30 equals €15 each vs ~€4.50 each by Metro',
        'Night arrivals after 01:30 when the Metro is closed',
        'Heavy luggage or large groups where Metro escalators and trains are impractical',
        'Destinations outside the Metro line (€30 covers the whole M-30 zone including hotels off-Metro)',
        'When Uber/Cabify are surging above €30 — the taxi flat rate cannot be exceeded',
        'Businesses or travellers who need a receipt (Madrid taxis provide printed receipts)',
      ]},
      { type: 'h2', heading: 'Frequently Asked Questions' },
      { type: 'faq', faqs: [
        { q: 'How much is a taxi from Madrid Airport to the city centre?', a: 'A fixed rate of €30 applies for all journeys between Madrid Barajas Airport (any terminal) and any address within the Madrid Municipal Area (the M-30 zone). This is mandated by Madrid City Council and applies at all hours. No supplements, no meter for this route.' },
        { q: 'What if my destination is outside the M-30 zone?', a: 'The €30 flat rate only applies within the M-30 zone. For destinations outside (e.g., Getafe, Alcorcón, Torrejón), the taxi uses the regular metered rate: €2.40 flag-fall + €1.17/km (day) or €1.40/km (night). Ask the driver to confirm before setting off.' },
        { q: 'Can I take the Metro from all terminals?', a: 'Yes — Metro Line 8 serves T1-T2-T3 (combined station) and T4 (separate station). The airport supplement is €3 on top of the regular zone fare, making the total approximately €4.50 to central stations like Nuevos Ministerios, with connections to the rest of the network.' },
        { q: 'Is Cabify or Uber cheaper than the flat-rate taxi?', a: 'Sometimes — during off-peak hours, Cabify can quote €20–€25 for the airport run, undercutting the €30 taxi. During surge, Cabify and Uber can easily exceed €35–€50. Check the app at arrival: if the quote is under €28, Cabify/Uber wins. If it\'s above €28, take the taxi.' },
        { q: 'Do Madrid taxis have an airport surcharge on top of the €30?', a: 'No — the €30 is the complete fare for all destinations within the M-30 zone. No luggage surcharge, no night supplement, no airport addition. The driver cannot legally charge more for this route.' },
        { q: 'Does the express bus go to the city centre?', a: 'Bus 203 (Exprés Aeropuerto) runs 24 hours between all airport terminals and Avenida de América metro interchange, from where you can connect to Lines 4, 6, 7, and 9. Fare is €5. For destinations near Avenida de América (Salamanca district, Recoletos), it\'s a convenient option.' },
      ]},
    ],
  },

]
