import type { BlogPost } from './blog-posts'

export const BATCH3C_BLOG_POSTS: BlogPost[] = [
  {
    slug: 'best-time-to-visit-marrakech',
    title: 'Best Time to Visit Marrakech: Heat, Crowds & Hidden Season (2025)',
    description: 'The best time to visit Marrakech is March to May or October to November — comfortable at 18–28°C before summer heat pushes 45°C in the Medina.',
    publishedAt: '2025-06-01',
    readingMinutes: 4,
    category: 'travel',
    city: 'Marrakech',
    country: 'Morocco',
    content: [
      { type: 'intro', body: 'Marrakech is best visited in spring (March–May, 18–28°C) or autumn (October–November, 18–26°C) — comfortable for exploring the Medina souks, day trips to the Atlas Mountains, and evenings on Djemaa el-Fna square. June to August sees temperatures of 38–45°C, making afternoon sightseeing genuinely difficult.' },
      { type: 'h2', heading: 'Marrakech Month by Month' },
      { type: 'table', rows: [
        { label: 'Mar–May (Spring)', value: '18–28°C, roses blooming in the Dadès Valley (May), ideal hiking weather, shoulder prices' },
        { label: 'Jun–Aug (Summer)', value: '35–45°C, intense heat midday, fewer tourists, cheapest riads, locals retreat indoors 12–4pm' },
        { label: 'Sep–Nov (Autumn)', value: '18–30°C, Marrakech Film Festival (Nov/Dec), harvest season in Ourika Valley' },
        { label: 'Dec–Feb (Winter)', value: '10–20°C days, 5°C nights, occasional rain, snow visible on Atlas peaks, Christmas period busy' },
      ]},
      { type: 'h2', heading: 'Practical Tips for Each Season' },
      { type: 'ul', items: [
        '**Ramadan (dates vary)**: Many local restaurants close during daylight hours; iftar (breaking fast at sunset) is a spectacular community event — join locals at Djemaa el-Fna for a memorable meal',
        '**Summer survival**: Riad swimming pools, hammam sessions, and pre-dawn souks (open from 7am before heat peaks) make summer manageable for acclimatised visitors',
        '**Atlas day trips**: Snow on Jebel Toubkal (4,167m) can persist until May — bring layers for any mountain excursion regardless of Marrakech temperatures',
      ]},
      { type: 'tip', body: 'The Marrakech Menara Airport is only 4km from the Medina — a taxi costs MAD 70–100 (~€6.50–9). Grand taxis (shared Mercedes) to Djemaa el-Fna run MAD 20–30 per seat. In spring and autumn, book your riad at least 3 weeks ahead — the best riads in the Medina sell out fast.' },
      { type: 'faq', faqs: [
        { q: 'Is Marrakech worth visiting in winter?', a: 'Yes — December to February offers mild days (15–20°C), minimal crowds outside the Christmas–New Year spike, and some of the lowest riad prices of the year. The Atlas Mountains dusted with snow visible from the city\'s rooftop terraces is genuinely beautiful.' },
        { q: 'How many days do you need in Marrakech?', a: 'Three days covers the Medina essentials: Djemaa el-Fna square, the souks, Bahia Palace, Saadian Tombs, and Jardin Majorelle. Five days adds a day trip to Ourika Valley or the Atlas, plus time to get properly lost in the Medina lanes.' },
      ]},
    ],
  },
  {
    slug: 'uber-vs-taxi-rome',
    title: 'Uber vs Taxi in Rome: Which Is Better in 2025?',
    description: 'In Rome, official white taxis are metered and honest — but Uber also operates (as UberBlack, not UberX). Here\'s the full comparison for 2025.',
    publishedAt: '2025-06-04',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Rome',
    country: 'Italy',
    content: [
      { type: 'intro', body: 'Rome\'s official white taxis are metered, licensed, and generally honest — the main risk is boarding an unlicensed "abusive" taxi outside airports and train stations. Uber operates in Rome but only as UberBlack (licensed private hire vehicles), which is typically 40–60% more expensive than a metered white cab.' },
      { type: 'h2', heading: 'Rome Taxi Options Compared (2025)' },
      { type: 'table', rows: [
        { label: 'Official white taxi (metered)', value: '€3.50 flag fall (daytime), €6.50 (nights/holidays), €1.10/km; honest and regulated' },
        { label: 'Uber Black / Van', value: 'Set price upfront; typically 40–60% above metered taxi; professional cars; no cheaper option' },
        { label: 'itTaxi / eCab (apps)', value: 'Books a licensed white taxi via app — same metered fare, safer than street-hailing near tourist sites' },
        { label: 'Fixed fares (from airports)', value: 'FCO (Fiumicino) to city centre ring road: €50 flat; Ciampino (CIA): €31 flat' },
      ]},
      { type: 'h2', heading: 'Typical Rome Taxi Fares (2025)' },
      { type: 'ul', items: [
        'Termini Station → Colosseum: ~€10–14 (2.5km, 10–15 min)',
        'Termini → Vatican (St Peter\'s Square): ~€12–17 (4km, 15–20 min)',
        'Colosseum → Trastevere: ~€8–12 (2km, 10 min)',
        'Fiumicino Airport (FCO) → city centre: €50 flat rate (fixed by Rome municipality — always confirm this before entering)',
        'Night surcharge (22:00–06:00): flag fall €6.50 vs €3.50 daytime — significant difference on short journeys',
      ]},
      { type: 'warning', body: 'The most common Rome taxi scam: touts at Fiumicino airport offering "official taxi" but charging €80–120 for what should be a €50 fixed-rate trip. Only board white taxis with a taxi licence plate (starting with TAXI or the city code). Book via itTaxi app or use the official taxi rank — never accept offers from people approaching you in arrivals.' },
      { type: 'faq', faqs: [
        { q: 'Is Uber available in Rome as UberX?', a: 'No — UberX (private drivers) is not licensed in Italy due to taxi industry regulations. Uber in Rome means UberBlack (licensed hire cars with professional drivers), which costs significantly more than a standard metered white taxi. For budget travel, the official white cab or itTaxi app is always cheaper.' },
        { q: 'Do you tip taxi drivers in Rome?', a: 'Not required — Italians round up to the nearest euro or add 50 cents on short trips. Tipping 10% is generous and appreciated but not expected. The fixed airport fare already accounts for full service.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-amsterdam',
    title: 'Getting Around Amsterdam: Tram, Metro, Canal Bus & Bike Guide (2025)',
    description: 'Amsterdam\'s tram network covers the whole inner city for €2.00/trip. Cycling is faster for most journeys. Here\'s the complete 2025 transport guide.',
    publishedAt: '2025-06-07',
    readingMinutes: 5,
    category: 'travel',
    city: 'Amsterdam',
    country: 'Netherlands',
    content: [
      { type: 'intro', body: 'Amsterdam is small enough to walk across in 40 minutes — but the tram network (15 lines, 80 stops) and city bikes cover the entire metro area cheaply and efficiently. An OV-chipkaart handles trams, buses, metros, and national trains on one card.' },
      { type: 'h2', heading: 'Amsterdam Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'Tram (GVB)', value: '€2.00/trip with OV-chipkaart or contactless; 1-hour transfer included; day pass €8.50' },
        { label: 'Metro (4 lines)', value: '€2.00/trip; North/South line (M52) connects Central Station to De Pijp and Amstelveen' },
        { label: 'Bus', value: '€2.00/trip; same OV-chipkaart; night buses (N-lines) run when trams stop' },
        { label: 'Canal Bus / Hop-on ferry', value: '€26/day (tourist hop-on); free IJ ferries behind Central Station are better value' },
        { label: 'MacBike / Donkey Republic (rental bike)', value: '€15–18/day; fastest option for distances 1–5km; follow cycle lane rules strictly' },
        { label: 'Schiphol Airport → Central Station', value: 'Train: €4.50, 17 min; Taxi: €40–60; no tram connection' },
      ]},
      { type: 'h2', heading: 'Cycling in Amsterdam: What Tourists Must Know' },
      { type: 'ul', items: [
        'Red/pink lanes are cycle lanes — pedestrians walking in them will be rung at firmly and without apology',
        'Always lock your bike with both the frame lock AND a chain lock to a fixed object; Amsterdam has the world\'s highest bike theft rate',
        'Cycle on the right, signal with your hand, and do not use your phone while riding — fines apply',
        'Tram tracks are a genuine hazard — cross them at right angles to avoid your wheel slipping into the groove',
        'The free GVB ferries across the IJ (behind Central Station) are bicycle-friendly and run 24/7',
      ]},
      { type: 'tip', body: 'The OV-chipkaart (€7.50 card + loaded credit) is worth it for any stay of 3+ days. Buy at Schiphol Airport train station or any GVB service point. Alternatively, tap your contactless bank card directly on GVB readers — it works on all trams, metros, and buses and automatically applies the correct fare.' },
      { type: 'faq', faqs: [
        { q: 'Is it easy to cycle as a tourist in Amsterdam?', a: 'Yes — the infrastructure is world-class. The city is flat, cycle lanes are clearly marked, and bike rental shops are everywhere. The learning curve is understanding the traffic hierarchy: trams have absolute right of way, cyclists have priority over pedestrians. Stick to the cycle lanes and you\'ll be fine within 30 minutes.' },
        { q: 'How do I get from Schiphol Airport to Amsterdam city?', a: 'The Amsterdam Centraal train from Schiphol takes 17 minutes and costs €4.50 using a single-use OV ticket or contactless card. Trains run every 10–15 minutes, 5am–midnight, and every 30 min overnight. This is by far the best option — the taxi queue at Schiphol can be 20+ minutes and costs €40–60.' },
      ]},
    ],
  },
  {
    slug: 'is-mexico-city-safe',
    title: 'Is Mexico City Safe for Tourists? Honest Safety Guide (2025)',
    description: 'Mexico City\'s tourist neighbourhoods (Roma, Condesa, Polanco, Coyoacán) are as safe as many European cities. Specific zones and behaviours carry higher risk — here\'s what to know.',
    publishedAt: '2025-06-10',
    readingMinutes: 5,
    category: 'travel',
    city: 'Mexico City',
    country: 'Mexico',
    content: [
      { type: 'intro', body: 'Mexico City (CDMX) is significantly safer for tourists than its reputation suggests — the upscale neighbourhoods of Roma Norte, Condesa, Polanco, and Coyoacán are comparable to most European city centres. Express kidnapping and street robbery do occur, particularly in certain districts and at night, but millions of visitors have positive experiences each year.' },
      { type: 'h2', heading: 'CDMX Safety Overview (2025)' },
      { type: 'table', rows: [
        { label: 'Tourist neighbourhoods', value: 'Roma Norte, Condesa, Polanco, Coyoacán, San Ángel — generally safe, active street life' },
        { label: 'Express kidnapping (secuestro express)', value: 'Primary risk via fake taxis — always use Uber, DiDi, or Cabify; never hail street taxis' },
        { label: 'Petty theft', value: 'Moderate — crowded Metro (especially Line 1–2), Zócalo area; use a money belt' },
        { label: 'Altitude', value: 'CDMX sits at 2,240m — some visitors experience headaches and shortness of breath for first 24–48h' },
        { label: 'Air quality', value: 'Contingencia ambiental (pollution alerts) occasionally restrict driving; AQI can be poor Nov–May' },
        { label: 'Neighbourhoods to avoid', value: 'Tepito, Doctores, parts of Iztapalapa — not tourist areas, high crime' },
      ]},
      { type: 'h2', heading: 'The Taxi Rule: Non-Negotiable in CDMX' },
      { type: 'p', body: 'Express kidnapping via unlicensed taxis (piratas) is Mexico City\'s primary tourist safety risk. The rule is simple and absolute: never hail a taxi from the street in Mexico City. Always use Uber, DiDi, or Cabify — set price before you go, route tracked, driver identified. This single precaution eliminates the most serious risk. Sitio taxis (radio taxis called by phone from reputable stands) are also safe if you have a working number, but apps are easier for visitors.' },
      { type: 'tip', body: 'DiDi (Chinese Didi Chuxing, dominant in Mexico) is typically 10–20% cheaper than Uber in CDMX and has excellent coverage. Download it before arriving. Both apps work without a local SIM if you have roaming data or access to hotel WiFi.' },
      { type: 'faq', faqs: [
        { q: 'Is Mexico City safe at night?', a: 'In Roma Norte, Condesa, and Polanco — yes, these neighbourhoods have active restaurant and bar scenes well past midnight. Use Uber between venues rather than walking more than 2–3 blocks late at night. Avoid wandering into unfamiliar side streets after dark regardless of neighbourhood.' },
        { q: 'Is the Mexico City Metro safe for tourists?', a: 'Generally yes during peak hours (7–10am, 6–9pm) when trains are packed — pickpockets operate in crowded carriages so use a front-facing bag and keep phones in a pocket. The Metro is excellent value (MXN 7 per trip, ~$0.35) and connects all major areas. Women-only carriages (marked pink) are available and recommended.' },
        { q: 'Is there a tourist police service in Mexico City?', a: 'Yes — the SSC Policía de Turismo operates in major tourist areas (Centro Histórico, Zona Rosa, Coyoacán) and speaks basic English. The tourist assistance line is 800-008-9090. Most major museums and attractions have on-site security and tourist-friendly staff.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-nairobi',
    title: 'How Much Does a Taxi Cost in Nairobi? (2025 Fare Guide)',
    description: 'Nairobi taxis are mostly unmetered. Bolt is the recommended option — most city trips cost KES 300–700 ($2.30–5.40). Here\'s the full guide.',
    publishedAt: '2025-06-13',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Nairobi',
    country: 'Kenya',
    content: [
      { type: 'intro', body: 'Nairobi taxis are unmetered — prices must be negotiated before entering, making app-based services essential. Bolt is the dominant app in Nairobi and the safest, most price-transparent option for tourists. Most city trips cost KES 300–700 ($2.30–5.40) via Bolt.' },
      { type: 'h2', heading: 'Nairobi Taxi Fares (2025)' },
      { type: 'table', rows: [
        { label: 'JKIA Airport → Westlands / Karen', value: 'KES 1,200–1,800 (~$9–14) via Bolt; negotiated taxi KES 2,000–3,000' },
        { label: 'CBD → Westlands (5km)', value: 'KES 350–550 via Bolt (~$2.70–4.20)' },
        { label: 'CBD → Karen (18km)', value: 'KES 700–1,100 via Bolt (~$5.40–8.50)' },
        { label: 'Westlands → Gigiri / UN HQ', value: 'KES 200–350 via Bolt (~$1.50–2.70)' },
        { label: 'Little Cab (local app)', value: 'Comparable to Bolt; Kenya-built app; strong in Nairobi' },
        { label: 'Bodaboda (motorbike taxi)', value: 'KES 50–200 for short trips; fast in traffic; not recommended for tourists unfamiliar with road risks' },
      ]},
      { type: 'h2', heading: 'Apps vs Street Taxis in Nairobi' },
      { type: 'p', body: 'Street-hailed taxis in Nairobi (often older Toyota Corollas or Proboxes) have no meters and prices are negotiated, often at inflated tourist rates of 2–3× the Bolt fare. Bolt and Little Cab display an upfront price before booking, track your route, and record the driver\'s details — significantly safer than negotiating in person. The in-app payment (M-Pesa or card) also eliminates cash handling. Download Bolt before arriving in Kenya.' },
      { type: 'tip', body: 'M-Pesa (Kenya\'s mobile money system) is the dominant payment method in Nairobi — widely accepted by Bolt, restaurants, shops, and markets. If you have a Kenyan SIM, register for M-Pesa at any Safaricom outlet. Without a local SIM, card payment via Bolt works fine for most transport needs.' },
      { type: 'faq', faqs: [
        { q: 'Is Uber available in Nairobi?', a: 'Uber operates in Nairobi but has less coverage and driver availability than Bolt, which launched in Kenya earlier and has a larger local driver base. Both apps work; Bolt is generally preferred by locals and typically has shorter wait times.' },
        { q: 'How do you get from Nairobi Airport to the city?', a: 'Via Bolt or Little Cab: KES 1,200–1,800 (~$9–14) to Westlands or city hotels, booked from the arrivals area. Nairobi Commuter Rail (SGR line to Syokimau) costs KES 100 but is infrequent and far from most hotels. Licensed taxi rank at JKIA: negotiate KES 2,000–2,500 to the city — confirm price before entering.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-prague',
    title: 'Prague Daily Budget: How Much Does Prague Cost Per Day? (2025)',
    description: 'Prague costs €40–60/day on a budget, €100–150 mid-range, and €350+ for luxury. It remains one of Europe\'s best-value city break destinations in 2025.',
    publishedAt: '2025-06-16',
    readingMinutes: 5,
    category: 'travel',
    city: 'Prague',
    country: 'Czech Republic',
    content: [
      { type: 'intro', body: 'Prague is one of Europe\'s most affordable city break destinations — a beautiful budget meal costs €5–9, Czech craft beer is €1.50–2.50 per 500ml, and world-class museums charge €5–12. Even mid-range travellers can eat and drink extraordinarily well for under €40/day on food and drink alone.' },
      { type: 'h2', heading: 'Prague Daily Budget Breakdown (2025)' },
      { type: 'table', rows: [
        { label: 'Budget (€40–60/day)', value: 'Hostel €15–25, svíčková lunch menu €6–9, 24-hour transit pass €4.80, free Old Town walk' },
        { label: 'Mid-range (€100–150/day)', value: '3-star hotel €55–90, sit-down restaurant €12–25, 1–2 attractions (Prague Castle €15)' },
        { label: 'Luxury (€350+/day)', value: 'Old Town boutique hotel €180–350, fine dining €50–100pp, private Old Town tour' },
      ]},
      { type: 'h2', heading: 'Where Your Money Goes in Prague' },
      { type: 'ul', items: [
        '**Beer**: Czech pub (pivnice) serves Pilsner Urquell or Kozel for CZK 45–60 (~€1.80–2.50) per 500ml — among Europe\'s cheapest quality lager',
        '**Lunch menu (denní menu)**: CZK 150–220 (~€6–9) at local restaurants — typically includes soup, main course, and sometimes a drink; Prague\'s greatest budget secret',
        '**Prague Card**: CZK 1,490 (€60, 3 days) covers public transport + 60+ attractions including Prague Castle — worth it if you plan 5+ paid sights',
        '**Free sights**: Astronomical Clock (free to watch), Charles Bridge (free), Old Jewish Cemetery (free exterior view), Wenceslas Square',
        '**Tourist traps to avoid**: Restaurants directly on Old Town Square charge 3× normal prices; walk 2 streets back for authentic Czech food at local prices',
      ]},
      { type: 'tip', body: 'Czech koruna (CZK) is the currency — not euros, despite Czech Republic being in the EU. Exchange at banks or ATMs (avoid airport exchange booths with 10–15% commissions). Most restaurants and hotels now accept cards, but local pubs and market stalls are often cash-only.' },
      { type: 'faq', faqs: [
        { q: 'Is Prague more expensive than Budapest?', a: 'Slightly — accommodation in Prague averages 10–20% more than Budapest, and beer is comparable. Both are dramatically cheaper than Vienna or Paris. Prague\'s tourist infrastructure is more developed, which means slightly higher prices in the most visited areas.' },
        { q: 'What is the Czech koruna exchange rate?', a: 'In 2025, approximately CZK 25 = €1 = $1.10 USD. Always pay in CZK rather than accepting "dynamic currency conversion" to euros or dollars at point of sale — the conversion rate offered is typically 5–8% worse than the interbank rate.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-barcelona',
    title: 'Getting Around Barcelona: Metro, Bus, Tram & Taxi Guide (2025)',
    description: 'Barcelona\'s Metro (8 lines, 181 stations) covers the whole city for €2.55/trip. The T-Casual 10-trip card (€12.15) is the best value for tourists.',
    publishedAt: '2025-06-19',
    readingMinutes: 5,
    category: 'travel',
    city: 'Barcelona',
    country: 'Spain',
    content: [
      { type: 'intro', body: 'Barcelona has one of Europe\'s best urban transport networks — the Metro, FGC trains, Renfe commuter rail, trams, night buses, and Barcelona Bus Turístic all integrate under the T-Casual card. Most tourist sights are within 500m of a Metro stop.' },
      { type: 'h2', heading: 'Barcelona Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'Metro (single trip)', value: '€2.55; T-Casual 10 trips: €12.15 (best value); 24h unlimited: €11.35' },
        { label: 'Bus', value: '€2.55/trip; same T-Casual card; useful for beach areas (Bus 59 from Diagonal to Barceloneta)' },
        { label: 'Aerobús to El Prat Airport', value: '€6.75 single, €11.50 return; 35 min to Plaça Catalunya; runs every 5–10 min' },
        { label: 'Metro to El Prat Airport', value: 'L9 Sud: €5.50 (airport supplement); 30–40 min to city; less frequent than Aerobús' },
        { label: 'Taxi (metered)', value: '€2.30 flag fall + €1.21/km; typical city trip €8–18; honest and regulated' },
        { label: 'Bolt / Uber / Cabify', value: 'All operate; typically 10–20% cheaper than taxis for same route' },
      ]},
      { type: 'h2', heading: 'Metro Lines Every Tourist Needs' },
      { type: 'ul', items: [
        '**L2 (purple)**: Sagrada Família — the single most-used Metro stop by tourists',
        '**L3 (green)**: Passeig de Gràcia (Casa Batlló, Casa Milà), Liceu (Gothic Quarter, La Boqueria), Barceloneta (beach)',
        '**L4 (yellow)**: Jaume I (Gothic Quarter, Born neighbourhood), Barceloneta beach',
        '**L5 (blue)**: Hospital de la Santa Creu i Sant Pau, FC Barcelona Camp Nou (Collblanc stop)',
        '**FGC from Plaça Catalunya**: Tibidabo amusement park and Collserola forest — not on Metro but T-Casual accepted',
      ]},
      { type: 'tip', body: 'The T-Casual 10-trip card works for one person making 10 individual trips, or multiple people sharing (validate once per person per journey). It\'s valid on Metro, bus, tram, and FGC within zone 1. Buy at any Metro station machine — you don\'t need to register it. Keep it for your whole stay.' },
      { type: 'faq', faqs: [
        { q: 'Is the Barcelona Bus Turístic worth it?', a: 'At €32/day (24h hop-on hop-off), it\'s only worth it if you plan to use it extensively. The Metro reaches Sagrada Família, Park Güell, Barceloneta, and Passeig de Gràcia — all major sights — more efficiently for €2.55/trip. The bus is better as a scenic orientation on day one rather than your primary transport.' },
        { q: 'How do I get from Barcelona Airport (El Prat) to the city centre?', a: 'The Aerobús is the simplest option: €6.75, 35 minutes to Plaça Catalunya, buses every 5–10 minutes from both Terminal 1 and T2. The Metro L9 is cheaper at €5.50 but slower (transfers needed). Taxi from El Prat to city centre: fixed rate €39 (approved by Barcelona municipality) — no negotiation needed, it\'s the standard metered fare.' },
      ]},
    ],
  },
  {
    slug: 'uber-vs-taxi-dubai',
    title: 'Uber vs Taxi in Dubai: Careem, RTA Cabs & Which to Use (2025)',
    description: 'In Dubai, official RTA taxis and Careem (owned by Uber) are both excellent. RTA taxis have no surge pricing; Careem offers upfront pricing. Here\'s the full comparison.',
    publishedAt: '2025-06-22',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Dubai',
    country: 'UAE',
    content: [
      { type: 'intro', body: 'Dubai has one of the world\'s most reliable taxi systems — RTA (Roads and Transport Authority) metered white cabs are clean, air-conditioned, metered, and plentiful. Careem (Uber\'s Middle East subsidiary) offers app-based booking with upfront pricing. Both are excellent; the choice depends on your situation.' },
      { type: 'h2', heading: 'Dubai RTA Taxi vs Careem (2025)' },
      { type: 'table', rows: [
        { label: 'RTA metered taxi', value: 'AED 12 minimum, AED 1.97/km; no surge pricing ever; airport surcharge AED 20; hailable on street' },
        { label: 'Careem (Uber ME)', value: 'Upfront price; no surge on standard routes; app tracking; card/wallet payment' },
        { label: 'Uber (via Careem app)', value: 'Same Careem app since merger; UberX = Careem Go; premium options available' },
        { label: '5km city trip', value: 'RTA taxi: AED 22–28 | Careem: AED 18–25 (often slightly cheaper)' },
        { label: 'DXB Airport → Downtown Dubai', value: 'RTA taxi: AED 50–70 + AED 20 surcharge | Careem: AED 45–65 (set price)' },
        { label: 'Women\'s taxi (RTA)', value: 'Pink-roofed taxis with female drivers; book via RTA app or request at designated ranks' },
      ]},
      { type: 'h2', heading: 'When to Use Each' },
      { type: 'ul', items: [
        '**Use RTA taxi**: when you need a cab immediately (hail on Sheikh Zayed Road), for women who prefer female drivers, during events when Careem surge pricing applies',
        '**Use Careem**: when you want an upfront price, for cashless payment, for scheduled bookings, for premium vehicles (Careem Plus)',
        '**Dubai Metro**: for routes along the Red and Green lines — far cheaper and often faster in peak-hour traffic',
        '**Avoid**: any unlicensed private car offering rides near tourist spots — these operate illegally and have no insurance',
      ]},
      { type: 'tip', body: 'Dubai taxis and Careem do not require tipping — it\'s not part of UAE taxi culture. Round up to the nearest dirham if you want to acknowledge good service, but this is entirely optional and not expected by drivers.' },
      { type: 'faq', faqs: [
        { q: 'Is Careem the same as Uber in Dubai?', a: 'Since Uber acquired Careem in 2019, both apps operate as the same service in the UAE. The Careem app is the dominant local brand and has more features (scheduled rides, cash payment option) in the UAE market. You can use either app — they connect to the same driver pool.' },
        { q: 'How much does a taxi cost from Dubai Mall to the airport?', a: 'DXB Terminal 1/3: AED 40–55 via Careem or metered RTA taxi (plus AED 20 airport drop-off surcharge). Journey time: 15–20 minutes with light traffic, 30–45 minutes during peak hour on Sheikh Zayed Road. Al Maktoum Airport (DWC) is 40km further — budget AED 120–160.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-doha',
    title: 'How Much Does a Taxi Cost in Doha? (2025 Fare Guide)',
    description: 'Doha taxis use meters: QAR 3 flag fall + QAR 1.60/km. Airport to city costs QAR 45–70 (~$12–19). Karwa is the official operator; Uber also available.',
    publishedAt: '2025-06-25',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Doha',
    country: 'Qatar',
    content: [
      { type: 'intro', body: 'Doha\'s official taxis (Karwa, operated by Mowasalat) are metered, air-conditioned, and reliable: QAR 3 flag fall + QAR 1.60/km. A typical city centre trip costs QAR 15–35 (~$4–9.50). The Doha Metro is the cheapest option for many journeys.' },
      { type: 'h2', heading: 'Doha Taxi & Transport Fares (2025)' },
      { type: 'table', rows: [
        { label: 'Hamad International Airport (DOH) → West Bay/Souq Waqif', value: 'QAR 45–70 (~$12–19), 20–30 min' },
        { label: 'Souq Waqif → The Pearl', value: 'QAR 25–40 (~$7–11), 15 min' },
        { label: 'West Bay → Katara Cultural Village', value: 'QAR 20–30 (~$5.50–8), 10 min' },
        { label: 'Doha Metro (Red/Gold line)', value: 'QAR 2–4/trip; airport to West Bay: QAR 2, 15 min' },
        { label: 'Uber (available)', value: 'Set price upfront; comparable to Karwa metered; convenient for non-Arabic speakers' },
        { label: 'Night surcharge', value: 'After 22:00: rate increases by 25%' },
      ]},
      { type: 'h2', heading: 'Getting Around Doha: Apps vs Metro' },
      { type: 'p', body: 'Karwa taxis can be hailed on the street or booked via the Karwa app. Uber is available and widely used by expats and visitors — both are safe, legal, and air-conditioned. The Doha Metro (Red Line: Airport to Al Wakra; Gold Line: Al Qassar to Education City) is excellent and QAR 2–4 per journey. It opened in 2019 and expanded for the FIFA World Cup 2022 — covering Hamad Airport, West Bay, Msheireb Downtown, and most tourist areas. Women-only metro carriages are available on all trains.' },
      { type: 'tip', body: 'During Ramadan, taxi availability can be limited around iftar time (sunset) as many drivers break their fast. Plan journeys outside the iftar window (30–60 minutes either side of sunset) or pre-book via the Karwa app. The Metro runs normal service during Ramadan.' },
      { type: 'faq', faqs: [
        { q: 'Do you tip taxi drivers in Qatar?', a: 'Not expected — Qatar has no tipping culture for taxis. Rounding up to the nearest QAR 5 is acceptable as a small gesture but completely optional. Uber and Karwa app journeys are paid cashlessly with no tip prompt.' },
        { q: 'Is it safe for solo women to take taxis in Doha?', a: 'Yes — Karwa taxis are government-regulated, air-conditioned, and safe. Women travelling solo are common in Doha (large expat community, many female professionals). The Karwa app shows driver name, photo, and plate number before you enter. Women-only Karwa taxis (with female drivers) are also available via the app.' },
      ]},
    ],
  },
  {
    slug: 'best-time-to-visit-istanbul',
    title: 'Best Time to Visit Istanbul: When to Visit the City on Two Continents (2025)',
    description: 'The best time to visit Istanbul is April to June or September to October — comfortable at 18–25°C with clear skies for Bosphorus views and shorter queues at Hagia Sophia.',
    publishedAt: '2025-06-28',
    readingMinutes: 5,
    category: 'travel',
    city: 'Istanbul',
    country: 'Turkey',
    content: [
      { type: 'intro', body: 'Istanbul\'s ideal visiting months are April to June (18–25°C, tulips in bloom in April, lively rooftop bar season) and September to October (warm at 20–26°C, summer crowds thinning, golden light over the Bosphorus). July and August are hot, crowded, and peak-priced.' },
      { type: 'h2', heading: 'Istanbul Season by Season' },
      { type: 'table', rows: [
        { label: 'Apr–Jun (Spring)', value: '15–25°C, Istanbul Tulip Festival (Apr), moderate crowds, shoulder prices' },
        { label: 'Jul–Aug (Peak summer)', value: '28–35°C, Hagia Sophia queues 90+ min without booking, fully booked Bosphorus cruises' },
        { label: 'Sep–Oct (Best months)', value: '18–26°C, fewer tourists, fish season begins (Oct — sea bass, bluefish from the Bosphorus)' },
        { label: 'Nov–Mar (Winter)', value: '3–10°C, occasional snow (beautiful on minarets), cheapest prices, cosy çay (tea) culture' },
      ]},
      { type: 'h2', heading: 'Istanbul Events Worth Timing Around' },
      { type: 'ul', items: [
        '**Istanbul Tulip Festival (April)**: Over 30 million tulips across parks including Emirgan, Gülhane, and the grounds of Topkapi Palace — spectacular and free',
        '**Istanbul Film Festival (April)**: International films screened at historic venues across the city',
        '**Ramadan**: Sultanahmet and Eminönü transform at iftar — stalls appear in front of the Blue Mosque, families picnic in the park; a uniquely atmospheric time to visit',
        '**New Year\'s Eve (Dec 31)**: Fireworks over the Bosphorus; İstiklal Avenue celebrations; book restaurants months ahead',
      ]},
      { type: 'tip', body: 'Pre-booking Hagia Sophia (now a mosque but open to non-Muslim visitors) is essential in summer — the free entry is managed via timed slots that fill weeks ahead. The Blue Mosque is also free and requires modest dress (head covering provided at entrance). Both are best visited at dawn or early morning before tour groups arrive.' },
      { type: 'faq', faqs: [
        { q: 'Is Istanbul expensive?', a: 'Istanbul has become significantly cheaper for visitors paying in EUR or USD following the Turkish lira\'s depreciation. In 2025, a quality hotel near Sultanahmet costs €60–120/night, a full fish dinner on the Bosphorus runs €20–40pp, and a public transport day pass is TRY 130 (~€3.50). Istanbul offers exceptional value for most international visitors.' },
        { q: 'How many days do you need in Istanbul?', a: 'Four to five days covers: Hagia Sophia, Blue Mosque, Topkapi Palace, Grand Bazaar, Spice Market (Mısır Çarşısı), a Bosphorus cruise, and a day crossing to the Asian side (Kadıköy neighbourhood). A week allows day trips to Princes\' Islands, Bursa, or the Black Sea coast.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-lisbon',
    title: 'Lisbon Daily Budget: How Much Does Lisbon Cost Per Day? (2025)',
    description: 'Lisbon costs €50–75/day on a tight budget, €130–200 mid-range, and €400+ for luxury. Here\'s the complete spending guide for Portugal\'s sun-drenched capital.',
    publishedAt: '2025-07-01',
    readingMinutes: 5,
    category: 'travel',
    city: 'Lisbon',
    country: 'Portugal',
    content: [
      { type: 'intro', body: 'Lisbon is one of Western Europe\'s most affordable capitals — a pastel de nata costs €1.10, a glass of house wine at a traditional tasca is €1.50, and a prego (steak sandwich) at a local café runs €4–7. Mid-range travellers can eat and drink as well as almost anywhere in Europe for a fraction of the cost.' },
      { type: 'h2', heading: 'Lisbon Daily Budget Breakdown (2025)' },
      { type: 'table', rows: [
        { label: 'Budget (€50–75/day)', value: 'Hostel €20–35, prego lunch €5–8, 24h Carris transport pass €6.80, free miradouros' },
        { label: 'Mid-range (€130–200/day)', value: 'Guesthouse €65–110, restaurant meals €14–30, Museu do Azulejo + Jerónimos Monastery €12 each' },
        { label: 'Luxury (€400+/day)', value: 'Chiado boutique hotel €200–400+, fine dining €60–120pp, private fado show with dinner' },
      ]},
      { type: 'h2', heading: 'Lisbon\'s Best Value Experiences' },
      { type: 'ul', items: [
        '**Pastéis de Belém**: The original custard tart (€1.30 each) at the 1837-founded café in Belém — get there before 11am to avoid a queue',
        '**Ginjinha**: Cherry liqueur served in an edible chocolate cup for €1.50 from the kiosk on Largo de S. Domingos — a Lisbon institution',
        '**28 tram**: Iconic yellow tram through Alfama for €3.35 (OV card) — tourist attraction and real transport in one',
        '**Miradouros (viewpoints)**: Miradouro da Graça, Santa Luzia, Portas do Sol — all free with the best views in the city',
        '**Caldo verde**: Traditional kale and potato soup for €3–5 at any tasca — a warming meal in itself',
      ]},
      { type: 'tip', body: 'Lisbon\'s famous Tram 28 has €3.35 OV-card fares — but tourists sometimes pay €3.35 cash on board. The cheaper hack: buy a Viva Viagem card (€0.50) and load a 24h Carris/Metro pass (€6.80), which covers unlimited tram, bus, and metro travel all day. The 28 tram is a genuine route (not a tourist train) so standing room only during peak hours.' },
      { type: 'faq', faqs: [
        { q: 'Is Lisbon more expensive than it used to be?', a: 'Yes — Lisbon has seen significant tourism-driven price inflation since 2018, particularly for accommodation. However, food and drink remain excellent value by Western European standards. Restaurants 2–3 streets back from tourist sites charge 30–50% less for the same quality. Avoid the waterfront (Ribeira) restaurants unless you\'re happy to pay tourist-zone prices.' },
        { q: 'What is the best area to stay in Lisbon for budget travellers?', a: 'Mouraria, Intendente, and Arroios offer the best combination of affordability, authenticity, and transport access. These neighbourhoods are up-and-coming rather than gentrified and have excellent local restaurants. Alfama is atmospheric but accommodation there is expensive for its quality. Bairro Alto has great nightlife access.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-berlin',
    title: 'Getting Around Berlin: U-Bahn, S-Bahn, Tram & Bike Guide (2025)',
    description: 'Berlin\'s BVG public transport network covers the entire city for €3.80/trip or €41/week. The U-Bahn and S-Bahn integrate seamlessly with one ticket.',
    publishedAt: '2025-07-04',
    readingMinutes: 5,
    category: 'travel',
    city: 'Berlin',
    country: 'Germany',
    content: [
      { type: 'intro', body: 'Berlin\'s public transport network (BVG) — U-Bahn, S-Bahn, trams, and buses — covers 892km² of city for €3.80 per trip on a standard single ticket. The Deutschlandticket (€49/month) covers all local and regional transport across Germany and is valid in Berlin.' },
      { type: 'h2', heading: 'Berlin Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'Single ticket (Zones AB)', value: '€3.80; valid 2h on all U-Bahn, S-Bahn, tram, bus within zones A+B' },
        { label: '24-hour ticket', value: '€10.00 zones AB; €10.80 ABC (includes Potsdam)' },
        { label: '7-day ticket', value: '€41.00 zones AB; best value for a week-long stay' },
        { label: 'Deutschlandticket', value: '€49/month; all German local transport; valid only for calendar month purchased' },
        { label: 'Berlin Airport (BER) → Alexanderplatz', value: 'S-Bahn S9: €3.80, 30 min; RE7 express train: €3.80, 20 min' },
        { label: 'Taxi / Uber / Bolt', value: 'Taxi: €4.00 flag fall + €2.00/km; Uber and Bolt available; FreeNow dominant app' },
      ]},
      { type: 'h2', heading: 'Key Berlin U-Bahn Lines for Tourists' },
      { type: 'ul', items: [
        '**U2**: Zoologischer Garten (Zoo, KaDeWe) → Ernst-Reuter-Platz → Potsdamer Platz → Stadtmitte → Alexanderplatz',
        '**U6**: Friedrichstraße (Checkpoint Charlie, Berlin\'s spy corridor) → Mehringdamm (Kreuzberg) → Tempelhof',
        '**U8**: Hermannstraße (Neukölln nightlife) → Kottbusser Tor (Kreuzberg heart) → Weinmeisterstraße (Hackescher Markt area)',
        '**S-Bahn Ringbahn (S41/S42)**: The circle line connecting Prenzlauer Berg, Mitte, Kreuzberg, Schöneberg, Charlottenburg — useful for cross-city journeys',
        '**Tram M10**: Runs through Prenzlauer Berg and Mitte — especially useful for Mauerpark flea market (Sunday) and Volkspark Friedrichshain',
      ]},
      { type: 'tip', body: 'Berlin is one of Europe\'s most cycling-friendly cities — Nextbike, Tier, and Lime dockless e-bikes are available throughout the city, typically €1 to unlock + €0.25–0.35/minute. The Berlin Wall Trail (Berliner Mauerweg, 160km) circles the entire city along the former Wall route. For a day\'s cycling through Tiergarten, the Spree waterfront, and East Berlin, rent a bike from one of the many shops near Hackescher Markt.' },
      { type: 'faq', faqs: [
        { q: 'How do I validate my BVG ticket in Berlin?', a: 'Single tickets must be validated (stamped) in the yellow machines on the platform or at the tram/bus door before travel — not on board the U-Bahn. Day and week passes are pre-validated when purchased from machines. Inspectors (Kontrolleure) check without warning and fines for ticketless travel are €60.' },
        { q: 'Is Uber safe to use in Berlin?', a: 'Yes — Uber, Bolt, and FreeNow all operate safely in Berlin. FreeNow also lets you book official metered taxis, which are slightly more expensive but have no surge pricing. Berlin\'s taxi industry is regulated and reliable; Uber drivers are all licensed private hire vehicles.' },
      ]},
    ],
  },
  {
    slug: 'is-jakarta-safe',
    title: 'Is Jakarta Safe for Tourists? Honest Safety Guide (2025)',
    description: 'Jakarta is generally safe for tourists who use ride-hailing apps, avoid specific flood-prone areas, and exercise normal big-city awareness. Here\'s the full picture.',
    publishedAt: '2025-07-07',
    readingMinutes: 4,
    category: 'travel',
    city: 'Jakarta',
    country: 'Indonesia',
    content: [
      { type: 'intro', body: 'Jakarta is a megacity of 11 million people with the safety challenges that entails — but violent crime targeting foreign tourists is rare. The main concerns are traffic accidents (genuinely dangerous), petty theft in crowded areas, and flooding during the wet season. Grab and Gojek app transport eliminate most risks for visitors.' },
      { type: 'h2', heading: 'Jakarta Safety Overview (2025)' },
      { type: 'table', rows: [
        { label: 'Violent crime', value: 'Low risk in tourist areas — Jakarta is safer than its regional reputation suggests' },
        { label: 'Traffic', value: 'Significant risk — Jakarta has some of the world\'s worst traffic and road safety; always use seatbelts' },
        { label: 'Flooding (Nov–Mar)', value: 'North Jakarta floods badly in wet season — check weather forecasts and avoid low-lying areas' },
        { label: 'Petty theft', value: 'Moderate in crowded Kota Tua (Old Town), markets; use a money belt in crowds' },
        { label: 'Ojek (motorbike taxis)', value: 'Available via Gojek app (GoRide); fast in traffic but riskier than car; tourist\'s call' },
        { label: 'Air quality', value: 'Jakarta regularly records Unhealthy AQI (150+); consider an N95 mask in peak dry season' },
      ]},
      { type: 'h2', heading: 'Transport Safety in Jakarta' },
      { type: 'p', body: 'Grab and Gojek are essential in Jakarta — never take an unlicensed ojek or street-hailed taxi. The TransJakarta Busway (BRT) and MRT Jakarta are safe, clean, and air-conditioned alternatives that bypass traffic congestion. The MRT North–South corridor (Lebak Bulus to Bundaran HI) covers 16km in 30 minutes and is excellent for the main tourist and business corridor.' },
      { type: 'tip', body: 'Jakarta\'s traffic is legendary — plan journeys that involve crossing the city during peak hours (7–10am, 5–8pm) to take 2–3× longer than off-peak. The MRT and TransJakarta busway run on dedicated lanes and are immune to traffic. For exploring Kota Tua (Old Town), the Kota Tua MRT station (opening 2025) dramatically improves access.' },
      { type: 'faq', faqs: [
        { q: 'Is Jakarta worth visiting?', a: 'Jakarta is often skipped in favour of Bali or Yogyakarta, but it rewards curious visitors with world-class food (nasi goreng from a warung cart at 11pm is transcendent), the colonial Kota Tua district, excellent museums (National Museum, Museum MACAN for contemporary art), and a genuinely vast, fascinating megacity energy.' },
        { q: 'What vaccinations are needed for Jakarta?', a: 'Standard recommendations: Hepatitis A, Typhoid. Dengue fever is a risk in Jakarta — use mosquito repellent especially around dawn and dusk. Rabies vaccination is recommended for extended stays. Check your government\'s travel health advisory before departure.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-abu-dhabi',
    title: 'How Much Does a Taxi Cost in Abu Dhabi? (2025 Fare Guide)',
    description: 'Abu Dhabi taxis: AED 5 flag fall + AED 1.82/km. Airport to city costs AED 60–90 (~$16–25). TransAD is the official metered operator — safe and reliable.',
    publishedAt: '2025-07-10',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Abu Dhabi',
    country: 'UAE',
    content: [
      { type: 'intro', body: 'Abu Dhabi taxis are operated by TransAD — clean, metered, and reliable. Flag fall AED 5, then AED 1.82/km. Abu Dhabi International Airport to downtown costs AED 60–90 (~$16–25). Careem and Uber also operate and offer comparable prices with upfront booking.' },
      { type: 'h2', heading: 'Abu Dhabi Taxi Fares (2025)' },
      { type: 'table', rows: [
        { label: 'AUH Airport → Downtown / Corniche', value: 'AED 60–90 (~$16–25), 30–40 min' },
        { label: 'Corniche → Sheikh Zayed Grand Mosque', value: 'AED 25–40 (~$7–11), 15 min' },
        { label: 'Downtown → Yas Island', value: 'AED 65–90 (~$18–25), 30 min' },
        { label: 'Abu Dhabi → Dubai (130km)', value: 'AED 200–280 (~$55–76); intercity taxis available; bus is far cheaper (AED 25)' },
        { label: 'Night surcharge', value: 'After 22:00: AED 5 additional flag fall + slight rate increase' },
        { label: 'Women-only taxis', value: 'Available via TransAD app — pink-themed vehicles with female drivers' },
      ]},
      { type: 'h2', heading: 'Abu Dhabi vs Dubai Taxi Pricing' },
      { type: 'p', body: 'Abu Dhabi taxis are slightly cheaper per km than Dubai RTA taxis (AED 1.82/km vs AED 1.97/km) and use a higher flag fall (AED 5 vs AED 3.50 for Dubai). Overall, city trips in Abu Dhabi are comparable in total cost to Dubai for similar distances. Careem operates in both cities and is often the most convenient option with upfront pricing and no cash needed.' },
      { type: 'tip', body: 'Abu Dhabi\'s layout is more spread out than Dubai — the Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, and Yas Island (Ferrari World, Warner Bros. World) are 20–40km from downtown. Plan for longer taxi journeys and higher transport costs than a comparable European city. The Abu Dhabi bus network (Mawaqif) is cheap but slow and infrequent for tourist routes.' },
      { type: 'faq', faqs: [
        { q: 'Is there Uber in Abu Dhabi?', a: 'Uber operates in Abu Dhabi through the Careem app (same service since the 2019 merger). Standard Careem/Uber trips in Abu Dhabi are priced similarly to TransAD metered taxis, with the advantage of upfront pricing and app-based booking. Both are safe and widely used.' },
        { q: 'How do I get from Abu Dhabi Airport to the city?', a: 'The most convenient option is a TransAD metered taxi (AED 60–90) or Careem (AED 55–80, pre-booked). The Airport Bus (Route 901 to Abu Dhabi Central Bus Station) costs AED 4 but takes 45–60 minutes. There is no direct metro connection — Abu Dhabi\'s metro is still under construction as of 2025.' },
      ]},
    ],
  },
  {
    slug: 'best-time-to-visit-prague',
    title: 'Best Time to Visit Prague: Fairy-Tale City in Every Season (2025)',
    description: 'The best time to visit Prague is May to June or September — comfortable at 18–24°C, manageable crowds, and the city at its most beautiful before or after summer peak.',
    publishedAt: '2025-07-13',
    readingMinutes: 4,
    category: 'travel',
    city: 'Prague',
    country: 'Czech Republic',
    content: [
      { type: 'intro', body: 'Prague is stunning year-round — but May to June (18–24°C, long evenings, beer garden season) and September to October (golden light, smaller crowds than August, affordable rates) offer the best experience. December brings arguably Europe\'s finest Christmas markets.' },
      { type: 'h2', heading: 'Prague Season by Season' },
      { type: 'table', rows: [
        { label: 'Mar–Apr (Spring)', value: '8–18°C, Easter markets in Old Town Square, cheaper than summer, some rainy days' },
        { label: 'May–Jun (Best months)', value: '18–24°C, Prague Spring Music Festival (May), long days, beer gardens open, busy but not gridlocked' },
        { label: 'Jul–Aug (Peak)', value: '25–32°C, Old Town Square heaving with tour groups, Charles Bridge crowded by 9am' },
        { label: 'Sep–Oct (Second best)', value: '14–22°C, autumn colours, Prague Fringe festival, significantly quieter, good hotel availability' },
        { label: 'Nov–Dec', value: '0–10°C, Christmas markets (Nov 30–Jan 6) — among Europe\'s most magical; mulled wine in the Old Town Square' },
        { label: 'Jan–Feb (Cheapest)', value: '-2 to 5°C, snow possible, minimal crowds, cheapest hotels, peaceful cobblestones to yourself' },
      ]},
      { type: 'h2', heading: 'Prague Crowds: What to Expect' },
      { type: 'ul', items: [
        'Charles Bridge: tourist-free only 5–7am in summer — go at dawn for the most photographed view without crowds',
        'Prague Castle: book timed entry online to skip queues; ticket C (gardens + exterior) is free; circuit tickets from CZK 250',
        'Old Town Astronomical Clock: crowds gather for the hourly show (9am–9pm) — arrive 5 min early for a front-row spot',
        'Wenceslas Square: always walkable; best in morning for the weekend farmers market at the top of the square',
      ]},
      { type: 'tip', body: 'Prague\'s most underrated neighbourhood: Vinohrady and Žižkov (20 minutes\' walk from Old Town) have excellent local restaurants, craft beer bars, and almost no tourists. The Žižkov TV Tower (CZK 250 observation deck) offers the best city panorama and has Crawling Babies sculptures by David Černý on its exterior.' },
      { type: 'faq', faqs: [
        { q: 'Is Prague expensive?', a: 'No — Prague is one of Europe\'s best-value city breaks. Quality hostel beds from €15/night, Czech craft beer from €1.80 per 500ml, a full lunch menu for €6–9. Even mid-range restaurant meals rarely exceed €20 per person. Prague is substantially cheaper than Vienna, Munich, or Paris for equivalent quality.' },
        { q: 'Is it safe to walk Prague at night?', a: 'Yes — Prague is one of Europe\'s safer cities for walking at night. The main concern is pickpockets on Charles Bridge and in bars, and tourist scams around unlicensed exchanges and strip clubs in Wenceslas Square. Stick to lit areas in the Old Town and use Bolt for late-night trips back to outlying hotels.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-budapest',
    title: 'Budapest Daily Budget: How Much Does Budapest Cost Per Day? (2025)',
    description: 'Budapest costs €35–55/day on a budget, €95–150 mid-range, and €350+ for luxury. It\'s one of Europe\'s great underpriced capital cities in 2025.',
    publishedAt: '2025-07-16',
    readingMinutes: 5,
    category: 'travel',
    city: 'Budapest',
    country: 'Hungary',
    content: [
      { type: 'intro', body: 'Budapest is extraordinary value for a European capital — a thermal bath costs €18–25, a full goulash and a craft beer dinner runs €12–18, and a week-long public transport pass is under €17. Budget travellers can live remarkably well for €50/day; mid-range visitors enjoy one of Europe\'s great dining and nightlife scenes for €100–150.' },
      { type: 'h2', heading: 'Budapest Daily Budget Breakdown (2025)' },
      { type: 'table', rows: [
        { label: 'Budget (€35–55/day)', value: 'Hostel HUF 4,500–8,000 (~€11–20), lángos €2–4, 24h BKK pass HUF 1,650 (~€4.15)' },
        { label: 'Mid-range (€95–150/day)', value: '3-star Pest hotel €55–90, restaurant meals €10–20, Széchenyi baths €20 + one attraction' },
        { label: 'Luxury (€350+/day)', value: 'Grand Hotel Margitsziget or Aria €180–350+, fine dining €50–90pp, private city tour' },
      ]},
      { type: 'h2', heading: 'Budapest\'s Essential Budget Experiences' },
      { type: 'ul', items: [
        '**Széchenyi Thermal Baths**: HUF 8,200 (~€20) for all-day access to indoor and outdoor thermal pools — one of Europe\'s great experiences',
        '**Ruin bars**: Szimpla Kert (VII. District) — craft beer HUF 900–1,500 (~€2.25–3.80), open courtyards, live music, no cover charge',
        '**Lángos**: Deep-fried flatbread with sour cream and cheese from market stalls — HUF 600–1,200 (~€1.50–3) for a filling lunch',
        '**Great Market Hall (Központi Vásárcsarnok)**: Free to enter; buy paprika (HUF 1,000–2,500), pick up langos upstairs, see the embroidery at local prices',
        '**Danube views**: Parliament building lit at night, Fisherman\'s Bastion sunset, Chain Bridge — all free to walk and photograph',
      ]},
      { type: 'tip', body: 'Hungary uses Hungarian Forint (HUF) — not euros. Always pay in HUF to avoid dynamic currency conversion fees (typically 3–5% worse than the interbank rate). ATMs of OTP Bank and Raiffeisen offer good rates; avoid standalone ATMs at tourist sites that offer "guaranteed rates" with commission.' },
      { type: 'faq', faqs: [
        { q: 'Is Budapest worth visiting for 3 days?', a: 'Three days is ideal for a first visit: Buda (Castle Hill, Fisherman\'s Bastion, Matthias Church, Gellért Hill) on day one; Pest (Parliament, Great Market Hall, Jewish Quarter, ruin bars) on day two; thermal baths and a Danube dinner cruise on day three. Excellent value and one of Europe\'s most rewarding short breaks.' },
        { q: 'Is Budapest nightlife expensive?', a: 'No — Budapest is one of Europe\'s most affordable nightlife destinations. Cocktails in the ruin bars of District VII cost €4–7; craft beer €2–4; club entry (typically after midnight) €5–10. The city\'s party scene — especially around Király utca and Kazinczy utca — is renowned across Europe for value and atmosphere.' },
      ]},
    ],
  },
  {
    slug: 'tipping-airport-porters',
    title: 'Airport Porter Tipping Guide: How Much to Tip Worldwide (2025)',
    description: 'Airport porter tipping ranges from $1–2 per bag in the USA to nothing expected in Japan. Here\'s exactly what to tip at airports worldwide in 2025.',
    publishedAt: '2025-07-19',
    readingMinutes: 4,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'Airport porter tipping norms vary significantly by country. In the USA, $1–2 per bag is standard and expected. In Japan and Singapore, tipping is unnecessary and may be declined. For most countries, $1–2 USD equivalent per bag is a generous and appropriate gesture.' },
      { type: 'h2', heading: 'Airport Porter Tipping by Country/Region' },
      { type: 'table', rows: [
        { label: 'USA', value: '$2–3 per bag minimum; $5 for multiple bags or a single heavy bag' },
        { label: 'UK', value: '£1–2 per bag; optional but appreciated — most UK airports have trolleys and self-service' },
        { label: 'Western Europe', value: '€1–2 per bag; tip at your discretion — porter service is rare at self-service airports' },
        { label: 'Southeast Asia', value: '$1–2 USD equivalent (in local currency); appreciated but not required' },
        { label: 'India', value: 'INR 50–100 per bag ($0.60–1.20); porters at Indian airports actively solicit help' },
        { label: 'Middle East', value: 'AED/QAR 5–10 per bag (~$1.40–2.70); appreciated but not expected' },
        { label: 'Japan / Singapore', value: 'No tip — professional service is included; a sincere "thank you" is appropriate' },
        { label: 'Africa', value: 'USD $1–2 per bag; in local currency where possible' },
      ]},
      { type: 'h2', heading: 'Porter Service: When to Use It' },
      { type: 'ul', items: [
        '**Arriving with lots of luggage**: Porters at the baggage carousel save time when you\'re managing multiple bags and navigating customs',
        '**Departure with heavy bags**: Many airports have porter services at check-in zones to help with oversized or overweight bags',
        '**Train station connections**: Some major airports (Heathrow, Charles de Gaulle) have porter services at the rail connection points',
        '**Hotel-to-terminal transfers**: Cruise terminal and resort porters handle luggage transfer — tip as per hotel porter norms ($1–2 per bag)',
      ]},
      { type: 'tip', body: 'At Indian airports (Mumbai, Delhi, Chennai), official licensed porters wear red uniforms and carry ID. They will often approach you in arrivals — agree the total price or tip amount before they touch your bags to avoid disagreements after. A fair rate is INR 100–150 for 1–2 bags for a short trolley distance.' },
      { type: 'faq', faqs: [
        { q: 'Do I have to use airport porter services?', a: 'No — they are entirely optional. All major airports have self-service trolleys (usually free or €1–2 deposit refundable). Porters are useful when you\'re traveling with multiple heavy bags, have mobility issues, or are pressed for time at a large complex airport.' },
        { q: 'Should I tip the hotel porter separately from the airport porter?', a: 'Yes — they are different people in different jobs. Hotel porters who bring your bags to your room deserve $1–2 per bag. If a hotel porter also gets your taxi or makes a restaurant reservation, tip additionally for that service ($5–10). Tip each service interaction separately rather than all at once on check-out.' },
      ]},
    ],
  },
  {
    slug: 'best-time-to-visit-lisbon',
    title: 'Best Time to Visit Lisbon: Sun, Sardines & the Right Season (2025)',
    description: 'The best time to visit Lisbon is April to June or September to October — warm at 20–27°C, vibrant street life, and before July\'s heat and tourist saturation.',
    publishedAt: '2025-07-22',
    readingMinutes: 4,
    category: 'travel',
    city: 'Lisbon',
    country: 'Portugal',
    content: [
      { type: 'intro', body: 'Lisbon\'s ideal months are April to June (18–26°C, outdoor café culture in full swing, the famous Festas de Lisboa in June) and September to October (22–27°C, fewer tourists than summer, beaches still warm, grape harvest in the Alentejo region). July and August are scorching at 30–35°C with visitor numbers at their peak.' },
      { type: 'h2', heading: 'Lisbon Season by Season' },
      { type: 'table', rows: [
        { label: 'Mar–May (Spring)', value: '14–23°C, cherry blossoms along Avenida da Liberdade, lower prices, ideal walking weather' },
        { label: 'Jun (Festas de Lisboa)', value: '20–27°C, street parties throughout Alfama and Mouraria, sardines grilled on every corner, locals celebrate St. Anthony (Jun 13)' },
        { label: 'Jul–Aug (Peak)', value: '27–35°C, very busy, Sintra and Cascais crowded, accommodation expensive' },
        { label: 'Sep–Oct (Sweet spot)', value: '20–27°C, Atlantic still 20°C for swimming, wine harvest, prices ease post-August' },
        { label: 'Nov–Feb (Winter)', value: '10–16°C, occasional rain, some sites close reduced hours, cheapest flights and hotels' },
      ]},
      { type: 'h2', heading: 'Day Trips from Lisbon' },
      { type: 'ul', items: [
        '**Sintra (40 min by train, €2.30)**: Pena Palace, Quinta da Regaleira, Moorish Castle — go early (7am) to beat the crowds; it\'s extremely busy Jul–Aug',
        '**Cascais (40 min by train, €2.30)**: Coastal resort town with excellent seafood, cycling along the coast, and Boca do Inferno sea cliffs',
        '**Óbidos (1.5h by bus)**: Medieval walled village with cherry liqueur (ginjinha) sold in chocolate cups — perfect day trip Oct–Apr when less visited',
        '**Setúbal and Arrábida Natural Park (1h by bus)**: Crystal-clear turquoise water, limestone cliffs — one of Europe\'s most beautiful coastlines, best Jun–Sep',
      ]},
      { type: 'tip', body: 'June 12–13 (Festa de Santo António) is Lisbon at its most infectious — the entire Alfama neighbourhood fills with grilled sardines, vinho verde, street parties, and traditional marchas (parade groups). Arrive by 8pm for a table at a neighbourhood tasco; by midnight the streets are packed. This is when Lisbon belongs to the Lisboetas, and visitors are warmly welcome.' },
      { type: 'faq', faqs: [
        { q: 'Is October good for Lisbon?', a: 'October is arguably Lisbon\'s finest month — warm at 20–24°C, crowds 40–50% lower than August, accommodation significantly cheaper, and the Atlantic is still warm enough for swimming at Cascais and Costa da Caparica. The autumn light over the Tejo is extraordinary.' },
        { q: 'How many days do you need in Lisbon?', a: 'Three days covers the essentials: Alfama and the Castelo São Jorge, Belém (Jerónimos Monastery, Pastéis de Belém, MAAT museum), and a day trip to Sintra. Five days adds Cascais, the Museu do Azulejo, and unhurried evenings in Bairro Alto and Chiado. A week allows you to explore the Alentejo or Algarve wine regions.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-seoul',
    title: 'Getting Around Seoul: Metro, Bus, KakaoTaxi & T-Money Guide (2025)',
    description: 'Seoul\'s Metro (9 lines, 327 stations) is one of Asia\'s best — cheap at KRW 1,400/trip, air-conditioned, and bilingual. Here\'s the complete 2025 guide.',
    publishedAt: '2025-07-25',
    readingMinutes: 5,
    category: 'travel',
    city: 'Seoul',
    country: 'South Korea',
    content: [
      { type: 'intro', body: 'Seoul\'s metropolitan subway system is one of the world\'s finest — 9 lines, 327 stations, all announcements in Korean and English, and fares starting at KRW 1,400 (~$1.05). A T-money card handles Metro, city buses, and some taxis on a single rechargeable card.' },
      { type: 'h2', heading: 'Seoul Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'Metro (single trip)', value: 'KRW 1,400–1,950 with T-money; AREX Airport Express to city: KRW 9,500 (43 min)' },
        { label: 'Bus (city)', value: 'KRW 1,400 with T-money; free transfer within 30 min when combined with Metro' },
        { label: 'KakaoTaxi (app)', value: 'Korea\'s dominant taxi app; KRW 4,800 base fare + KRW 100/131m; premium Kakao Black available' },
        { label: 'Standard metered taxi', value: 'KRW 4,800 base + KRW 100/131m; night surcharge (midnight–4am): +20%' },
        { label: 'Incheon Airport (ICN) → Gangnam/Myeongdong', value: 'AREX + Metro: KRW 9,500–11,000 | Taxi: KRW 65,000–80,000' },
        { label: 'Gimpo Airport (GMP) → city', value: 'Metro Line 5: KRW 1,400, 30 min to Yeouido' },
      ]},
      { type: 'h2', heading: 'The T-Money Card: Essential for Seoul' },
      { type: 'p', body: 'Buy a T-money card at any convenience store (GS25, CU, 7-Eleven) for KRW 3,000 (non-refundable). Top up at convenience stores or Metro station machines in multiples of KRW 1,000. Load KRW 30,000–50,000 for a week\'s transport. The card offers a KRW 100 transfer discount when combining Metro and bus within 30 minutes — essential for outlying areas. Kakao Pay and credit cards also work on newer Metro gates, but T-money is the most reliable across all transport types.' },
      { type: 'tip', body: 'Seoul\'s Metro is fastest and most reliable 6am–10pm. Kakao Taxi becomes the better option after midnight — taxis wait in queues near Hongdae, Itaewon, and Gangnam entertainment areas after clubs close. Book via KakaoTaxi app (supports English) rather than hailing on the street for confirmed pricing. Kakao T Black (premium black car) offers English-speaking drivers for airport runs.' },
      { type: 'faq', faqs: [
        { q: 'Do I need a Korean SIM card to use KakaoTaxi?', a: 'KakaoTaxi requires a Korean phone number for account registration. If you have international roaming, you can receive the verification SMS. Alternatively, buy a Korean SIM at Incheon Airport arrivals (KT, SKT, or LG U+ counters; KRW 15,000–30,000 for a week\'s data) — this unlocks all Korean apps including Kakao and Naver Maps (more accurate than Google Maps in Korea).' },
        { q: 'Is the Seoul Metro English-friendly?', a: 'Extremely — all station names are displayed in Korean, Chinese, and English (with romanisation). Platform announcements are in Korean and English. Free WiFi operates throughout the system. The Metro app (Seoul Metro, KakaoMetro) provides real-time arrival information and route planning in English.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-kuala-lumpur',
    title: 'Kuala Lumpur Daily Budget: How Much Does KL Cost Per Day? (2025)',
    description: 'Kuala Lumpur costs MYR 80–130 ($17–28) per day on a budget, MYR 200–350 mid-range, and MYR 600+ for luxury. Here\'s the full 2025 spending guide.',
    publishedAt: '2025-07-28',
    readingMinutes: 5,
    category: 'travel',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    content: [
      { type: 'intro', body: 'Kuala Lumpur is one of Asia\'s best-value major cities — exceptional Malaysian food for MYR 5–15 ($1–3.20), world-class attractions like the Petronas Towers for MYR 89 ($19), and budget accommodation from MYR 35/night in Bukit Bintang. The city is clean, safe, and English-speaking throughout.' },
      { type: 'h2', heading: 'Kuala Lumpur Daily Budget Breakdown (2025)' },
      { type: 'table', rows: [
        { label: 'Budget (MYR 80–130 / $17–28/day)', value: 'Guesthouse MYR 35–60, hawker stall meals MYR 5–10, MRT MYR 1.20–3.50/trip' },
        { label: 'Mid-range (MYR 200–350 / $43–75/day)', value: '3-star hotel MYR 100–180, restaurant meals MYR 20–45, Petronas Towers + KLCC park' },
        { label: 'Luxury (MYR 600+ / $130+/day)', value: 'Mandarin Oriental / Four Seasons MYR 400–700+, fine dining MYR 100–200pp' },
      ]},
      { type: 'h2', heading: 'KL\'s Best Budget Food' },
      { type: 'ul', items: [
        '**Jalan Alor Night Market**: Street food strip in Bukit Bintang — satay MYR 1/stick, char kway teow MYR 8–12, grilled seafood MYR 15–25; open from 6pm',
        '**Petaling Street (Chinatown)**: Wonton noodles MYR 6–9, teh tarik (pulled milk tea) MYR 2–3, fruit stalls with seasonal tropical fruit',
        '**Brickfields (Little India)**: Banana leaf rice MYR 8–14 (unlimited curry refills), roti canai breakfast MYR 2–4, teh tarik at old-school kopitiams',
        '**KLCC Suria Mall Food Court**: Affordable Malaysian, Chinese, Indian, and Western food in an air-conditioned setting — useful for midday escape from heat',
        '**GoKL Free Bus**: The red, green, purple, and blue routes cover the city centre for free — the single best budget transport decision in KL',
      ]},
      { type: 'tip', body: 'Kuala Lumpur has an excellent value airport connection: the KLIA Ekspres train from KLIA to KL Sentral takes 28 minutes and costs MYR 55 ($12). The express bus is cheaper (MYR 12–18) but takes 45–70 minutes. Grab from KLIA to the city centre typically costs MYR 80–120 — much more than the train but sometimes comparable to the bus for door-to-door convenience.' },
      { type: 'faq', faqs: [
        { q: 'Is KL safe for tourists?', a: 'Yes — Kuala Lumpur is one of Southeast Asia\'s safer capitals. Petty theft in crowded areas (Petaling Street, LRT stations) is the main concern; violent crime targeting tourists is rare. The main transport caveat: use Grab rather than street-hailed taxis, which have a history of meter refusal and overcharging in KL.' },
        { q: 'Is alcohol expensive in KL?', a: 'Malaysia has a significant alcohol tax — a beer at a restaurant or café runs MYR 18–30 ($4–6.50). Bars and rooftop lounges charge MYR 30–55 per drink. If this is a concern, Singapore (expensive but no excess tax) or Thailand (cheaper) offer better value for alcohol-inclusive holidays. Muslim-owned restaurants (marked Halal) don\'t serve alcohol at all.' },
      ]},
    ],
  },
  {
    slug: 'uber-vs-taxi-amsterdam',
    title: 'Uber vs Taxi in Amsterdam: Bolt, TCA Cab & Which to Use (2025)',
    description: 'In Amsterdam, Bolt is generally cheaper and more convenient than metered taxis. Uber also operates. Here\'s the full comparison including typical fares.',
    publishedAt: '2025-07-31',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Amsterdam',
    country: 'Netherlands',
    content: [
      { type: 'intro', body: 'Amsterdam taxi pricing is deregulated — metered taxis set their own rates within regulated caps. Bolt and Uber both operate and are typically 15–25% cheaper than metered cabs for the same journey. For most city trips, a bike or the GVB tram is still the better option.' },
      { type: 'h2', heading: 'Amsterdam Taxi Options Compared (2025)' },
      { type: 'table', rows: [
        { label: 'TCA / Taxi Centrale (metered)', value: '€3.19 flag fall + €2.17/km; reputable; bookable via app or phone' },
        { label: 'Bolt', value: 'Upfront price; typically €2–5 cheaper than TCA on same route; widely used' },
        { label: 'Uber', value: 'Available; similar pricing to Bolt; slightly fewer drivers than Bolt in Amsterdam' },
        { label: 'Schiphol Airport → city centre', value: 'Taxi/Uber: €40–60; Train: €4.50 (17 min) — always take the train' },
        { label: 'City centre → Vondelpark', value: 'Bolt: €8–14; tram: €2.00; bike: free if rented' },
        { label: 'Night surcharge', value: 'After midnight: +20% on most metered routes; Bolt/Uber usually upfront-priced' },
      ]},
      { type: 'h2', heading: 'When a Taxi Makes Sense in Amsterdam' },
      { type: 'p', body: 'Amsterdam is compact and has excellent public transport — taxis are rarely necessary for most tourist journeys. Cases where a taxi/Bolt is genuinely useful: arriving late at night with luggage when trams have reduced frequency; travelling to outer areas not well-served by tram (Amsterdam North before the Metro extension, Sloterdijk, Amsterdam Zuidoost); group travel where splitting a Bolt is cheaper per person than multiple tram tickets.' },
      { type: 'tip', body: 'Amsterdam\'s taxis have had a well-documented tourist-overcharging problem, particularly at Schiphol and Centraal Station. Bolt and Uber eliminate this risk with upfront pricing. If you do use a metered taxi, check that the taximeter is running from the moment you depart — not before — and that it shows a reasonable starting rate of €3–4.' },
      { type: 'faq', faqs: [
        { q: 'Is Uber Black available in Amsterdam?', a: 'Yes — Uber Black (premium cars with professional drivers) operates in Amsterdam alongside standard UberX. For airport runs or business travel, Uber Black offers a guaranteed standard vehicle. Standard Bolt or UberX is adequate for most tourist journeys.' },
        { q: 'What time do Amsterdam trams stop running?', a: 'GVB trams run roughly 6am to 12:30am, then are replaced by night buses (N-lines) running every 30–60 minutes on key routes. The night bus network is less comprehensive than daytime trams — for late-night returns to outlying hotels (e.g. near RAI, Amstel, or Airport Shuttle connections), pre-book a Bolt.' },
      ]},
    ],
  },
  {
    slug: 'is-marrakech-safe',
    title: 'Is Marrakech Safe for Tourists? Honest Safety Guide (2025)',
    description: 'Marrakech is safe for tourists with awareness — the Medina souks can feel overwhelming, but violent crime is rare. Here\'s what actually requires caution.',
    publishedAt: '2025-08-03',
    readingMinutes: 5,
    category: 'travel',
    city: 'Marrakech',
    country: 'Morocco',
    content: [
      { type: 'intro', body: 'Marrakech is generally safe for tourists — violent crime targeting visitors is rare and Morocco has a strong police presence in tourist areas. The real challenges are aggressive touts, fake guides, commission-driven scams, and disorientation in the Medina\'s labyrinthine lanes. Being scam-aware rather than crime-wary is the right mindset.' },
      { type: 'h2', heading: 'Marrakech Safety Overview (2025)' },
      { type: 'table', rows: [
        { label: 'Violent crime', value: 'Low — Marrakech has a good record; tourist police (Brigade Touristique) patrol the Medina' },
        { label: 'Fake guide scams', value: 'Common — men offer to "show you the tanneries" and lead you into a carpet shop for commission; decline firmly' },
        { label: 'Price inflation (tourist tax)', value: 'Ubiquitous — taxis, market stalls, and cafés charge 3–5× local prices; always negotiate' },
        { label: 'Henna "gift" scam', value: 'Women offer henna without agreeing a price, then demand €20–50 after; only engage if you agree price first' },
        { label: 'Getting lost in the Medina', value: 'Easy to do — carry offline maps (Maps.me) or drop a GPS pin at your riad before exploring' },
        { label: 'Solo female safety', value: 'Possible but requires more vigilance than male travel; choose a riad in the Medina not a budget guesthouse in outer areas' },
      ]},
      { type: 'h2', heading: 'Practical Safety Tips for Marrakech' },
      { type: 'ul', items: [
        'Download Maps.me and save your riad\'s location before entering the Medina — internet can be spotty in the lanes',
        'Use Careem or inDriver for taxis — metered taxis in Marrakech often refuse the meter; negotiate before entering and always agree a price',
        'Say "la shukran" (no thank you) firmly to touts — sustained eye contact and engagement only prolongs the interaction',
        'Djemaa el-Fna square at night: keep phones and cameras close, avoid the "friendly" man with a monkey who will charge for a photo',
        'Dress modestly: covered shoulders and knees (especially women) reduces unwanted attention in residential Medina areas',
      ]},
      { type: 'tip', body: 'The Brigade Touristique (tourist police) is present throughout the Medina and genuinely helpful — they are there specifically to assist foreign visitors. If you feel harassed or unsafe, walk into any shop, hotel, or police post. Moroccan locals are generally hospitable and will help if approached respectfully.' },
      { type: 'faq', faqs: [
        { q: 'Is Marrakech safe for solo female travellers?', a: 'Manageable with preparation — verbal harassment is more common than in Western Europe, particularly in less-touristed areas of the Medina. Stay in a well-reviewed riad, dress conservatively (headscarf not required but modest clothing respected), use Careem for transport, and consider joining day tours rather than solo exploring outer areas. The Medina\'s tourist core (around Djemaa el-Fna) is well-policed and visited by thousands of solo women daily.' },
        { q: 'Is it safe to eat street food in Marrakech?', a: 'Yes — Djemaa el-Fna food stalls are a highlight, though choose busy stalls with high turnover. Merguez sausages, harira soup, and snail broth are classics. Avoid stalls that seem stagnant or poorly maintained. Bottled water is essential; do not drink tap water.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-hanoi',
    title: 'How Much Does a Taxi Cost in Hanoi? (2025 Fare Guide)',
    description: 'Hanoi taxis start at VND 12,000–15,000 and cost VND 11,000–16,000/km. Noi Bai Airport to the Old Quarter costs VND 350,000–450,000 (~$14–18). Grab is the safest option.',
    publishedAt: '2025-08-06',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Hanoi',
    country: 'Vietnam',
    content: [
      { type: 'intro', body: 'Hanoi taxis: flag fall VND 12,000–15,000 (~$0.50–0.60), then VND 11,000–16,000/km (~$0.45–0.65/km). A typical Old Quarter trip costs VND 40,000–100,000 ($1.60–4). Grab is strongly recommended over street-hailed cabs — it offers fixed pricing, route tracking, and eliminates meter manipulation.' },
      { type: 'h2', heading: 'Hanoi Taxi Fares (2025)' },
      { type: 'table', rows: [
        { label: 'Noi Bai Airport → Old Quarter', value: 'VND 350,000–450,000 (~$14–18) via Grab; metered cab VND 400,000–500,000' },
        { label: 'Hoan Kiem Lake → Temple of Literature', value: 'VND 35,000–60,000 (~$1.40–2.40) via Grab' },
        { label: 'Old Quarter → Ho Chi Minh Mausoleum', value: 'VND 45,000–80,000 (~$1.80–3.20) via Grab' },
        { label: 'Grab Car (GrabCar)', value: 'Fixed price shown before booking — eliminates all overcharging risk' },
        { label: 'Grab Bike (GrabBike)', value: 'VND 12,000–20,000 for short trips; fastest in traffic' },
        { label: 'Be (local Vietnamese app)', value: 'Alternative to Grab; sometimes 10–15% cheaper; reliable' },
      ]},
      { type: 'h2', heading: 'Taxi Safety in Hanoi' },
      { type: 'p', body: 'Hanoi has a well-documented problem with meter rigging — some taxis have "turbo meters" that run 5–10× faster than the legal rate. The safest metered companies are Taxi Group (yellow) and Mai Linh (green) — recognisable brands with regulated meters. However, even these can be faked by copy-cat vehicles. The safest approach for all journeys: use Grab or Be. At Noi Bai Airport, book Grab from the arrivals hall before exiting — the taxi mafia operates near exit doors offering rides at inflated rates.' },
      { type: 'tip', body: 'Xe om (traditional motorbike taxis) are offered throughout Hanoi — negotiate the price firmly before getting on (VND 20,000–50,000 for short trips). Grab Bike is the app-based, safer, pre-priced version. For luggage or longer distances, GrabCar is the reliable choice. The Hanoi Old Quarter is best explored on foot — it\'s only 1km across.' },
      { type: 'faq', faqs: [
        { q: 'Is there a direct bus from Noi Bai Airport to Hanoi city?', a: 'Yes — Bus 86 runs from Noi Bai Airport to Long Bien Bus Station (passing through Hanoi Old Quarter area) for VND 45,000 (~$1.80), taking 45–60 minutes. Bus 07 runs to Hanoi Old Quarter more directly. Both are air-conditioned and perfectly safe. The bus is significantly cheaper than any taxi option but requires more navigation confidence.' },
        { q: 'How much should I tip taxi drivers in Hanoi?', a: 'Tipping is not expected in Vietnam for taxi drivers. For Grab and Be rides, the app fare is the final amount — no tip prompt. If a metered driver has been particularly helpful (helped with luggage, waited patiently, spoke English well), rounding up VND 10,000–20,000 is a kind gesture.' },
      ]},
    ],
  },
  {
    slug: 'best-time-to-visit-vietnam',
    title: 'Best Time to Visit Vietnam: North, Central & South Season Guide (2025)',
    description: 'Vietnam\'s best months depend on which region you\'re visiting. February to April suits the whole country; November to January is best for the south. Here\'s the full guide.',
    publishedAt: '2025-08-09',
    readingMinutes: 5,
    category: 'travel',
    country: 'Vietnam',
    content: [
      { type: 'intro', body: 'Vietnam spans 1,650km with dramatically different climates by region. February to April is the closest thing to a universally good time — the north is dry and warming, the centre is post-typhoon, and the south is at its most comfortable. Plan by region rather than by country for the best experience.' },
      { type: 'h2', heading: 'Vietnam Climate by Region' },
      { type: 'table', rows: [
        { label: 'North (Hanoi, Ha Long Bay, Sapa)', value: 'Best: Oct–Apr (dry, cooler 15–25°C). Avoid: Jun–Sep (typhoon risk, heavy rain in Sapa)' },
        { label: 'Central (Hoi An, Da Nang, Hue)', value: 'Best: Feb–Aug (dry, 25–35°C, beach weather). Avoid: Oct–Nov (severe flooding in Hoi An annually)' },
        { label: 'South (HCMC, Mekong Delta, Phu Quoc)', value: 'Best: Nov–Apr (dry season, 28–34°C). Avoid: May–Oct (heavy afternoon rain, Mekong flooding)' },
        { label: 'Vietnamese New Year (Tết)', value: '3–7 days in late Jan/Feb (exact date varies) — many restaurants close; book transport months ahead' },
      ]},
      { type: 'h2', heading: 'Best Month by Travel Goal' },
      { type: 'ul', items: [
        '**Ha Long Bay cruise**: October–April for calm seas and clear skies; June–August has frequent rain and sea mist',
        '**Sapa rice terraces**: September–October for post-harvest golden fields; May–June for terraced water reflections',
        '**Hoi An Ancient Town**: February–May for dry weather and the Lantern Festival full moon events',
        '**Hoi An flooding**: The town floods to knee-depth annually in October–November — some visitors find this atmospheric; most prefer to avoid it',
        '**Phu Quoc Island**: November–April for clear water, calm seas, excellent snorkelling and diving',
        '**Ho Chi Minh City**: All-year destination; Nov–Apr is drier and most comfortable for walking',
      ]},
      { type: 'tip', body: 'Tết (Vietnamese New Year) falls in late January or February (2026 Tết is February 17). The week before and after Tết sees mass domestic travel — train and bus tickets sell out months ahead, and many family restaurants close. If visiting during Tết, book all transport well in advance and embrace the temple visits and street celebrations. It\'s one of Southeast Asia\'s great cultural events.' },
      { type: 'faq', faqs: [
        { q: 'Is Vietnam good for beach holidays?', a: 'Excellent — but time your visit carefully. Da Nang and Hoi An beaches (My Khe, An Bang) are best March–August; Phu Quoc November–April; Mui Ne October–January. Nha Trang has the widest dry-season window (Jan–Sep) but has become overdeveloped. The Con Dao Islands (May–Oct) are the country\'s most pristine and difficult-to-reach beaches.' },
        { q: 'Is Vietnam expensive for Western tourists?', a: 'No — Vietnam is excellent value. A comfortable guesthouse runs $15–30/night, a pho breakfast $1.50–2.50, a Grab car trip $1.50–4. Budget travellers can live very well for $30–40/day. Mid-range travellers spending $80–120/day enjoy boutique hotels, excellent restaurants, and cooking classes. Vietnam\'s quality-to-price ratio is among the best in Asia.' },
      ]},
    ],
  },
  {
    slug: 'tipping-on-cruises',
    title: 'Cruise Ship Tipping Guide: Auto-Gratuities, Who Gets What & How Much (2025)',
    description: 'Most cruise lines add $16–20 per person per day in automatic gratuities. Here\'s exactly where it goes, when to tip extra, and which lines include tips already.',
    publishedAt: '2025-08-12',
    readingMinutes: 5,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'Cruise ship tipping is structured differently from land-based travel — most major lines add automatic daily gratuities ($16–20/day per person) that are shared among cabin stewards, dining staff, and behind-the-scenes crew. Understanding what\'s included, who benefits, and when extra tipping is appropriate saves confusion and ensures the right people are recognised.' },
      { type: 'h2', heading: 'Cruise Line Auto-Gratuity Rates (2025)' },
      { type: 'table', rows: [
        { label: 'Royal Caribbean', value: '$18.50/day per person (standard); $21/day (suites)' },
        { label: 'Carnival Cruise Line', value: '$16/day (standard); $18/day (premium cabins)' },
        { label: 'Norwegian Cruise Line (NCL)', value: '$20/day; can be prepaid at booking' },
        { label: 'Princess Cruises', value: '$16/day (standard); $17/day (mini-suites); $18/day (suites)' },
        { label: 'MSC Cruises', value: '€10–14/day depending on itinerary and cabin type' },
        { label: 'Viking, Silversea, Regent', value: 'All-inclusive — gratuities included in cruise price; no daily add-on' },
        { label: 'Virgin Voyages', value: 'Gratuities included; bars do not add auto-service charge' },
      ]},
      { type: 'h2', heading: 'Beyond the Auto-Gratuity: When to Tip Extra' },
      { type: 'ul', items: [
        '**Cabin steward**: $5–10 cash mid-cruise + $10–20 on final night for exceptional service (turning down rooms twice daily, special requests, cabin decorations for birthdays)',
        '**Favourite dining room server**: $5–10 cash on final night if you had a consistent waiter across multiple meals',
        '**Bar staff**: 15–18% is usually auto-added to each drink order; extra tip for exceptional service at your favourite bar',
        '**Spa / salon**: 18–20% usually added automatically; extra $5–10 for outstanding treatments',
        '**Shore excursion guides**: Tip as per destination norms (see Hootling\'s country tipping guide) — the ship\'s excursion price does not include guide tips',
        '**Room service**: $2–3 tip even when the service includes delivery — crew member made the delivery',
      ]},
      { type: 'tip', body: 'You can remove or reduce auto-gratuities at guest services on most ships — but consider carefully before doing so. The auto-gratuity pools often include engine room crew, kitchen staff, and laundry workers who are invisible to passengers but critical to the ship\'s operation. If you experienced poor service from a specific staff member, speak to their supervisor rather than removing the entire pool gratuity.' },
      { type: 'faq', faqs: [
        { q: 'Should I prepay cruise gratuities?', a: 'Prepaying gratuities at booking locks in the current rate (some lines increase rates annually) and simplifies your onboard account. It\'s generally recommended for budget-conscious travellers who want predictable costs. The gratuity amount is the same whether prepaid or added daily — it\'s purely a cash-flow preference.' },
        { q: 'Do cruise staff get to keep their tips?', a: 'The auto-gratuity system pools tips and distributes them across all hotel department staff according to a formula set by the cruise line. Cash tips given directly to specific crew members may or may not need to be pooled depending on the line\'s policy — on some lines, cash is theirs to keep; on others, it must be declared and added to the pool. Your favourite server will know their line\'s policy.' },
        { q: 'What currencies can I use for cruise tips?', a: 'US dollars are accepted as tips on virtually all international cruise lines. For European and Australian itineraries, the relevant local currency (euros, AUD) is also appropriate. Large denomination bills ($50, $100) are harder for crew to use — bring small bills ($5, $10, $20) for direct cash tips.' },
      ]},
    ],
  },
]
