import type { BlogPost } from './blog-posts'

export const BATCH3D_BLOG_POSTS: BlogPost[] = [
  {
    slug: 'best-time-to-visit-mexico-city',
    title: 'Best Time to Visit Mexico City: CDMX Season Guide (2025)',
    description: 'The best time to visit Mexico City is March to May — dry, warm at 18–26°C, and jacaranda trees in bloom. Here\'s what each season brings.',
    publishedAt: '2025-07-17',
    readingMinutes: 4,
    category: 'travel',
    city: 'Mexico City',
    country: 'Mexico',
    content: [
      { type: 'intro', body: 'Mexico City\'s best months are March to May — the dry season peaks here, temperatures sit at a comfortable 18–26°C, and the city\'s wide boulevards are lined with blooming jacaranda trees. At 2,240m altitude, CDMX never gets oppressively hot even in summer.' },
      { type: 'h2', heading: 'Mexico City Season by Season' },
      { type: 'table', rows: [
        { label: 'Mar–May (Dry, best)', value: '18–26°C, clear skies, jacaranda blooms in Feb–Mar, ideal for walking and outdoor markets' },
        { label: 'Jun–Sep (Rainy)', value: '16–24°C, afternoon downpours (short, intense), cooler temps, lush greenery' },
        { label: 'Oct–Nov (Shoulder)', value: '15–22°C, Day of the Dead (Nov 1–2) is extraordinary — book months ahead' },
        { label: 'Dec–Feb (Cool dry)', value: '8–20°C, Christmas posadas and markets, quieter, cheaper flights' },
      ]},
      { type: 'h2', heading: 'Events That Define Mexico City' },
      { type: 'ul', items: [
        '**Día de Muertos (Nov 1–2)**: The Gran Procesión de las Catrinas through Reforma is spectacular — altars, marigolds, face paint, and genuine reverence; book accommodation 3+ months ahead',
        '**Vive Latino (Mar)**: Latin America\'s premier music festival in Foro Sol — 2–3 days, 100+ acts',
        '**Festival del Centro Histórico (Apr)**: Free and ticketed concerts, theatre, and art in the historic centre',
        '**Independencia (Sep 15–16)**: El Grito de Independencia in the Zócalo — President shouts from the balcony at 11pm to 100,000+ people',
      ]},
      { type: 'tip', body: 'Altitude sickness (soroche) affects roughly 1 in 4 visitors arriving at 2,240m. Rest for your first 24 hours, avoid alcohol, drink extra water, and keep paracetamol handy. Most people acclimatise by day two. If symptoms persist, pharmacies stock acetazolamide (Diamox) over the counter.' },
      { type: 'faq', faqs: [
        { q: 'Is Mexico City safe for tourists in 2025?', a: 'Tourist neighbourhoods — Roma Norte, Condesa, Polanco, Coyoacán, Xochimilco, and the historic centre — are generally safe during daylight and early evenings with normal precautions. Avoid isolated streets at night, use Uber or DiDi rather than street taxis, and keep valuables discreet. CDMX has improved significantly in tourist areas over the past five years.' },
        { q: 'How many days do you need in Mexico City?', a: 'Four to five days covers the essentials: Zócalo and historic centre, Teotihuacán pyramids day trip, Coyoacán and Frida Kahlo Museum, Chapultepec Park and castle, Mercado de Jamaica, and a Lucha Libre evening. A week allows Xochimilco floating gardens and deeper neighbourhood exploration.' },
      ]},
    ],
  },
  {
    slug: 'best-time-to-visit-greece',
    title: 'Best Time to Visit Greece: Islands, Athens & the Perfect Season (2025)',
    description: 'The best time to visit Greece is May–June or September–October — warm sea, fewer crowds than July–August, and 25–30°C temperatures. Here\'s the full guide.',
    publishedAt: '2025-07-20',
    readingMinutes: 5,
    category: 'travel',
    country: 'Greece',
    content: [
      { type: 'intro', body: 'Greece is best visited in May–June or September–October: the Aegean is warm enough to swim (22–25°C), crowds are manageable, accommodation prices are 30–50% lower than peak, and the light is extraordinary. July–August brings 35–40°C heat, Santorini and Mykonos at gridlock capacity, and double the prices.' },
      { type: 'h2', heading: 'Greece Season by Season' },
      { type: 'table', rows: [
        { label: 'Apr–May (Spring, best)', value: '20–26°C, wildflowers, fewer tourists, ferries all running, Easter (huge if dates align)' },
        { label: 'Jun (Early summer)', value: '25–30°C, sea warm, busy but not peak, great balance of weather and manageable crowds' },
        { label: 'Jul–Aug (Peak)', value: '33–40°C, Santorini/Mykonos impossibly crowded, prices double, ferry seats scarce' },
        { label: 'Sep–Oct (Sweet spot)', value: '24–30°C, sea still 24°C, summer crowds gone, harvest festivals, photographers\' favourite light' },
        { label: 'Nov–Mar (Off-season)', value: '8–15°C, many island businesses closed, ferries reduced; Athens and Crete year-round viable' },
      ]},
      { type: 'h2', heading: 'Which Island for Which Traveller' },
      { type: 'ul', items: [
        '**Santorini**: Most iconic (caldera views, blue domes) — overwhelming in August; May or October is transformative',
        '**Mykonos**: Best beach clubs and nightlife — perfect in June, chaotic in August',
        '**Crete**: Largest island, viable year-round; best Apr–Jun and Sep–Oct; Samaria Gorge hike (May–Oct)',
        '**Rhodes**: Medieval old town, reliably sunny May–Oct; one of Greece\'s warmest islands',
        '**Corfu**: Lush and green (rare for Greece); best May–Jun before summer heat peaks',
        '**Naxos**: Best family island — longest beaches, best local food, less crowded than Santorini/Mykonos',
      ]},
      { type: 'tip', body: 'Greek Easter (date varies — often different from Western Easter) is the country\'s most important celebration. Midnight resurrection services with candles, fireworks, and lamb on the spit the next day — experiencing it on a small island or in a mountain village is genuinely memorable. Book accommodation a full year ahead if targeting Greek Easter.' },
      { type: 'faq', faqs: [
        { q: 'Is it worth visiting Athens in summer?', a: 'Yes — the Acropolis and major sites are open year-round. In July–August, visit the Acropolis before 8am or after 6pm to avoid the worst heat and crowds. Athens is cheaper than the islands and has world-class museums (National Archaeological Museum, Acropolis Museum) that are cooler indoors.' },
        { q: 'Do I need to book ferries in advance for the Greek islands?', a: 'For July–August: yes, 2–4 weeks ahead for cabin berths and vehicle transport. For May–June and September–October: less critical but still advisable for popular routes (Piraeus–Santorini, Piraeus–Mykonos). Ferryhopper and Ferry Scoot are reliable booking platforms. Hydrofoils (faster) book out before standard ferries.' },
      ]},
    ],
  },
  {
    slug: 'best-time-to-visit-amsterdam',
    title: 'Best Time to Visit Amsterdam: Tulips, Canals & Finding Good Weather (2025)',
    description: 'The best time to visit Amsterdam is April–May for tulip season or June–August for warmest weather. Here\'s what each season brings to the Dutch capital.',
    publishedAt: '2025-07-23',
    readingMinutes: 4,
    category: 'travel',
    city: 'Amsterdam',
    country: 'Netherlands',
    content: [
      { type: 'intro', body: 'Amsterdam\'s iconic tulip season (April–May) draws visitors for the Keukenhof Gardens and canal-side bloom displays — this is the city at its most photogenic. June–August brings the warmest temperatures (20–25°C) and longest days. Winter is cold and grey but cosy, with the fewest crowds and lowest prices.' },
      { type: 'h2', heading: 'Amsterdam Month by Month' },
      { type: 'table', rows: [
        { label: 'Apr–May (Tulip season)', value: '12–18°C, Keukenhof in full bloom, King\'s Day (Apr 27) city-wide party, busy but brilliant' },
        { label: 'Jun–Aug (Summer)', value: '20–25°C, terraces packed, canal swimming, outdoor festivals, longest daylight' },
        { label: 'Sep–Oct (Autumn)', value: '12–18°C, fewer crowds, Amsterdam Dance Event (Oct), golden canal light' },
        { label: 'Nov–Mar (Winter)', value: '2–8°C, Amsterdam Light Festival (Nov–Jan), ice skating if canals freeze, lowest prices' },
      ]},
      { type: 'h2', heading: 'Key Amsterdam Events' },
      { type: 'ul', items: [
        '**King\'s Day (Apr 27)**: The entire city turns orange — 700,000+ people fill the streets, canals, and parks for the world\'s biggest flea market and party; exceptional experience, chaotic to navigate',
        '**Keukenhof (Mar–May)**: 7 million bulbs in bloom at the world\'s largest flower garden, 45 min from Amsterdam — pre-book; closes in mid-May',
        '**Amsterdam Dance Event (Oct)**: World\'s largest electronic music conference and festival — 400,000 attendees, 1,000 events across 200 venues',
        '**Amsterdam Light Festival (Nov–Jan)**: Free and boat-tour light art installations throughout the canals — magical in December',
      ]},
      { type: 'tip', body: 'Amsterdam\'s most annoying time to visit is August school holiday weeks — canals clogged with tourist boats, Rijksmuseum queues long even with booking, rental bikes unavailable. Late June and early September offer nearly identical weather with 30–40% fewer visitors.' },
      { type: 'faq', faqs: [
        { q: 'Is Amsterdam worth visiting in winter?', a: 'Yes — the city\'s museums (Rijksmuseum, Van Gogh Museum, Anne Frank House) are magnificent year-round and less crowded in winter. The Amsterdam Light Festival (Nov–Jan) adds a unique winter spectacle. Accommodation is cheapest December–February. Downside: canals lose their summer terrace culture and the grey skies are relentless.' },
        { q: 'How far is Keukenhof from Amsterdam?', a: 'About 35km — roughly 45 minutes by bus (Connexxion direct service from Amsterdam Schiphol or Amsterdam Sloterdijk station, €17.50 return including entry). Open only mid-March to mid-May. Book tickets in advance online; same-day entry is often sold out in peak weeks.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-ho-chi-minh-city',
    title: 'Ho Chi Minh City Daily Budget: How Much Does HCMC Cost Per Day? (2025)',
    description: 'Ho Chi Minh City costs $18–30/day on a budget, $50–80 mid-range, and $200+ for luxury. It\'s one of Southeast Asia\'s best-value destinations in 2025.',
    publishedAt: '2025-07-26',
    readingMinutes: 4,
    category: 'travel',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    content: [
      { type: 'intro', body: 'Ho Chi Minh City (Saigon) is exceptional value — a budget traveller can eat, drink, and get around on $25/day. A pho bo from a street cart costs VND 40,000 (~$1.60); a Grab bike across the city costs VND 20,000 (~$0.80); a beer at a backpacker bar on Bui Vien costs VND 15,000 (~$0.60).' },
      { type: 'h2', heading: 'HCMC Daily Budget Breakdown (2025)' },
      { type: 'table', rows: [
        { label: 'Budget ($18–30/day)', value: 'Guesthouse $8–15, street food $1–3/meal, Grab bike $0.50–2, local bia hoi beer $0.50–1' },
        { label: 'Mid-range ($50–80/day)', value: '3-star hotel $25–45, sit-down restaurant $5–15, Grab Car $2–5, rooftop bar' },
        { label: 'Luxury ($200+/day)', value: 'Boutique hotel $80–150, Cục Gạch restaurant $20–50pp, spa, private car' },
      ]},
      { type: 'h2', heading: 'Where to Spend and Where to Save' },
      { type: 'ul', items: [
        '**Save**: Street food — banh mi ($0.80–1.50), banh xeo (sizzling pancake, $1–2), com tam (broken rice with grilled pork, $1.50–3); these are genuinely among Vietnam\'s best dishes',
        '**Save**: Grab over taxi — Grab Bike ~$0.50–1.50 for most short trips; Grab Car $1.50–4 for longer; metered taxis cost 2–3× more',
        '**Spend**: Cu Chi Tunnels day trip ($5–12 entry + guide) — essential historical experience',
        '**Spend**: Mekong Delta day tour ($25–45) — boat through floating markets and rice paddies',
        '**Worth it**: A rooftop bar drink at Chill Sky Bar or Broma Not A Bar — $5–10 for a cocktail with the city skyline view',
      ]},
      { type: 'tip', body: 'The Vietnamese dong (VND) deals in thousands — don\'t confuse VND 100,000 (~$4) with VND 100 (~$0.004). A helpful shorthand: remove three zeros and divide by 25 to convert to USD approximately. So VND 50,000 = $2. Carry small notes (VND 10,000–50,000) for street food vendors.' },
      { type: 'faq', faqs: [
        { q: 'Is HCMC cheaper than Bangkok?', a: 'Comparable — both are excellent budget destinations. Street food in HCMC is marginally cheaper than Bangkok. Accommodation is similar. Bangkok has a better-developed backpacker party scene on Khao San Road; HCMC\'s Bui Vien Street is lively but smaller. Both are exceptional value versus any Western city.' },
        { q: 'What is the best neighbourhood to stay in HCMC?', a: 'District 1 (Ben Thanh area) for central access to major sights; District 3 for a more local feel with great street food; Binh Thanh for budget guesthouses. Avoid staying in District 7 (Phu My Hung) unless you prefer a sterile expat suburb with no atmosphere.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-cairo',
    title: 'Cairo Daily Budget: How Much Does Cairo Cost Per Day? (2025)',
    description: 'Cairo costs $25–40/day on a budget, $70–110 mid-range. With Egypt\'s recent currency changes, it\'s one of the best-value destinations for USD/EUR holders in 2025.',
    publishedAt: '2025-07-29',
    readingMinutes: 4,
    category: 'travel',
    city: 'Cairo',
    country: 'Egypt',
    content: [
      { type: 'intro', body: 'Cairo is outstanding value for USD and EUR holders following the Egyptian pound\'s significant devaluation. Entrance to the Giza pyramids costs EGP 450 (~$9); a full meal at a local restaurant runs EGP 80–200 (~$1.60–4); and an air-conditioned Metro ride costs EGP 7–10 ($0.14–0.20). Mid-range comfort is achievable for $70/day.' },
      { type: 'h2', heading: 'Cairo Daily Budget Breakdown (2025)' },
      { type: 'table', rows: [
        { label: 'Budget ($25–40/day)', value: 'Guesthouse $10–18, fuul/ta\'ameya street food $1–3, Metro EGP 7–10' },
        { label: 'Mid-range ($70–110/day)', value: '3-star hotel $35–65, restaurant meals EGP 400–1,000 ($8–20), Uber/Careem for transport' },
        { label: 'Luxury ($250+/day)', value: 'Nile view 5-star $120–250+, fine dining $30–60pp, private guide pyramid tours' },
      ]},
      { type: 'h2', heading: 'Essential Cairo Costs (2025)' },
      { type: 'ul', items: [
        '**Giza Plateau (pyramids)**: EGP 450 (~$9) general entry; Great Pyramid interior: EGP 700 extra (~$14); book online at egy.gov.eg',
        '**Egyptian Museum (Tahrir)**: EGP 400 (~$8) — Tutankhamun mask, Royal Mummies Room EGP 300 extra (~$6)',
        '**Grand Egyptian Museum (GEM)**: EGP 900 (~$18) — brand new, world-class, less crowded than old museum',
        '**Bakshish (tips)**: Budget $10–15/day for small tips to guards, restroom attendants, parking helpers — it\'s endemic and expected',
        '**Khan el-Khalili bazaar**: No entry fee; budget for bargained purchases; start at 30% of the opening price',
      ]},
      { type: 'tip', body: 'Cairo\'s Cairo Metro is one of Africa\'s best — just EGP 7–10 (~$0.14–0.20) per trip with air conditioning. Lines 1, 2, and 3 cover Tahrir Square, Old Cairo (Coptic churches), and connect to major transit hubs. Far faster than a taxi in Cairo\'s legendary traffic, and genuinely safe.' },
      { type: 'faq', faqs: [
        { q: 'Is Cairo safe for tourists in 2025?', a: 'The tourist areas of Cairo (Giza, Islamic Cairo, Coptic Cairo, Downtown, Khan el-Khalili) are generally safe with normal awareness. Tourist police are visible at all major sites. The main risks are persistent but non-violent hustle (guides, camel rides, souvenir sellers) and petty theft in very crowded areas. Use Uber or Careem rather than street taxis.' },
        { q: 'What currency should I use in Cairo?', a: 'Egyptian pounds (EGP) for all local transactions. USD is widely understood at tourist sites. ATMs dispense EGP at fair rates. Credit cards accepted at hotels and upmarket restaurants. Carry EGP cash for bazaars, street food, and small tips.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-buenos-aires',
    title: 'Buenos Aires Daily Budget: How Much Does BA Cost Per Day? (2025)',
    description: 'Buenos Aires costs $30–50/day on a budget using the blue-dollar rate, $80–120 mid-range. World-class steak and Malbec for a fraction of European prices.',
    publishedAt: '2025-08-01',
    readingMinutes: 4,
    category: 'travel',
    city: 'Buenos Aires',
    country: 'Argentina',
    content: [
      { type: 'intro', body: 'Buenos Aires is one of the world\'s great bargain capitals for foreign visitors — thanks to Argentina\'s persistent currency pressures, USD cash gets you far more than card transactions. A world-class parrilla (steakhouse) meal with Malbec runs $15–25; a hostel in Palermo costs $12–20/night; and the Subte (Metro) costs ARS 1,000 per trip ($0.80–1.00).' },
      { type: 'h2', heading: 'Buenos Aires Daily Budget (2025)' },
      { type: 'table', rows: [
        { label: 'Budget ($30–50/day)', value: 'Hostel ARS 12,000–20,000, medialunas + cafe ARS 1,500–3,000, Subte ARS 1,000/trip' },
        { label: 'Mid-range ($80–120/day)', value: 'B&B in Palermo $30–60, neighbourhood parrilla dinner $15–30pp including wine' },
        { label: 'Luxury ($250+/day)', value: 'Puerto Madero boutique hotel $80–180, Don Julio or La Cabrera steak dinner $40–80pp' },
      ]},
      { type: 'h2', heading: 'Where Your Money Goes in Buenos Aires' },
      { type: 'ul', items: [
        '**The steak**: Argentine beef (asado) at a neighbourhood parrilla — bife de chorizo (sirloin) ARS 8,000–20,000 ($8–20) with salad and a glass of Malbec; one of the world\'s great cheap luxury meals',
        '**Empanadas**: ARS 600–1,200 (~$0.60–1.20) each from a panadería — dinner for $3',
        '**Subte**: ARS 1,000 (~$0.80–1.00) per trip; covers all 6 lines across the city',
        '**Milonga (tango dance hall)**: ARS 3,000–8,000 ($3–8) entry including a show; neighbourhood milongas in San Telmo are cheapest and most authentic',
        '**Currency note**: Check dolarito.ar for the unofficial (blue) exchange rate before exchanging USD cash — it\'s typically 10–20% better than official bank rates',
      ]},
      { type: 'tip', body: 'Always carry USD cash in Buenos Aires and exchange it at a cueva (informal exchange house) in the financial district (Florida Street/Lavalle) or your accommodation. The blue-dollar rate consistently outperforms ATM rates and official exchange by a significant margin. USD $100 bills get the best rates; smaller denominations receive slightly less.' },
      { type: 'faq', faqs: [
        { q: 'Is Buenos Aires still cheap in 2025?', a: 'Yes — for USD, EUR, and GBP holders, Buenos Aires remains one of South America\'s best value destinations despite local inflation. Restaurant meals, taxis, accommodation, and cultural experiences are all dramatically cheaper than European equivalents. The caveat: peso inflation means any price in ARS quoted online may be outdated by the time you arrive.' },
        { q: 'What is the best neighbourhood to stay in Buenos Aires?', a: 'Palermo (especially Palermo Soho and Palermo Hollywood) is the traveller favourite — parks, designer boutiques, excellent restaurants and bars, bike-friendly. San Telmo is more characterful (tango, antiques, cobblestones) but rougher at night. Puerto Madero is expensive and sterile. Recoleta is elegant and quiet.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-mexico-city',
    title: 'Mexico City Daily Budget: How Much Does CDMX Cost Per Day? (2025)',
    description: 'Mexico City costs $35–55/day on a budget, $90–140 mid-range, and $300+ for luxury. The Metro costs MXN 7 ($0.35) — one of the world\'s best transport deals.',
    publishedAt: '2025-08-04',
    readingMinutes: 4,
    category: 'travel',
    city: 'Mexico City',
    country: 'Mexico',
    content: [
      { type: 'intro', body: 'Mexico City is an extraordinary value proposition for a world capital — world-class museums (many free), outstanding street food from $1, and the world\'s cheapest urban metro at MXN 7 ($0.35) per trip. A budget traveller can live very well on $50/day.' },
      { type: 'h2', heading: 'Mexico City Daily Budget (2025)' },
      { type: 'table', rows: [
        { label: 'Budget ($35–55/day)', value: 'Hostel $12–22, tacos al pastor MXN 15–25 each, Metro MXN 7/trip' },
        { label: 'Mid-range ($90–140/day)', value: 'Boutique hotel in Roma Norte $40–75, restaurant meals $10–25pp, Uber for longer trips' },
        { label: 'Luxury ($300+/day)', value: 'Polanco 5-star hotel $120–250, Pujol or Contramar dinner $60–120pp, private museum tours' },
      ]},
      { type: 'h2', heading: 'Mexico City\'s Best Free and Low-Cost Experiences' },
      { type: 'ul', items: [
        '**MUNAL, Bellas Artes, Anthropology Museum**: Museo Nacional de Antropología — MXN 90 ($4.50), world-class pre-Columbian collection; Bellas Artes — free exterior, murals by Rivera visible from the lobby',
        '**Chapultepec Park**: Entirely free; one of the world\'s largest urban parks with multiple free museums (Museo del Caracol, Museo de Arte Moderno)',
        '**Coyoacán neighbourhood**: Free to explore — Frida Kahlo Museum (Casa Azul) is MXN 250 ($12.50) and requires advance booking',
        '**Teotihuacán day trip**: MXN 90 (~$4.50) entry; 45 min by bus from Terminal Norte; one of the world\'s great archaeological sites',
        '**Street tacos**: Al pastor spit-roasted tacos MXN 15–25 each ($0.75–1.25) — three tacos + salsa + agua fresca = $5 meal',
      ]},
      { type: 'tip', body: 'Mexico City\'s Metro (Sistema de Transporte Colectivo) carries 4.5 million passengers daily at MXN 7 per trip — arguably the world\'s best urban transit value. Lines 1–12 cover all major tourist zones: Zócalo (Line 2), Coyoacán (Line 3, Viveros station), Roma/Condesa (Line 1, Insurgentes station). The Metro can be crowded during rush hour but is safe for tourists with normal awareness.' },
      { type: 'faq', faqs: [
        { q: 'Is Mexico City expensive compared to other Mexican destinations?', a: 'CDMX is Mexico\'s most expensive city but still dramatically cheaper than comparable global capitals. Oaxaca and Mérida are cheaper for accommodation; Cancún is more expensive for accommodation in the Hotel Zone but has similar street food costs. For cultural richness per dollar, CDMX is unmatched in Mexico.' },
        { q: 'What is the best market to visit in Mexico City?', a: 'Mercado de Jamaica (flower market) for extraordinary colour; Mercado de Medellín in Roma for everyday local shopping; Mercado de San Juan (Arcos de Belén) for gourmet international ingredients; and the Sunday Bazar del Sábado in San Ángel for artisan crafts. All are free to browse.' },
      ]},
    ],
  },
  {
    slug: 'daily-budget-guide-cape-town',
    title: 'Cape Town Daily Budget: How Much Does Cape Town Cost Per Day? (2025)',
    description: 'Cape Town costs ZAR 600–900 ($33–50) per day on a budget, ZAR 1,500–2,500 mid-range. Here\'s the full breakdown for 2025.',
    publishedAt: '2025-08-07',
    readingMinutes: 4,
    category: 'travel',
    city: 'Cape Town',
    country: 'South Africa',
    content: [
      { type: 'intro', body: 'Cape Town is affordable by European and North American standards — the South African rand gives USD and EUR holders strong purchasing power. Meals at local restaurants run ZAR 80–200 ($4.50–11), Uber rides across the city cost ZAR 60–150 ($3.50–8), and Table Mountain cable car entry is ZAR 430 ($24) return.' },
      { type: 'h2', heading: 'Cape Town Daily Budget (2025)' },
      { type: 'table', rows: [
        { label: 'Budget (ZAR 600–900 / $33–50/day)', value: 'Hostel ZAR 200–350, Woolworths Food meal ZAR 50–120, Uber for transport' },
        { label: 'Mid-range (ZAR 1,500–2,500 / $83–139/day)', value: '3-star guesthouse ZAR 700–1,200, restaurant meals ZAR 200–450, paid attractions' },
        { label: 'Luxury (ZAR 5,000+ / $280+/day)', value: 'Camps Bay boutique ZAR 2,500–5,000+, La Colombe or The Test Kitchen $60–120pp' },
      ]},
      { type: 'h2', heading: 'What Things Cost in Cape Town (2025)' },
      { type: 'ul', items: [
        '**Table Mountain cable car**: ZAR 430 ($24) return adult — book online, check weather first',
        '**Cape of Good Hope + Boulders Penguin**: ZAR 400 ($22) combined SANParks entry — day trip, best with a car or tour',
        '**Wine tasting, Stellenbosch/Franschhoek**: ZAR 100–250 ($5.50–14) per cellar door tasting — world-class Chenin Blanc and Pinotage',
        '**Township Langa food tour**: ZAR 600–900 ($33–50) with a reputable operator — excellent cultural experience',
        '**Braai (BBQ) groceries**: ZAR 200–350 ($11–19) feeds 4 people — boerewors, pap, chakalaka from a supermarket',
      ]},
      { type: 'tip', body: 'Cape Town has virtually no public transport useful to tourists — the MyCiTi bus covers limited routes and doesn\'t reach the Winelands or Cape Point. Uber is the default transport. Hiring a car (ZAR 400–700/day) unlocks the Peninsula, Chapman\'s Peak Drive, and the Winelands independently at much lower total cost than tours.' },
      { type: 'faq', faqs: [
        { q: 'Is Cape Town expensive for food?', a: 'A wide range exists. Local restaurants and cafe chains (Woolworths Food, Ocean Basket, Spur) offer excellent meals for ZAR 80–200 ($4.50–11). Fine dining at world-class restaurants (The Test Kitchen, La Colombe) runs ZAR 1,200–2,500pp ($67–139). The middle ground — good neighbourhood restaurants in Gardens, Woodstock, and Obs — offers excellent food for ZAR 180–350 ($10–19) per person.' },
        { q: 'Is it worth renting a car in Cape Town?', a: 'Yes, if you want to see beyond the immediate city. The Cape Peninsula (Cape Point, Boulders, Chapman\'s Peak), the Winelands (Stellenbosch, Franschhoek), and the Garden Route all require a car for independence. Drive on the left (South African standard). Car hire from ZAR 400–700/day from reputable operators at the airport.' },
      ]},
    ],
  },
  {
    slug: 'uber-vs-taxi-kuala-lumpur',
    title: 'Grab vs Taxi in Kuala Lumpur: Which Is Better in 2025?',
    description: 'Grab dominates Kuala Lumpur — metered taxis frequently refuse fares or overcharge tourists. Here\'s why Grab is almost always the better choice in KL.',
    publishedAt: '2025-08-10',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    content: [
      { type: 'intro', body: 'In Kuala Lumpur, Grab is overwhelmingly the better option for tourists. Metered taxis in KL have a long history of meter refusal, demanding flat tourist rates, and taking unnecessarily long routes. Grab eliminates all of this — fixed price upfront, route tracked, cashless payment.' },
      { type: 'h2', heading: 'Grab vs Metered Taxi in KL (2025)' },
      { type: 'table', rows: [
        { label: 'KLIA Airport → KLCC', value: 'Grab: MYR 80–110 ($17–23) | Taxi: MYR 90–130 negotiated ($19–28) | KLIA Ekspres: MYR 55 ($12)' },
        { label: '5km city trip (eg. KLCC → Bukit Bintang)', value: 'Grab: MYR 8–15 ($1.70–3.20) | Metered taxi: MYR 12–20 (if meter used) | Walk: 15 min' },
        { label: 'Surge pricing', value: 'Grab: applies during peak/rain — MYR 20–35 for short trips | Taxi: no surge, but meter often refused' },
        { label: 'Availability', value: 'Grab: 1–5 min wait citywide | Taxi: unreliable in suburbs and at night' },
        { label: 'Uber', value: 'Uber left Malaysia in 2018 — merged with Grab; Grab is the only major ride-hailing option' },
      ]},
      { type: 'h2', heading: 'When Taxis Are Actually Fine in KL' },
      { type: 'ul', items: [
        '**Budget Premier Taxis** (black with yellow roof): Premium metered taxis — more reliable than regular red taxis, use meters, higher minimum fare but honest',
        '**Taxi ranks at major malls**: KLCC, Pavilion, Mid Valley — queue-based system; drivers are less likely to refuse metered fares at managed ranks',
        '**Late night when Grab is surging 3×**: During peak Grab surge (weekends 1–3am), a taxi willing to use the meter can be cheaper',
      ]},
      { type: 'tip', body: 'Download Grab before arriving in Malaysia — it also works seamlessly in Singapore, Thailand, Vietnam, Philippines, and Indonesia. One app for all Southeast Asian ride-hailing. Link your credit card in advance; cash pickup is available but slower to match. GrabCar Plus (premium) is worth the extra MYR 5–10 for airport runs with luggage.' },
      { type: 'faq', faqs: [
        { q: 'Is the KL Monorail better than Grab for getting around?', a: 'For many central routes, yes. KL\'s rail network (MRT Putrajaya Line, MRT Kajang Line, LRT Kelana Jaya, Monorail) covers KLCC, Bukit Bintang, KL Sentral, and Masjid Jamek for MYR 1.20–4.00 per trip with a Touch\'n Go card. Rail is faster than Grab during peak traffic — but Grab wins for door-to-door convenience, especially with luggage.' },
        { q: 'How much does a Grab from KLIA Airport to the city cost?', a: 'MYR 80–110 ($17–23) for GrabCar to the KLCC/Bukit Bintang area. Book in the designated Grab/Taxi app zone in the arrivals hall. The KLIA Ekspres train (MYR 55, 28 minutes to KL Sentral) is faster and cheaper — highly recommended unless you have lots of luggage or a distant hotel.' },
      ]},
    ],
  },
  {
    slug: 'uber-vs-taxi-beijing',
    title: 'DiDi vs Taxi in Beijing: Which Is Better for Tourists? (2025)',
    description: 'Uber left China in 2016. DiDi is now Beijing\'s dominant ride-hailing app. Here\'s how DiDi compares to metered taxis — and how to set both up before you arrive.',
    publishedAt: '2025-08-13',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Beijing',
    country: 'China',
    content: [
      { type: 'intro', body: 'Uber exited China in 2016, selling to DiDi Chuxing. Today, Beijing tourists choose between DiDi (China\'s dominant ride-hailing app, requires WeChat Pay or Alipay), metered taxis (honest meters, but language barrier is significant), and the excellent Beijing Metro (CNY 4–10 for most trips).' },
      { type: 'h2', heading: 'DiDi vs Metered Taxi in Beijing (2025)' },
      { type: 'table', rows: [
        { label: 'Standard city trip (5km)', value: 'DiDi: CNY 20–35 ($2.75–5) | Taxi: CNY 20–35 (similar, meter honest)' },
        { label: 'PEK Airport → Sanlitun', value: 'DiDi: CNY 130–180 ($18–25) | Taxi: CNY 140–200 ($19–28) | Metro: CNY 30 ($4.10)' },
        { label: 'PKX Daxing Airport → city', value: 'DiDi: CNY 100–150 ($14–21) | Airport Express train: CNY 35 ($4.80)' },
        { label: 'Setting up', value: 'DiDi: needs WeChat/Alipay OR international credit card (added in 2019) | Taxi: cash or WeChat Pay' },
        { label: 'English language', value: 'DiDi: app partly in English, driver no English | Taxi: show address in Chinese characters' },
      ]},
      { type: 'h2', heading: 'How to Use DiDi as a Tourist' },
      { type: 'ul', items: [
        'Download DiDi app (available on App Store and Google Play outside China)',
        'Register with your foreign phone number — SMS verification works',
        'Add an international Visa/Mastercard in the payments section (supported since 2019)',
        'Set destination using English — DiDi translates automatically',
        'Confirm pickup by showing the driver your phone with the booking screen',
        'Driver will call if lost — have your hotel concierge\'s number saved to help mediate',
      ]},
      { type: 'tip', body: 'Beijing\'s metered taxis are actually very honest — CNY 13 flag fall plus CNY 2.30/km, meters always run, and drivers rarely attempt tourist fraud. The main challenge is the language barrier. Solution: screenshot your destination in Chinese characters from Google Maps before hailing a cab. Show it to the driver; problem solved.' },
      { type: 'faq', faqs: [
        { q: 'Does Uber work in China?', a: 'No — Uber sold its China operations to DiDi in 2016. The Uber app does not function in mainland China. DiDi is the equivalent and works with international credit cards. Download and set up DiDi before your flight.' },
        { q: 'Is the Beijing Metro better than DiDi for tourists?', a: 'For most tourist routes: yes. The Beijing Metro (14+ lines) covers the Forbidden City (Tiananmen East/West), Temple of Heaven (Tiantan Dongmen), Summer Palace (Beigongmen), Olympic Park (Olympic Green), and both airports. CNY 4–10 per trip with a Yikatong transit card. Faster than DiDi during rush hour and far cheaper.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-sydney',
    title: 'Getting Around Sydney: Trains, Ferries, Buses & Taxis (2025)',
    description: 'Sydney\'s Opal card covers trains, buses, ferries, and light rail for $3.61–$9.20 per trip. Here\'s everything you need to get around Australia\'s most beautiful city.',
    publishedAt: '2025-08-16',
    readingMinutes: 5,
    category: 'travel',
    city: 'Sydney',
    country: 'Australia',
    content: [
      { type: 'intro', body: 'Sydney\'s Opal card (load at any 7-Eleven or train station) covers all public transport: trains, buses, light rail, and ferries — including the Manly Ferry, one of the world\'s great harbour commutes. Tap on and tap off; daily cap of AUD $18.60 means all-day travel at a fixed maximum.' },
      { type: 'h2', heading: 'Sydney Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'Train (City network)', value: 'AUD $3.61–6.89 with Opal; Airport Line: AUD $21.80 with airport station fee' },
        { label: 'Ferry (Manly)', value: 'AUD $9.20 one-way; 30 min from Circular Quay; one of the world\'s great harbour journeys' },
        { label: 'Ferry (inner harbour)', value: 'AUD $6.83 one-way; Circular Quay → Darling Harbour, Taronga Zoo, Balmain' },
        { label: 'Bus', value: 'AUD $3.20–4.80; extensive network including Bondi beach routes (333, 380, 381)' },
        { label: 'Light Rail (CBD to Randwick)', value: 'AUD $3.20–4.80; covers CBD, Pyrmont, Moore Park, UNSW' },
        { label: 'Uber / Taxi', value: 'Uber: AUD $15–30 for most inner-city trips; metered taxi: AUD $4.20 flag fall + $2.19/km' },
      ]},
      { type: 'h2', heading: 'Key Routes for Tourists' },
      { type: 'ul', items: [
        '**Airport to CBD**: Train (Airport Link) to Central Station — AUD $21.80 including surcharge, 13 min; or Uber ~AUD $45–65 depending on traffic',
        '**Circular Quay to Bondi Beach**: Bus 333 or 380 from outside Circular Quay station — AUD $4.80, 30–40 min (more scenic than train)',
        '**CBD to Taronga Zoo**: Ferry from Circular Quay Wharf 2 — AUD $6.83, 12 min with harbour views; combine with zoo entry',
        '**Manly day trip**: Ferry from Circular Quay Wharf 3 — AUD $9.20, 30 min; walk the 10km Manly to Spit Bridge coastal track from there',
        '**Blue Mountains**: Train from Central Station to Katoomba — AUD $9.46 each way, 2 hours; one of NSW\'s best day trips',
      ]},
      { type: 'tip', body: 'The Manly Ferry (AUD $9.20) is widely considered the world\'s best-value tourist experience — a working commuter service that passes through Sydney Harbour, under the Bridge, past the Opera House, and arrives at a beach town on the Northern Beaches. Take it at golden hour for the best light on the Opera House.' },
      { type: 'faq', faqs: [
        { q: 'Do I need an Opal card in Sydney?', a: 'Contactless bank cards and phone tap-to-pay now work on all Sydney transport — you no longer need a physical Opal card. Simply tap on and tap off with your card or phone and the correct fare is charged automatically. The daily ($18.60) and weekly ($50) caps still apply to contactless payments.' },
        { q: 'How far is Sydney Airport from the city?', a: 'Sydney Airport (SYD) is 8km from the CBD — deceptively close but the train includes a hefty AUD $15.70 airport station access fee on top of the normal fare (total AUD $21.80). Uber/taxi runs AUD $35–65 depending on destination and traffic. For groups of 3–4 people, Uber becomes competitive with the train.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-mumbai',
    title: 'Getting Around Mumbai: Local Train, Metro, Auto & Taxi Guide (2025)',
    description: 'Mumbai\'s suburban rail carries 7 million passengers daily. Here\'s how to navigate the local train, Metro, auto-rickshaws, and app-based taxis in India\'s largest city.',
    publishedAt: '2025-08-19',
    readingMinutes: 5,
    category: 'travel',
    city: 'Mumbai',
    country: 'India',
    content: [
      { type: 'intro', body: 'Mumbai\'s suburban railway (the "local") is the fastest way to travel the city\'s north-south spine — but during rush hour it\'s so overcrowded that travellers with luggage or unfamiliar with the system should use Ola or Uber instead. The Metro network is expanding rapidly and provides a more comfortable alternative.' },
      { type: 'h2', heading: 'Mumbai Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'Suburban train (local)', value: 'INR 10–30/trip; 3 lines (Western, Central, Harbour); incredibly fast north-south' },
        { label: 'Mumbai Metro (expanding)', value: 'INR 10–40/trip; Aqua Line (Line 3) now connects BKC to SEEPZ; more lines opening 2025' },
        { label: 'Black & Yellow taxi (kaali-peeli)', value: 'INR 25 minimum + INR 15/km; metered, honest, iconic' },
        { label: 'Ola / Uber', value: 'INR 80–250 for most tourist trips; strongly recommended for tourists' },
        { label: 'Auto-rickshaw', value: 'Only in suburbs (not South Mumbai); INR 21 minimum + INR 13/km; meter used' },
        { label: 'BEST Bus', value: 'INR 8–20; extensive network; Google Maps routes work well' },
      ]},
      { type: 'h2', heading: 'Getting Between Tourist Highlights' },
      { type: 'ul', items: [
        '**CSMT (Victoria Terminus) → Bandra**: Local train Western Line from Churchgate — 30 min, INR 15; or Uber ~INR 350–500',
        '**Colaba → Elephanta Caves**: Ferry from Gateway of India — INR 250 return, 1 hour each way; Elephanta entry INR 600',
        '**CSIA Airport → BKC/Bandra**: Metro Aqua Line (Line 3) from Sahar station — INR 30–40, ~25 min; far cheaper than Ola (~INR 500–700)',
        '**Dharavi visit**: Local train to Mahim station, then 5-min walk or auto to Reality Tours office',
        '**Marine Drive**: Walk — the 3km "Queen\'s Necklace" promenade from Nariman Point to Chowpatty Beach is Mumbai\'s finest free attraction',
      ]},
      { type: 'tip', body: 'Rush hour on Mumbai\'s local trains (7–10am and 5–9pm) is extreme — carriages are genuinely dangerous for those unfamiliar with the system due to the force of the crowds. Travel off-peak for your first few journeys and always identify which direction (UP — towards Churchgate/CSMT, or DOWN — towards the suburbs) before boarding.' },
      { type: 'faq', faqs: [
        { q: 'Are Mumbai taxis safe?', a: 'Yes — the Black & Yellow kaali-peeli taxis are metered, regulated, and generally honest. Ola and Uber are the most convenient option for tourists as they eliminate the language barrier and have upfront pricing. Avoid unmetered taxis at the airport — use the prepaid taxi counter or book Ola/Uber in the arrivals area.' },
        { q: 'Can I use auto-rickshaws in South Mumbai?', a: 'No — auto-rickshaws are not permitted south of Mahim/Sion in the island city. They operate freely in the suburbs (Bandra, Andheri, Powai, etc.). In South Mumbai (Colaba, Fort, Nariman Point), use kaali-peeli taxis, Ola, or Uber.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-hong-kong',
    title: 'Getting Around Hong Kong: MTR, Tram, Ferry & Taxi Guide (2025)',
    description: 'Hong Kong\'s Octopus card covers the MTR, buses, ferries, trams, and mini-buses. Here\'s how to navigate one of Asia\'s most efficient transport networks in 2025.',
    publishedAt: '2025-08-22',
    readingMinutes: 4,
    category: 'travel',
    city: 'Hong Kong',
    country: 'China',
    content: [
      { type: 'intro', body: 'Hong Kong\'s public transport is a masterclass in urban mobility. The MTR (Mass Transit Railway) is fast, clean, and covers all major areas; the iconic Ding Ding (double-decker tram) costs HKD $3 flat; and the Star Ferry (HKD $3.40) is one of the world\'s great harbour crossings — all payable with a single Octopus card.' },
      { type: 'h2', heading: 'Hong Kong Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'MTR (any line)', value: 'HKD $4.60–52.60 with Octopus; Airport Express: HKD $115 (24 min from HKIA to Hong Kong station)' },
        { label: 'Star Ferry (Tsim Sha Tsui ↔ Central)', value: 'HKD $3.40 (upper deck); one of the world\'s iconic harbour crossings' },
        { label: 'Ding Ding (tram, HK Island)', value: 'HKD $3.00 flat fare; east-west along northern HK Island; slow but atmospheric' },
        { label: 'Red taxi (urban)', value: 'HKD $30 flag fall + HKD $2/200m; clean, metered, honest' },
        { label: 'Green taxi (New Territories)', value: 'HKD $25 flag fall; cheaper for NT trips' },
        { label: 'Bus (Kowloon Motor Bus)', value: 'HKD $4–55 depending on route; Octopus accepted' },
      ]},
      { type: 'h2', heading: 'Essential Octopus Card Tips' },
      { type: 'p', body: 'Buy an Octopus card (HKD $150 including HKD $100 stored value + HKD $50 refundable deposit) at the Airport Express counter on arrival or any MTR station. Top up at any 7-Eleven, Circle K, or MTR machine. The card works on all MTR lines, buses, trams, Star Ferry, mini-buses, and some taxis. At trip end, refund the HKD $50 deposit at any MTR customer service centre. The Tourist Octopus (HKD $39 for 1-day unlimited MTR) is available but rarely worth it compared to pay-per-trip pricing.' },
      { type: 'tip', body: 'The Airport Express In-Town Check-In service at Hong Kong and Kowloon stations allows you to check your bags and receive your boarding pass up to a day before departure — leaving you free to spend your last day in Hong Kong without luggage. Available for most major airlines. Included in your Airport Express ticket.' },
      { type: 'faq', faqs: [
        { q: 'Is Hong Kong a walkable city?', a: 'Very walkable in specific areas — Central, Sheung Wan, Wan Chai, Tsim Sha Tsui, and Mong Kok are all excellent on foot. The hillside Mid-Levels Escalator (world\'s longest outdoor covered escalator, free) connects Central to SoHo and Hollywood Road. However, the hills and heat (May–October) make trams and MTR preferable for longer distances.' },
        { q: 'Is it safe to take taxis in Hong Kong?', a: 'Yes — Hong Kong taxis are among Asia\'s safest and most regulated. Red (urban), green (New Territories), and blue (Lantau) taxis all use meters and receipts. Drivers are licensed and the system has extremely low fraud rates. No app-based ride-hailing (Uber) operates commercially in Hong Kong — taxis are the standard.' },
      ]},
    ],
  },
  {
    slug: 'getting-around-kuala-lumpur',
    title: 'Getting Around Kuala Lumpur: MRT, LRT, Monorail, Grab & Bus (2025)',
    description: 'Kuala Lumpur\'s rail network covers most tourist areas for MYR 1.20–7.10 per trip. Here\'s how to combine the MRT, LRT, Monorail, and Grab to navigate KL efficiently.',
    publishedAt: '2025-08-25',
    readingMinutes: 4,
    category: 'travel',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    content: [
      { type: 'intro', body: 'Kuala Lumpur\'s rail network — MRT, LRT, Monorail, and KTM commuter rail — is extensive but can be confusing with multiple operators and card systems. The key: a Touch\'n Go card (one card, all rail lines) loaded at any station, plus Grab for the gaps the rail doesn\'t cover.' },
      { type: 'h2', heading: 'KL Transport Options (2025)' },
      { type: 'table', rows: [
        { label: 'MRT Putrajaya Line', value: 'MYR 1.20–7.10 with Touch\'n Go; covers KLCC, Bukit Bintang, Chinatown (Pasar Seni)' },
        { label: 'LRT Kelana Jaya Line', value: 'MYR 1.20–6.80; Masjid Jamek, KLCC, Ampang Park' },
        { label: 'KL Monorail', value: 'MYR 1.20–3.50; Bukit Bintang, Brickfields (Little India), Titiwangsa' },
        { label: 'KLIA Ekspres', value: 'MYR 55 ($12); Kuala Lumpur Sentral ↔ KLIA Airport in 28 min — best airport option' },
        { label: 'GoKL City Bus', value: 'Free within city centre; 4 colour-coded routes covering major attractions' },
        { label: 'Grab', value: 'MYR 8–25 for most city trips; essential for areas rail doesn\'t serve' },
      ]},
      { type: 'h2', heading: 'Key Tourist Routes in KL' },
      { type: 'ul', items: [
        '**Petronas Towers**: MRT to KLCC station — towers directly above, free to walk around the base and park; observation deck MYR 89',
        '**Batu Caves**: KTM commuter rail from KL Sentral to Batu Caves station (30 min, MYR 4); 272 rainbow steps to Hindu cave temples — free entry, MYR 5 for dark cave',
        '**Chinatown (Petaling Street)**: MRT/LRT to Pasar Seni station; market stalls for watches, bags, and street food',
        '**Bukit Bintang (shopping)**: MRT to Bukit Bintang — Pavilion Mall, Fahrenheit88, Lot 10 all within walking distance',
        '**KLCC Park**: Free entry; fountains and gardens at the base of the Petronas Towers; lovely at dusk',
      ]},
      { type: 'tip', body: 'The Touch\'n Go card (MYR 10 + minimum MYR 10 credit load) is essential for KL\'s rail network. Buy at any rail station customer service counter. It\'s also accepted at highway toll booths, some parking garages, and selected retailers. Load MYR 50 for a week of rail travel plus Grab top-up via the Touch\'n Go eWallet app.' },
      { type: 'faq', faqs: [
        { q: 'Is KL easy to navigate for first-time visitors?', a: 'Moderately — the multiple rail operators (Rapid KL, KTM, Prasarana) can be confusing, but Google Maps and the MyRapid app both give accurate routing and fare estimates. The main challenge is that several key tourist sights (Perdana Botanical Garden, Royal Palace, National Museum) aren\'t directly rail-accessible and require Grab.' },
        { q: 'What is the best way to get from KL Sentral to KLCC (Petronas Towers)?', a: 'LRT Kelana Jaya Line from KL Sentral to KLCC station — MYR 3.10, 12 minutes, direct. Alternatively, MRT Putrajaya Line from Muzium Negara to Bukit Bintang then walk 800m. Grab: MYR 15–25 depending on traffic, 20–40 min. Rail is faster and cheaper for this specific route.' },
      ]},
    ],
  },
  {
    slug: 'is-johannesburg-safe',
    title: 'Is Johannesburg Safe for Tourists? Honest Guide (2025)',
    description: 'Johannesburg has real safety challenges but millions visit safely each year by staying in the right areas and following straightforward precautions. Here\'s the honest picture.',
    publishedAt: '2025-08-28',
    readingMinutes: 5,
    category: 'travel',
    city: 'Johannesburg',
    country: 'South Africa',
    content: [
      { type: 'intro', body: 'Johannesburg has one of the highest violent crime rates of any major city in the world — but the tourist areas (Sandton, Rosebank, Maboneng, Soweto with a guide, the Apartheid Museum) are managed environments visited by millions each year. The key is staying in the right areas and avoiding behaviour that increases risk.' },
      { type: 'h2', heading: 'Johannesburg Safety Overview (2025)' },
      { type: 'table', rows: [
        { label: 'Violent crime (general city)', value: 'High — Joburg has significant violent crime, particularly in the inner city and townships' },
        { label: 'Tourist zone safety', value: 'Manageable — Sandton, Rosebank, Melville, Maboneng with awareness are viable' },
        { label: 'Carjacking', value: 'Significant risk when driving — lock doors, keep windows up in traffic, avoid stopping on dark roads' },
        { label: 'Mugging risk', value: 'High if walking in wrong areas; never walk in Joburg CBD at night' },
        { label: 'Soweto tours', value: 'Very safe with reputable operator — Soweto is a community, not a war zone; excellent guided tours available' },
        { label: 'OR Tambo Airport', value: 'Safe within the airport; use pre-booked Uber or hotel shuttle — never informal taxis' },
      ]},
      { type: 'h2', heading: 'Safe vs Avoid' },
      { type: 'ul', items: [
        '**Generally safe with awareness**: Sandton (Africa\'s richest sq km), Rosebank, Melville, Parkhurst, Maboneng (daytime), OR Tambo Airport precinct',
        '**Only with a guide**: Soweto (genuinely excellent), Alexandra, the CBD/Hillbrow area',
        '**Avoid independently**: Joburg CBD at night, Park Station area after dark, anywhere that feels isolated',
        '**Essential apps**: Uber is essential — never hail on the street; bolt also works well in Joburg',
      ]},
      { type: 'tip', body: 'The Apartheid Museum (MYR 220 / ~$12 entry) is one of the most important museums in Africa and is completely safe — it\'s in a managed precinct near Gold Reef City. Soweto\'s Vilakazi Street (Nelson Mandela\'s and Desmond Tutu\'s former homes are on the same street — unique globally) is best visited with a local guide who can contextualise the neighbourhood and its history.' },
      { type: 'faq', faqs: [
        { q: 'Is Johannesburg worth visiting or should I go straight to Cape Town?', a: 'Joburg is the gateway to Kruger National Park (the world\'s most accessible Big Five game reserve) and has world-class cultural sites (Apartheid Museum, Soweto, Constitution Hill). If you\'re doing a South Africa trip, a 2-day Joburg stop adds genuine depth. Cape Town alone doesn\'t give you the Highveld, the mining history, or authentic township culture.' },
        { q: 'How do I get from OR Tambo Airport to Sandton?', a: 'Gautrain (airport rail, MYR 235 / ~$13) from OR Tambo to Sandton Station — 15 minutes, the fastest and safest option. Uber from the designated pickup area: MYR 200–350 ($11–19) depending on destination and traffic. Never use unbooked taxi services at OR Tambo.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-phnom-penh',
    title: 'How Much Does a Taxi Cost in Phnom Penh? (2025 Fare Guide)',
    description: 'Phnom Penh taxis are mostly unmetered. PassApp and Grab charge $2–5 for most city trips. Airport to city costs $10–15. Here\'s everything you need to know.',
    publishedAt: '2025-08-31',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Phnom Penh',
    country: 'Cambodia',
    content: [
      { type: 'intro', body: 'Phnom Penh has no standardised metered taxis. PassApp (Cambodia\'s dominant ride-hailing app) and Grab both offer app-based rides with upfront pricing — the strongly recommended option for tourists. Traditional tuk-tuks are fun and cheap for short trips but require price negotiation.' },
      { type: 'h2', heading: 'Typical Phnom Penh Transport Fares (2025)' },
      { type: 'table', rows: [
        { label: 'PNH Airport → Riverside/BKK1', value: 'PassApp/Grab: $8–12 | Tuk-tuk (negotiated): $10–18 | Hotel shuttle: $15–25' },
        { label: 'Short city trip (2–3km)', value: 'PassApp: $2–4 | Tuk-tuk: $3–6 (negotiate) | Moto (Grab Bike): $1–2' },
        { label: 'Riverside → Russian Market (Toul Tom Poung)', value: 'PassApp: $4–7 | Tuk-tuk: $5–8' },
        { label: 'Riverside → Killing Fields (Choeung Ek)', value: 'Tuk-tuk: $15–20 round trip with wait | PassApp Car: $10–14 one-way' },
        { label: 'Tuk-tuk per hour', value: 'USD $5–10/hour negotiated for city touring' },
      ]},
      { type: 'h2', heading: 'Transport Options in Phnom Penh' },
      { type: 'ul', items: [
        '**PassApp**: Cambodia\'s leading app — car and moto (motorbike) options; most locals use this; recommended',
        '**Grab**: Also operates; slightly fewer drivers than PassApp in Phnom Penh; same pricing model',
        '**Traditional tuk-tuk**: Fun, breezy, best for short hops — agree price firmly before departing; $3–6 for most tourist routes',
        '**Remork (trailer tuk-tuk)**: Larger, more comfortable version — ideal for groups or luggage',
        '**Moto-dop (motorbike taxi)**: Cheapest option ($1–3) but not recommended for tourists unfamiliar with Phnom Penh traffic',
      ]},
      { type: 'tip', body: 'Download PassApp before arriving in Cambodia — it\'s more widely used than Grab in Phnom Penh and Siem Reap. Unlike Grab, PassApp also shows Cambodian-language menus so local drivers are more likely to accept your request immediately. Keep the app topped up with $10–20 for smooth operation throughout your visit.' },
      { type: 'faq', faqs: [
        { q: 'Do tuk-tuk drivers in Phnom Penh speak English?', a: 'Tourist-area tuk-tuk drivers have working English — enough to understand major destinations and negotiate prices. ShowMap app (show your destination on a map) works as a universal fallback. Avoid overcomplicating directions; write the name of your hotel and show it.' },
        { q: 'Is it safe to take moto-dops (motorbike taxis) in Phnom Penh?', a: 'Traffic in Phnom Penh is hectic by Western standards. Moto-dops are used by millions of locals daily but carry higher accident risk than cars. If you choose one, wear the helmet provided, hold on firmly, and avoid rush hour. For most tourists, PassApp Car or tuk-tuk is preferable for comfort and peace of mind.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-colombo',
    title: 'How Much Does a Taxi Cost in Colombo? (2025 Fare Guide)',
    description: 'Colombo taxis cost LKR 100 flag fall + LKR 60–100/km. PickMe and Uber are the recommended apps. Airport to city runs LKR 2,500–3,500 (~$8–11).',
    publishedAt: '2025-09-01',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Colombo',
    country: 'Sri Lanka',
    content: [
      { type: 'intro', body: 'Colombo taxis vary widely: air-conditioned app-based cars via PickMe or Uber cost LKR 1,500–3,000 ($5–10) for most city trips, while traditional three-wheelers (tuk-tuks) are cheaper but prone to meter refusal. PickMe is Sri Lanka\'s dominant app and offers both car and tuk-tuk options with upfront pricing.' },
      { type: 'h2', heading: 'Typical Colombo Taxi Fares (2025)' },
      { type: 'table', rows: [
        { label: 'CMB Airport → Fort/Pettah', value: 'PickMe/Uber: LKR 2,500–3,500 ($8–11) | Traditional taxi: LKR 3,000–5,000 (negotiated)' },
        { label: 'Fort → Pettah Market', value: 'PickMe: LKR 300–600 ($1–2) | Tuk-tuk: LKR 150–300 negotiated' },
        { label: 'Colombo 3 → Colombo 7 (Cinnamon Gardens)', value: 'PickMe: LKR 500–900 ($1.60–3)' },
        { label: 'Colombo → Kandy (3 hrs)', value: 'App car: LKR 8,000–12,000 ($26–40) | Train: LKR 200–400 (slow but scenic)' },
        { label: 'Three-wheeler (tuk-tuk) short trip', value: 'Metered: LKR 60–80/km | PickMe tuk-tuk: set price in app' },
      ]},
      { type: 'h2', heading: 'PickMe vs Uber in Colombo' },
      { type: 'p', body: 'PickMe is the local champion — more drivers, faster pickups, and lower prices than Uber in most Colombo situations. PickMe also allows you to book three-wheelers (tuk-tuks) and bikes through the same app, giving flexible options. Uber operates in Colombo and is slightly more expensive but useful as a backup when PickMe is surging. Both accept international Visa/Mastercard.' },
      { type: 'tip', body: 'Sri Lanka\'s train network is spectacular — the Kandy line (Colombo to Kandy through tea country) and the Ella–Badulla line are genuinely among the world\'s most beautiful rail journeys. First-class observation seats cost LKR 1,000–1,500 ($3–5) and should be booked weeks ahead at railway.gov.lk. Don\'t take a taxi to Kandy when the train offers a better experience.' },
      { type: 'faq', faqs: [
        { q: 'Are three-wheelers (tuk-tuks) safe in Colombo?', a: 'Generally yes — they\'re the dominant short-hop transport for locals. Traditional three-wheelers have metered rates but drivers often negotiate tourist rates. Using PickMe\'s tuk-tuk option gives the lower local rate with the safety of app tracking. Three-wheelers are open-sided — avoid during heavy monsoon rain.' },
        { q: 'What is the best way to get from Colombo to Galle?', a: 'Coastal train from Colombo Fort to Galle (2.5 hours, LKR 200–800 depending on class) is scenic and comfortable. App taxi: LKR 5,000–8,000 ($16–26) and faster (1.5 hrs on the expressway). The train along the coast through Bentota and Hikkaduwa is the more memorable option.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-bogota',
    title: 'How Much Does a Taxi Cost in Bogotá? (2025 Fare Guide)',
    description: 'Bogotá taxis are metered but tourist safety requires using apps. InDriver and Cabify are recommended. Airport to Zona Rosa costs COL $45,000–65,000 (~$11–16).',
    publishedAt: '2025-09-03',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Bogotá',
    country: 'Colombia',
    content: [
      { type: 'intro', body: 'Bogotá has metered taxis but street-hailing carries genuine security risk — "paseo millonario" (express kidnapping via fake taxis) is a documented threat. Always use InDriver, Cabify, or Uber instead of hailing on the street. App rides give you driver details, route tracking, and cashless payment — dramatically reducing risk.' },
      { type: 'h2', heading: 'Typical Bogotá Taxi Fares (2025)' },
      { type: 'table', rows: [
        { label: 'El Dorado Airport (BOG) → Zona Rosa/Chapinero', value: 'App: COL $45,000–65,000 ($11–16); 30–50 min via Autopista Norte' },
        { label: 'Zona Rosa → La Candelaria (historic centre)', value: 'App: COL $15,000–25,000 ($3.70–6.20); 20–35 min depending on traffic' },
        { label: 'La Candelaria → Usaquén (Sunday flea market)', value: 'App: COL $25,000–40,000 ($6.20–10); 30–45 min' },
        { label: 'Standard 5km city trip', value: 'App: COL $12,000–20,000 ($3–5); metered taxi (if safe): COL $8,000–16,000' },
        { label: 'Night surcharge', value: '35% added to meter rate after 9pm and before 5am' },
      ]},
      { type: 'h2', heading: 'Best Taxi Apps in Bogotá' },
      { type: 'ul', items: [
        '**InDriver**: Ride-bidding app popular in Colombia — set your own price or accept driver offers; often cheapest option',
        '**Cabify**: Premium option with vetted drivers; slightly more expensive but very safe',
        '**Uber**: Operates in Colombia; comparable to Cabify; some drivers use unmarked cars (legally complex in Colombia but common)',
        '**Beat**: Also operates in Bogotá; competitive pricing',
        '**Never**: Accept rides from drivers who approach you at the airport, shopping malls, or on the street',
      ]},
      { type: 'tip', body: 'Bogotá has TransMilenio — an extensive Bus Rapid Transit system (COL $2,950 per trip, ~$0.73) covering most of the city north-south on Caracas and Autopista Norte. It\'s crowded but fast, and the main trunk lines connect the airport area to La Candelaria and Chapinero. Add a Tullave card (similar to a transit card) to avoid carrying exact change.' },
      { type: 'faq', faqs: [
        { q: 'Is Bogotá safe for tourists in 2025?', a: 'Bogotá\'s tourist neighbourhoods — Zona Rosa, Parque 93, Usaquén, and La Candelaria (daytime) — are increasingly safe with normal precautions. The city has invested heavily in security infrastructure. Avoid Parque Tercer Milenio, Bronx area, and south Bogotá. Never walk on the street while distracted by a phone, especially near La Candelaria at night.' },
        { q: 'How is Bogotá\'s altitude for travellers?', a: 'Bogotá sits at 2,640m — higher than Mexico City. Mild altitude symptoms (headache, fatigue, shortness of breath) are common on day one. Rest, drink water, avoid alcohol on arrival. Acclimatise before attempting hikes around the city (eg. Monserrate). Altitude sickness medication (acetazolamide) is available at Colombian pharmacies.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-lima',
    title: 'How Much Does a Taxi Cost in Lima? (2025 Fare Guide)',
    description: 'Lima taxis are unmetered — all prices are negotiated. Beat and InDriver are strongly recommended for safety. Miraflores to airport costs $20–30 via app.',
    publishedAt: '2025-09-05',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Lima',
    country: 'Peru',
    content: [
      { type: 'intro', body: 'Lima has no metered taxis — every fare is negotiated. More critically, Lima has a significant express kidnapping risk from informal street taxis. Beat (formerly Taxibeat Peru) and InDriver are the strongly recommended options: set price before booking, driver details tracked, safe pickup.' },
      { type: 'h2', heading: 'Typical Lima Taxi Fares (2025)' },
      { type: 'table', rows: [
        { label: 'Jorge Chávez Airport (LIM) → Miraflores', value: 'Beat/Uber: $20–28 | Negotiated taxi: $25–40 | Travel time: 30–60 min (traffic-dependent)' },
        { label: 'Miraflores → Barranco', value: 'Beat: $5–8 | Negotiated: $8–15; 3km coastal drive' },
        { label: 'Miraflores → Historic Centre (Plaza de Armas)', value: 'Beat: $10–16 | Negotiated: $15–25; 8km, 25–45 min' },
        { label: 'Short Miraflores trip (2km)', value: 'Beat: $3–6 | Negotiated (from street): $5–10' },
        { label: 'Night surcharge', value: 'Informal: ad hoc increase expected after 10pm; Beat: prices shown upfront regardless of time' },
      ]},
      { type: 'h2', heading: 'Lima Safety and Taxi Rules' },
      { type: 'ul', items: [
        '**Never hail taxis on the street in Lima** — express kidnapping via informal taxis is a documented risk; it happens to tourists',
        '**Beat (formerly Taxibeat)**: most popular app in Peru; larger driver pool than Uber in Lima; download before arriving',
        '**InDriver**: bid-based; often cheapest; good driver availability in San Isidro, Miraflores, Barranco',
        '**Uber**: operates in Lima and is reliable; slightly fewer drivers than Beat in suburban areas',
        '**Airport taxis**: Use the authorised Taxi Green or Taxi Ejecutivo booths inside arrivals — pre-pay a fixed amount; do not accept offers from people approaching you in arrivals',
      ]},
      { type: 'tip', body: 'Lima\'s affluent tourist districts — Miraflores, Barranco, and San Isidro — are the safest in Peru\'s capital. The Pacific Ocean cliffside Malecón walk (free, 3km) connecting Miraflores to Barranco is one of South America\'s best coastal urban promenades. Stay in these districts and use Beat exclusively — you will have an excellent Lima experience.' },
      { type: 'faq', faqs: [
        { q: 'Is Lima safe for tourists?', a: 'In the tourist districts (Miraflores, Barranco, San Isidro), yes — these are among the more secure areas of any South American capital. The historic centre requires daytime-only visiting with valuables secured. Avoid Callao (port area), La Victoria, and all areas beyond the tourist belt. The single biggest safety rule: use Beat or Uber exclusively for transport.' },
        { q: 'How much is a taxi from Lima Airport to Miraflores?', a: 'Via Beat or Uber: $20–28 depending on exact destination and surge. Via the official Taxi Green/Ejecutivo counter inside arrivals: $25–35 fixed rate. Never accept rides from informal drivers in the arrivals hall (they will approach you) — the price they offer is not the main issue; the safety risk is.' },
      ]},
    ],
  },
  {
    slug: 'taxi-costs-havana',
    title: 'How Much Does a Taxi Cost in Havana? (2025 Fare Guide)',
    description: 'Havana has official metered taxis and tourist taxis (classic American cars). There are no app-based rides in Cuba. Most airport-to-centre trips cost $25–35 negotiated.',
    publishedAt: '2025-09-07',
    readingMinutes: 4,
    category: 'taxi',
    city: 'Havana',
    country: 'Cuba',
    content: [
      { type: 'intro', body: 'Havana\'s taxi system is unique — no Uber, no Grab, no apps. You choose between official metered taxis (yellow state taxis), classic American car tourist taxis, colectivos (shared taxis on fixed routes), and coco-taxis (three-wheeled yellow vehicles). All prices are negotiated or metered in CUP.' },
      { type: 'h2', heading: 'Havana Taxi Types and Fares (2025)' },
      { type: 'table', rows: [
        { label: 'Classic American car (tourist taxi)', value: '$20–35 negotiated for airport (HAV/HAV-1) to Old Havana or Vedado; agree price before entering' },
        { label: 'Yellow state taxi (metered)', value: 'CUP 50/km metered; most honest option; harder to find outside hotels' },
        { label: 'Colectivo (shared, fixed route)', value: 'CUP 40–100 ($0.15–0.40 at current rate) for shared rides on set routes across the city' },
        { label: 'Coco-taxi (open-air 3-wheeler)', value: '$5–15 for tourist area trips; fun but noisy and exposed' },
        { label: 'Havana airport → Old Havana', value: '$25–40 negotiated classic car; $20–30 metered state taxi' },
      ]},
      { type: 'h2', heading: 'Navigating Cuba\'s Currency System' },
      { type: 'p', body: 'Cuba operates with a complex currency reality in 2025. The Cuban peso (CUP) is the local currency; USD, EUR, and CAD cash are widely accepted in tourist contexts at informal exchange rates. Credit cards from US-linked banks do not work in Cuba (including Mastercard/Visa processed through US intermediaries). Bring sufficient cash for your entire stay — ATMs exist but are unreliable. Tourist taxis typically price in USD; colectivos and local services price in CUP.' },
      { type: 'tip', body: 'Negotiating with classic car drivers: start the conversation, let them name a price, counter at 60–70%, and settle around 75–80% of their opening offer. This is standard and expected — drivers aren\'t offended by negotiation. For return trips (airport at end of stay), arrange the car the day before through your casa particular host for a pre-agreed price.' },
      { type: 'faq', faqs: [
        { q: 'Can I use Uber or any app in Cuba?', a: 'No — Uber does not operate in Cuba and no equivalent app-based service exists. Cuba\'s internet limitations and the US embargo both contribute to this gap. All taxi booking is done in person: at your hotel, casa particular, or by approaching drivers on the street. WhatsApp is sometimes used to reach specific drivers by phone number — ask your accommodation to recommend one.' },
        { q: 'Are the classic American cars safe to ride in Havana?', a: 'Yes — the 1950s American cars (Chevrolets, Buicks, Fords) are a genuine feature of Havana travel and are maintained to a working standard. Air conditioning is usually absent; windows open. They are not mechanically pristine by modern standards but are roadworthy. Agree your destination and price clearly before getting in — there\'s no meter in tourist cars.' },
      ]},
    ],
  },
  {
    slug: 'tipping-in-cash-only-countries',
    title: 'Tipping in Cash-Only Countries: What to Carry & How Much (2025)',
    description: 'Cuba, Myanmar, and parts of Africa require cash tips — cards won\'t work. Here\'s what currencies to carry and how to tip effectively in cash-dependent destinations.',
    publishedAt: '2025-09-10',
    readingMinutes: 4,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'In several destinations, digital tipping is simply not possible — cards don\'t work, apps don\'t exist, and the local currency may not even be widely accepted. Cuba, Myanmar, North Korea, rural Cambodia, and parts of East Africa require you to plan your cash tipping strategy before arrival.' },
      { type: 'h2', heading: 'Cash-Only Tipping Countries (2025)' },
      { type: 'table', rows: [
        { label: 'Cuba', value: 'USD or EUR; $1–2 for restaurant staff, $5–10 for music performers, $20–30 for guides. CUP impractical for tourists to accumulate in right denominations.' },
        { label: 'Myanmar', value: 'USD (clean, unfolded notes essential) or Kyat; $1–5 range for most tips; ATMs present but international cards often declined' },
        { label: 'Ethiopia', value: 'ETB cash essential; $1–3 equivalent for most services; guides $5–10/day; USD accepted as backup' },
        { label: 'Rural Cambodia / Laos', value: 'USD and Riel/Kip both used; $1–2 for most tips; remote areas cash only' },
        { label: 'Morocco (rural areas)', value: 'MAD coins for hammam attendants, parking helpers, tea pourers; major cities more card-friendly' },
        { label: 'Egypt', value: 'EGP essential for bakshish culture; carry EGP 5–20 notes throughout the day; USD accepted at tourist sites' },
      ]},
      { type: 'h2', heading: 'Pre-Trip Cash Strategy' },
      { type: 'ul', items: [
        '**Break large bills before departure**: Get $1, $5, and $10 USD bills from your bank at home — harder to obtain abroad',
        '**Carry two currencies**: Your home currency plus USD as universal backup for tip situations',
        '**Cuba-specific**: Arrive with all the cash you need — USD $100 bills get the best exchange rate; $20 and $50 also accepted; $100 bills must be undefaced',
        '**Myanmar-specific**: USD notes must be pristine — any fold, mark, or pen mark will be refused; bring freshly printed bills',
        '**Daily float**: Each morning, separate that day\'s tip money into a different pocket — never reveal your full wallet when tipping',
      ]},
      { type: 'tip', body: 'When departing a cash-only country, use remaining local currency for airport food, last taxi, or tips — you\'ll get poor exchange rates for leftover cash at home airports. In Cuba specifically, any CUP you hold at departure cannot be exchanged outside the country. Spend it all before you fly.' },
      { type: 'faq', faqs: [
        { q: 'Do I need to tip in Myanmar in 2025?', a: 'Yes — tipping is appreciated and important given the economic disruption since 2021. Restaurant staff, hotel housekeeping ($1–2/day), guides ($5–10/day), and drivers ($5–8/day) all rely on tips as a significant income supplement. USD is universally preferred; Kyat is also appropriate for small restaurant tips.' },
        { q: 'What denominations should I bring for Cuba?', a: 'Bring a mix of USD $1, $5, $10, and $20 bills. Larger bills ($50, $100) are used for accommodation and larger purchases. $1 bills are essential for small tips (musicians, cocktail waiters, parking helpers). Cuba\'s own currency situation is complex — your accommodation will advise on current CUP exchange rates on arrival.' },
      ]},
    ],
  },
  {
    slug: 'tipping-in-muslim-countries',
    title: 'Tipping in Muslim Countries: What\'s Expected Across the Muslim World (2025)',
    description: 'Tipping norms vary widely across Muslim countries — from Egypt\'s bakshish culture to the UAE\'s optional-but-appreciated gratuities. Here\'s the full guide.',
    publishedAt: '2025-09-13',
    readingMinutes: 5,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'There is no single "Muslim" tipping culture — practices vary enormously by country, from Egypt where small tips (bakshish) are embedded in daily life to Japan-adjacent Singapore where Islam is practiced but tipping isn\'t expected. Here\'s country-by-country guidance for the world\'s most-visited Muslim-majority destinations.' },
      { type: 'h2', heading: 'Tipping in Muslim Countries (2025)' },
      { type: 'table', rows: [
        { label: 'UAE (Dubai/Abu Dhabi)', value: '10–15% restaurants appreciated; not mandatory; no tipping culture pressure' },
        { label: 'Qatar (Doha)', value: 'Service charge often on bill; 10% extra welcomed; not obligatory' },
        { label: 'Egypt', value: 'Bakshish expected everywhere — EGP 5–50 for restrooms, guards, small services; 10% restaurants' },
        { label: 'Morocco', value: 'MAD 5–20 for most small tips; 10% restaurants; MAD 50–100 for full-day guides' },
        { label: 'Turkey', value: '10% restaurants; round up taxis; €5–15 guides per day' },
        { label: 'Indonesia (Bali)', value: '10% restaurants if no service charge; IDR 20,000–50,000 for spa; driver $5–10/day' },
        { label: 'Malaysia', value: '10% service charge already added to most bills; no additional tip expected' },
        { label: 'Jordan', value: 'JOD 1–2 for most services; 10% restaurants; $10–15 guides per day' },
        { label: 'Saudi Arabia', value: 'Tipping uncommon historically; tourist-facing restaurants now appreciate 10%; guide $15–20' },
      ]},
      { type: 'h2', heading: 'Ramadan and Tipping' },
      { type: 'ul', items: [
        'Tipping is entirely appropriate during Ramadan — it does not conflict with Islamic practice',
        'During daytime fasting hours, restaurant service may be slower — tip the same; staff are working while fasting',
        'Iftar (breaking fast at sunset) is a wonderful time to dine — restaurants come alive; tip 10–15% on what is often a special communal meal',
        'In Egypt during Ramadan, bakshish continues as normal throughout the holy month',
        'Ramadan dates shift ~11 days earlier each year — check dates for your travel year before planning',
      ]},
      { type: 'tip', body: 'Egypt\'s bakshish culture can feel overwhelming for first-time visitors — small tips are expected for services that would be free elsewhere (restroom attendants, museum guards who show you an extra artefact, parking helpers). Budget EGP 100–200 ($2–4) per day in small notes specifically for bakshish and treat it as part of the experience rather than a nuisance.' },
      { type: 'faq', faqs: [
        { q: 'Is tipping allowed in Islam?', a: 'Yes — tipping (ihsan, or giving more than required) is encouraged in Islamic ethics as a form of generosity. The Prophet Muhammad encouraged rewarding good service. There is no religious prohibition on tipping; the variation in tipping cultures across Muslim countries reflects local economic and social traditions, not Islamic law.' },
        { q: 'Should I tip in Dubai restaurants?', a: 'A 10–15% tip is appreciated but not required. Most Dubai restaurant bills include a 10% service charge — check before adding more. For exceptional service, an additional 5–10% cash tip directly to the waiter is a generous gesture. Unlike New York or Australia, you will not cause offence by not tipping in Dubai.' },
      ]},
    ],
  },
  {
    slug: 'when-not-to-tip',
    title: 'When NOT to Tip: Countries & Situations Where Tipping Is Wrong (2025)',
    description: 'In Japan, South Korea, and Iceland tipping can be offensive. In Singapore, the service charge is already included. Here\'s a complete guide to when not to tip.',
    publishedAt: '2025-09-16',
    readingMinutes: 4,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'Not tipping in the wrong place is respectful, not rude. In Japan, tipping is considered insulting — implying the worker isn\'t paid fairly for their professional service. In Singapore, you\'ve already tipped via the mandatory 10% service charge. Knowing when NOT to tip is as important as knowing when to tip.' },
      { type: 'h2', heading: 'Countries Where Tipping Is Inappropriate or Unnecessary' },
      { type: 'table', rows: [
        { label: 'Japan', value: 'Never tip — considered rude or patronising; staff may chase you to return money; verbal gratitude is correct' },
        { label: 'South Korea', value: 'Tipping culture is minimal; staff may decline or be confused; not expected anywhere' },
        { label: 'China', value: 'Local restaurants and taxis: not expected; some tourist hotel venues accept tips graciously but won\'t solicit' },
        { label: 'Singapore', value: '10% service charge already on bill + 9% GST; no additional tip needed or expected' },
        { label: 'Iceland', value: 'Workers earn living wages; tipping uncommon; rounding up is fine, 20% American-style tip is unnecessary' },
        { label: 'Switzerland', value: 'Rounding up is normal; large tips are unnecessary — Swiss service workers are among the world\'s best-paid' },
        { label: 'Hong Kong', value: '10% service charge on most bills; no extra tip expected; optional small gesture for outstanding service' },
        { label: 'New Zealand / Australia', value: 'Tipping not obligatory; workers earn minimum wages; 10% for exceptional service is generous, not expected' },
      ]},
      { type: 'h2', heading: 'Situations Where You Should Never Tip (Anywhere)' },
      { type: 'ul', items: [
        '**When a mandatory service charge is on the bill**: Check before adding more — you may be tipping twice',
        '**When someone provides unsolicited "help"**: Strangers who grab your bag, "guide" you without invitation, or offer unrequested services then demand payment are scams, not service',
        '**Government employees performing their duties**: Immigration officers, customs officials, police — tipping is bribery and can cause serious trouble',
        '**Healthcare workers in most countries**: Doctors, nurses, pharmacists are professionals paid for their expertise — tipping is inappropriate in most countries (US may be an exception for some specialist care relationships)',
        '**When the service was genuinely poor**: A 0% tip for a mediocre waiter is uncomfortable; a minimal tip ($1–2) sends the signal without being offensive',
      ]},
      { type: 'tip', body: 'The "tip screen" problem: self-serve cafes, fast food counters, and takeaway windows now routinely display a tip prompt on card terminals. You are under zero obligation to tip at a counter-service restaurant where no table service was provided. Press the "No Tip" or "Custom" ($0.00) option with confidence. These screens are designed to normalise tipping beyond its traditional context.' },
      { type: 'faq', faqs: [
        { q: 'What happens if I tip in Japan by accident?', a: 'The staff member may politely decline and hand it back. If you insist, they may become uncomfortable or report it to their manager. The kindest thing if you want to express appreciation in Japan: a genuine bow and a specific verbal compliment in Japanese (or English — they\'ll understand the sentiment). Saying "totemo oishikatta desu" (it was very delicious) at a restaurant means far more than cash.' },
        { q: 'Is it rude not to tip in the USA?', a: 'At sit-down restaurants: yes — US service staff are often paid sub-minimum wages ($2.13/hour in some states) on the assumption that tips make up the difference. Not tipping in a US restaurant is genuinely unkind to the server. At counter-service, fast food, or self-serve venues: no tip is needed, and the tip screen prompts are optional. The distinction matters.' },
      ]},
    ],
  },
  {
    slug: 'digital-tipping-guide',
    title: 'Digital Tipping Guide: How to Tip When You Have No Cash (2025)',
    description: 'Most major apps now include in-app tipping. Here\'s how to tip Uber drivers, hotel staff, restaurant servers, and tour guides without cash in 2025.',
    publishedAt: '2025-09-19',
    readingMinutes: 4,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'The shift to cashless payments has transformed tipping — for better and worse. Uber, Lyft, DoorDash, and Square POS all prompt you to tip digitally. But many workers who rely on tips — hotel housekeeping, tour guides, spa therapists — still receive tips best in cash. Here\'s how to navigate both worlds.' },
      { type: 'h2', heading: 'Where Digital Tipping Works Well' },
      { type: 'table', rows: [
        { label: 'Ride-hailing (Uber, Lyft, Grab)', value: 'In-app tip prompt after ride completion; 10–20% common; tip within 30 days of ride' },
        { label: 'Food delivery (DoorDash, Uber Eats)', value: 'Tip in app before or after delivery; 15–20% standard; pre-tip increases driver likelihood of accepting order' },
        { label: 'Restaurant POS (Square, Toast)', value: 'Tip prompt on card terminal at checkout; 18–22% at sit-down; tap "custom" for specific amount' },
        { label: 'Hotel front desk (digital checkout)', value: 'Many hotel apps now include tip option at checkout for housekeeping pool' },
        { label: 'QR code tip jars', value: 'Common at US cafes since 2022; scan to tip barista via Venmo or app; entirely optional' },
      ]},
      { type: 'h2', heading: 'Where Cash Tipping Is Still Superior' },
      { type: 'ul', items: [
        '**Hotel housekeeping**: Daily cash tip (left on pillow or desk with a "Thank You" note) is the only reliable way to ensure it reaches the individual who cleaned your room — digital checkout pools are split unpredictably',
        '**Spa therapists**: Many spas don\'t pass on card tips; hand cash directly to your therapist',
        '**Tour guides**: Cash is universally accessible and avoids the guide needing to manage multiple payment apps',
        '**Valet parking**: Cash tip on car retrieval is the norm; digital options rarely available',
        '**International destinations**: In Southeast Asia, Africa, Latin America — digital tipping options are rare; cash is essential',
      ]},
      { type: 'tip', body: 'The "auto-gratuity" problem: many US restaurants add an automatic 18–20% service charge to groups of 6+ people. Always check your bill — the tip line on the card terminal is for an additional tip on top of the already-added gratuity. Paying twice is a common tourist mistake. If auto-gratuity is already on the bill, sign "0.00" on the tip line.' },
      { type: 'faq', faqs: [
        { q: 'Should I tip before or after delivery in food apps?', a: 'Pre-tipping (setting a tip when ordering) significantly increases the chance a driver accepts your delivery, especially in off-peak times or for long distances. Post-trip adjustments are possible on most apps within a window. For good service, leave the tip as-is or increase it. For genuinely poor service (very late, damaged order), adjust down within 24 hours.' },
        { q: 'Do Uber drivers prefer cash or in-app tips?', a: 'Either is appreciated, but cash is immediately available to the driver rather than being paid out in a weekly batch payment. If you have local cash, a $2–3 cash tip handed directly at the end of the ride is warmly received. In-app tips ensure the driver gets credited even if you forget to tip on exit.' },
      ]},
    ],
  },
  {
    slug: 'tipping-guide-for-solo-female-travellers',
    title: 'Tipping Guide for Solo Female Travellers: Safety, Culture & Etiquette (2025)',
    description: 'Solo female travellers face unique dynamics around tipping. Here\'s how to tip safely, avoid unwanted attention, and navigate service interactions confidently worldwide.',
    publishedAt: '2025-09-22',
    readingMinutes: 5,
    category: 'tipping',
    content: [
      { type: 'intro', body: 'For solo female travellers, tipping is not just about courtesy — it\'s also a tool for managing interactions safely and respectfully. A confident, appropriately-sized tip signals self-assurance; a fumbled over-tip can attract unwanted attention; and in some cultures, how you tip communicates your social standing. Here\'s how to navigate it.' },
      { type: 'h2', heading: 'Tipping by Service Type: Solo Female Perspective' },
      { type: 'table', rows: [
        { label: 'Taxi / ride-hailing drivers', value: 'Tip after safe arrival, not before; use in-app tipping where possible to avoid displaying cash; 10–15%' },
        { label: 'Tour guides', value: 'Tip at the end, privately — a handshake and folded note (not a showy wad) is the correct approach; $10–20pp/day' },
        { label: 'Hotel staff (porter, concierge)', value: '$1–2/bag; hand discreetly, not publicly; if the concierge is being particularly attentive, a moderate tip maintains professional distance' },
        { label: 'Restaurant servers', value: 'Standard local norms apply; tip by card where possible (less cash display)' },
        { label: 'Spa / massage therapists', value: 'Tip directly to therapist at end of session; pre-agreed amount avoids any awkward negotiation' },
        { label: 'Hammam attendants (Morocco, Turkey)', value: 'MAD 30–50 / TRY 50–100; tip the female attendant directly if possible; request female-only sessions' },
      ]},
      { type: 'h2', heading: 'Safety-First Tipping Practices' },
      { type: 'ul', items: [
        '**Never display your full wallet**: Carry day-tip money in a separate pocket — $1/$5 notes accessible without revealing your total cash',
        '**Tip privately**: Hand tips with a natural, confident gesture — not a production. Eye contact + a thank you is the correct accompanying behaviour',
        '**In male-dominated service contexts** (North Africa, South Asia): a professionally-sized tip signals confidence and respect; an over-tip can be misread as seeking extended interaction',
        '**In taxis, tip after arrival**: If a driver has been helpful and safe, a tip at the destination point is correct. Never tip up front — it reduces incentive for safe driving and creates obligation dynamics',
        '**Trust your instincts**: If an interaction feels unsafe, your safety is worth more than tipping etiquette. Leave without tipping if necessary — it is always the right call',
      ]},
      { type: 'tip', body: 'In countries with strong negotiated-price service cultures (Morocco, Egypt, India, Southeast Asia), agree the total price for a service upfront, including any tip you plan to add. "I\'ll pay X — is that okay?" avoids post-service pressure and keeps you in control of the interaction.' },
      { type: 'faq', faqs: [
        { q: 'What should I do if a service worker refuses to accept the agreed price and demands more?', a: 'Stay calm and confident. Restate the agreed price clearly once ("We agreed on X"). If they continue, do not argue — pay the agreed amount and leave. Do not be pressured into over-tipping through raised voices or dramatic behaviour. In tourist areas, this tactic relies on the tourist\'s discomfort; quiet confidence defuses most situations.' },
        { q: 'Is it safer to tip by card or cash as a solo female traveller?', a: 'Card tipping (in-app or POS terminal) is generally safer as it avoids displaying cash and creating potential follow-up dynamics. Cash tipping is necessary in many international contexts — in those cases, pre-separated small notes handled discreetly are the safest approach. Pre-trip: always have a mix of both options available.' },
        { q: 'Do female-only services require different tipping norms?', a: 'No — tip the same amount regardless of the service provider\'s gender. Female-only taxis (available in UAE, Saudi Arabia, and some Southeast Asian cities) follow standard local tipping norms. Women-only hammam sessions in Morocco: tip your female attendant MAD 30–50 directly.' },
      ]},
    ],
  },
]
