import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about FairFare — pricing, accuracy, coverage, privacy, and how to get a refund.',
}

const FAQS: { q: string; a: string }[] = [
  {
    q: 'How much does it cost?',
    a: '$0.99 USD per query. You pay once and get a single-use access token valid for 30 minutes. There are no subscriptions, no monthly fees, and no account required.',
  },
  {
    q: 'What payment methods are accepted?',
    a: 'Payment is handled by Stripe. You can pay with any major credit or debit card. Apple Pay and Google Pay are supported automatically on compatible devices and browsers.',
  },
  {
    q: 'How accurate are the fare estimates?',
    a: 'Fare ranges are calculated from a curated dataset of local taxi rates combined with real route distances from Google Maps. A ±15% range is applied to account for traffic, surcharges, and driver discretion. Always confirm the fare with your driver before the journey — FairFare is a reference tool, not a metered guarantee.',
  },
  {
    q: 'Which cities are covered for taxi fares?',
    a: 'FairFare covers 120+ cities across every continent, including major tourist destinations in Asia, Europe, the Americas, Africa, and the Middle East. If your city is not in our dataset, the result will include a note to verify the fare directly with your driver.',
  },
  {
    q: 'Which countries are covered for tipping?',
    a: 'Tipping guides are available for 50+ countries including all major travel destinations. The guide covers six scenarios: restaurants, taxis, hotel porters, bars, tour guides, and delivery.',
  },
  {
    q: 'What are the scam warnings based on?',
    a: 'Scam warnings are AI-generated by Anthropic Claude and reflect well-known issues specific to each city — such as meter tampering, unofficial taxis, or fixed-price scams. They are generated from Claude\'s training data and cached for up to 30 days. They are a starting point for awareness, not a guarantee of current conditions.',
  },
  {
    q: 'Can I use my token for multiple searches?',
    a: 'Each $0.99 payment grants one access token for one query result. The token is valid for 30 minutes after issue, but it is single-use — you cannot use the same payment to look up multiple cities or countries.',
  },
  {
    q: 'Do I need to create an account?',
    a: 'No. FairFare has no accounts, no sign-up, and no login. Your query result and access token are stored temporarily in your browser only.',
  },
  {
    q: 'Can I get a refund?',
    a: 'Due to the instant digital nature of the service, all sales are final once a result has been delivered. If you experienced a technical failure that prevented delivery, contact legal@fairfare.app within 7 days and we will review your case.',
  },
  {
    q: 'Is my payment data stored?',
    a: 'No. Payment is processed entirely by Stripe. FairFare never sees, handles, or stores your card number, CVC, or banking details. We only receive confirmation that a payment session was completed.',
  },
  {
    q: 'Does FairFare track my location?',
    a: 'No. FairFare does not use GPS or request location permission. You type addresses manually. Those addresses are sent to Google Maps to calculate the route distance — that is the only data sent.',
  },
  {
    q: 'What data is sent to Anthropic?',
    a: 'Only the city and country name of your pickup location (e.g. "Bangkok, Thailand") is sent to the Claude API to generate scam warnings, tipping notes, and driver phrases. No address-level detail is included.',
  },
  {
    q: 'Is FairFare affiliated with any taxi company?',
    a: 'No. FairFare is an independent travel reference tool with no affiliation with any taxi company, driver, dispatch service, or transportation authority.',
  },
  {
    q: 'What languages is the app available in?',
    a: 'The FairFare interface is available in English, Spanish, French, and German. Use the language selector in the bottom navigation bar to switch. AI-generated content (scam warnings, tipping advice) is currently in English only.',
  },
]

export default function FaqPage() {
  return (
    <div className="space-y-6 pb-4">
      <div>
        <h1 className="text-xl font-bold text-white">Frequently Asked Questions</h1>
        <p className="text-xs text-zinc-500 mt-1">Everything you need to know about FairFare</p>
      </div>

      <div className="space-y-3">
        {FAQS.map(({ q, a }) => (
          <div key={q} className="rounded-2xl bg-zinc-900 border border-zinc-800 p-4 space-y-1.5">
            <p className="text-sm font-medium text-white leading-snug">{q}</p>
            <p className="text-sm text-zinc-400 leading-relaxed">{a}</p>
          </div>
        ))}
      </div>

      <div className="rounded-2xl bg-zinc-900 border border-zinc-800 p-4 space-y-2">
        <p className="text-sm font-medium text-white">Still have a question?</p>
        <p className="text-sm text-zinc-400">
          Reach us at{' '}
          <a href="mailto:legal@fairfare.app" className="text-purple-400 underline">
            legal@fairfare.app
          </a>
          {' '}and we&apos;ll get back to you within 5 business days.
        </p>
      </div>

      <div className="pt-2 border-t border-zinc-800">
        <Link href="/" className="text-sm text-zinc-600 hover:text-zinc-400 transition-colors">
          ← Back to FairFare
        </Link>
      </div>
    </div>
  )
}
