import type { Metadata } from 'next'
import Link from 'next/link'
import { getUSDPrices } from '@/lib/currency'

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about Hootling — pricing, accuracy, coverage, privacy, and how to get a refund.',
}

function buildFaqs(p: { single: string; pass: string; bundle: string }) {
  return [
  {
    q: 'How much does it cost?',
    a: `From ${p.single} USD per query — no subscriptions, no monthly fees, no account required:`,
    bullets: [
      `Single query — ${p.single}: one taxi fare check or tipping guide`,
      `Country Pass — ${p.pass}: unlimited queries for one country, valid 24 hours`,
      `10-query bundle — ${p.bundle}: stored on your device, valid 90 days across any city or country`,
      `Prices shown in your local currency at checkout`,
    ],
  },
  {
    q: 'What payment methods are accepted?',
    a: 'Payment is handled by Stripe. You can pay with any major credit or debit card. Apple Pay and Google Pay are supported automatically on compatible devices and browsers.',
  },
  {
    q: 'How accurate are the fare estimates?',
    a: 'Fare ranges are calculated from a curated dataset of local taxi rates combined with real route distances from Google Maps. A ±15% range is applied to account for traffic, surcharges, and driver discretion. Always confirm the fare with your driver before the journey — Hootling is a reference tool, not a metered guarantee.',
  },
  {
    q: 'Which cities are covered for taxi fares?',
    a: 'Hootling covers 120+ cities across every continent, including major tourist destinations in Asia, Europe, the Americas, Africa, and the Middle East. If your city is not in our dataset, the result will include a note to verify the fare directly with your driver.',
  },
  {
    q: 'Which countries are covered for tipping?',
    a: 'Tipping guides are available for 50+ countries including all major travel destinations. The guide covers six scenarios: restaurants, taxis, hotel porters, bars, tour guides, and delivery.',
  },
  {
    q: 'What are the scam warnings based on?',
    a: 'Scam warnings are AI-generated by Anthropic Claude and reflect well-known issues specific to each city — such as meter tampering, unofficial taxis, or fixed-price scams. They are generated from Claude\'s training data and cached for up to 90 days. They are a starting point for awareness, not a guarantee of current conditions.',
  },
  {
    q: 'Can I use my payment for multiple searches?',
    a: `It depends on the option chosen. A single query (${p.single}) covers one result. A Country Pass (${p.pass}) allows unlimited taxi and tipping queries for one country for 24 hours. A 10-query bundle (${p.bundle}) gives you 10 queries stored on your device, valid for 90 days across any city or country.`,
  },
  {
    q: 'Do I need to create an account?',
    a: 'No. Hootling has no accounts, no sign-up, and no login. Your query result and access token are stored temporarily in your browser only.',
  },
  {
    q: 'Can I get a refund?',
    a: 'Due to the instant digital nature of the service, all sales are final once a result has been delivered. If you experienced a technical failure that prevented delivery, contact legal@hootling.com within 7 days and we will review your case.',
  },
  {
    q: 'Is my payment data stored?',
    a: 'No. Payment is processed entirely by Stripe. Hootling never sees, handles, or stores your card number, CVC, or banking details. We only receive confirmation that a payment session was completed.',
  },
  {
    q: 'Does Hootling track my location?',
    a: 'No. Hootling does not use GPS or request location permission. You type addresses manually. Those addresses are sent to Google Maps to calculate the route distance — that is the only data sent.',
  },
  {
    q: 'What data is sent to Anthropic?',
    a: 'Only the city and country name of your pickup location (e.g. "Bangkok, Thailand") is sent to the Claude API to generate scam warnings, tipping notes, and driver phrases. No address-level detail is included.',
  },
  {
    q: 'Is Hootling affiliated with any taxi company?',
    a: 'No. Hootling is an independent travel reference tool with no affiliation with any taxi company, driver, dispatch service, or transportation authority.',
  },
  {
    q: 'What languages is the app available in?',
    a: 'Hootling is fully available in 12 languages: English, Spanish, French, German, Portuguese (Brazilian), Chinese (Simplified), Japanese, Korean, Hindi, Italian, Indonesian, and Vietnamese. The entire interface, AI-generated scam warnings, tipping advice, and driver phrases all respond in your selected language. Use the language selector in the bottom navigation bar to switch.',
  },
]}

export default function FaqPage() {
  const faqs = buildFaqs(getUSDPrices())

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(({ q, a, bullets }) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: bullets ? `${a} ${bullets.join(' ')}` : a,
      },
    })),
  }

  return (
    <>
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
    <div className="space-y-6 pb-4">
      <div className="flex items-center gap-3">
        <Link href="/" className="w-10 h-10 shrink-0 hover:opacity-90 transition-opacity">
          <img src="/images/owl/expressions/owl-confused.svg" alt="" aria-hidden="true" className="w-full h-full object-contain" />
        </Link>
        <div>
          <h1 className="text-xl font-bold text-white">Frequently Asked Questions</h1>
          <p className="text-xs text-zinc-500 mt-1">Everything you need to know about Hootling</p>
        </div>
      </div>

      <div className="space-y-3">
        {faqs.map(({ q, a, bullets }) => (
          <div key={q} className="rounded-2xl bg-zinc-900 border border-zinc-800 p-4 space-y-1.5">
            <p className="text-sm font-medium text-white leading-snug">{q}</p>
            <p className="text-sm text-zinc-400 leading-relaxed">{a}</p>
            {bullets && (
              <ul className="space-y-1 pt-0.5">
                {bullets.map((b) => (
                  <li key={b} className="flex items-start gap-2 text-sm text-zinc-400">
                    <span className="text-purple-400 shrink-0 mt-0.5">•</span>
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </div>

      <div className="rounded-2xl bg-zinc-900 border border-zinc-800 p-4 space-y-2">
        <p className="text-sm font-medium text-white">Still have a question?</p>
        <p className="text-sm text-zinc-400">
          Reach us at{' '}
          <a href="mailto:legal@hootling.com" className="text-purple-400 underline">
            legal@hootling.com
          </a>
          {' '}and we&apos;ll get back to you within 5 business days.
        </p>
      </div>

      <div className="pt-2 border-t border-zinc-800">
        <Link href="/" className="text-sm text-zinc-600 hover:text-zinc-400 transition-colors">
          ← Back to Hootling
        </Link>
      </div>
    </div>
    </>
  )
}
