import type { Metadata } from 'next'
import { FaqContent } from '@/components/pages/FaqContent'
import { getUSDPrices } from '@/lib/currency'
import { pageAlternates } from '@/lib/seo-helpers'

const PAGE_URL = `${process.env.NEXT_PUBLIC_APP_URL ?? 'https://hootling.com'}/faq`

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about Hootling — pricing, accuracy, coverage, privacy, and how to get a refund.',
  alternates: { canonical: PAGE_URL, ...pageAlternates(PAGE_URL) },
}

// JSON-LD schema stays server-side for SEO — uses English source strings
function buildJsonLd() {
  const { single, pass, bundle } = getUSDPrices()
  const p = { single, pass, bundle }
  const faqs = [
    { q: 'How much does it cost?', a: `From ${p.single} USD per query. Single query: ${p.single}, DayPass: ${p.pass}, 20-query bundle: ${p.bundle}.` },
    { q: 'What payment methods are accepted?', a: 'Stripe — major cards, Apple Pay, Google Pay.' },
    { q: 'How accurate are the fare estimates?', a: 'Calculated from local taxi rates + Google Maps distance. ±15% range applied.' },
    { q: 'Which cities are covered for taxi fares?', a: '120+ cities across every continent.' },
    { q: 'Which countries are covered for tipping?', a: '50+ countries, 6 scenarios each.' },
    { q: 'What are the scam warnings based on?', a: 'AI-generated by Anthropic Claude, city-specific, cached 90 days.' },
    { q: 'Do I need to create an account?', a: 'No accounts, no sign-up, no login.' },
    { q: 'Can I get a refund?', a: 'Results are delivered instantly — email hello@hootling.com within 7 days if your result was not delivered due to a technical failure.' },
    { q: 'Is my payment data stored?', a: 'No. Stripe handles all card data.' },
    { q: 'Does Hootling track my location?', a: 'No GPS used. Addresses typed manually.' },
    { q: 'What languages is the app available in?', a: '14 languages: English, Spanish, French, German, Portuguese, Italian, Indonesian, Vietnamese, Thai, Simplified Chinese, Traditional Chinese, Japanese, Korean, Hindi.' },
  ]
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(({ q, a }) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a },
    })),
  }
}

export default function FaqPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(buildJsonLd()) }} />
      <FaqContent />
    </>
  )
}
